/**
 * This file is part of the NocoBase (R) project.
 * Copyright (c) 2020-2024 NocoBase Co., Ltd.
 * Authors: NocoBase Team.
 *
 * This project is dual-licensed under AGPL-3.0 and NocoBase Commercial License.
 * For more information, please refer to: https://www.nocobase.com/agreement.
 */

import fs from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';

import ts from 'typescript';

import {
  buildRunJSTypeScriptEnvironmentFiles,
  RUNJS_TYPESCRIPT_LIB_FILE_NAMES,
  RUNJS_TYPESCRIPT_ENVIRONMENT_LIBRARY_NAME,
  RUNJS_TYPESCRIPT_ENVIRONMENT_PACK_ID,
  type RunJSTypeScriptLibSource,
} from '../src/typescript-environment';

export interface RunJSTypeScriptEnvironmentGeneratorIO {
  error(message: string): void;
  log(message: string): void;
}

export async function runTypeScriptEnvironmentGeneratorCli(
  args: readonly string[],
  options: { outputPath?: string; projectRoot?: string; io?: RunJSTypeScriptEnvironmentGeneratorIO } = {},
): Promise<number> {
  const unknownArguments = args.filter((argument) => argument !== '--check');
  const io = options.io || console;
  if (unknownArguments.length) {
    io.error(`Unknown arguments: ${unknownArguments.join(', ')}`);
    return 1;
  }

  const projectRoot = path.resolve(options.projectRoot || path.resolve(__dirname, '../../../..'));
  const outputPath = path.resolve(
    options.outputPath ||
      path.join(
        projectRoot,
        'packages/core/client-v2/src/flow/components/code-editor/generated/runJSTypeScriptEnvironmentFiles.ts',
      ),
  );
  const artifact = renderArtifact(readTypeScriptLibraries());

  if (args.includes('--check')) {
    const current = await fs.readFile(outputPath, 'utf8').catch(() => '');
    if (current !== artifact) {
      io.error(`RunJS TypeScript environment artifact is out of date: ${outputPath}`);
      return 1;
    }
    io.log(`RunJS TypeScript environment artifact is current (${artifact.length} bytes).`);
    return 0;
  }

  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, artifact, 'utf8');
  io.log(`Generated RunJS TypeScript environment artifact (${artifact.length} bytes).`);
  return 0;
}

function readTypeScriptLibraries(): RunJSTypeScriptLibSource[] {
  const libDirectory = path.dirname(ts.getDefaultLibFilePath({ target: ts.ScriptTarget.ES2020 }));
  return RUNJS_TYPESCRIPT_LIB_FILE_NAMES.map((fileName) => {
    const content = ts.sys.readFile(path.join(libDirectory, fileName));
    if (typeof content !== 'string') throw new Error(`Unable to read TypeScript standard library: ${fileName}`);
    return { content, fileName };
  });
}

function renderArtifact(sources: readonly RunJSTypeScriptLibSource[]): string {
  const environmentFiles = buildRunJSTypeScriptEnvironmentFiles(sources);
  const rootFiles = environmentFiles.map((file) => ({
    ...file,
    contentHash: createHash('sha256').update(file.content).digest('hex'),
  }));
  const contentHash = createHash('sha256')
    .update(JSON.stringify(rootFiles.map((file) => ({ contentHash: file.contentHash, path: file.path }))))
    .digest('hex');
  return `/**
 * This file is part of the NocoBase (R) project.
 * Copyright (c) 2020-2024 NocoBase Co., Ltd.
 * Authors: NocoBase Team.
 *
 * This project is dual-licensed under AGPL-3.0 and NocoBase Commercial License.
 * For more information, please refer to: https://www.nocobase.com/agreement.
 */
// Generated by @nocobase/runjs TypeScript environment generator. Do not edit.
/* eslint-disable */

import type { RunJSTypeLibraryPack } from '@nocobase/runjs/client-v2';

export const runJSTypeScriptEnvironmentPack: RunJSTypeLibraryPack = ${JSON.stringify(
    {
      id: RUNJS_TYPESCRIPT_ENVIRONMENT_PACK_ID,
      libraryName: RUNJS_TYPESCRIPT_ENVIRONMENT_LIBRARY_NAME,
      version: ts.version,
      contentHash,
      dependencies: [],
      rootFiles,
      dependencyFiles: [],
    },
    null,
    2,
  )};
`;
}

if (require.main === module) {
  runTypeScriptEnvironmentGeneratorCli(process.argv.slice(2))
    .then((exitCode) => {
      process.exitCode = exitCode;
    })
    .catch((error: unknown) => {
      console.error(error);
      process.exitCode = 1;
    });
}
