// Generated by Grafana k6 Studio (1.7.0) on 2025-09-12T04:25:47.702Z

import { group, sleep, check } from 'k6';
import http from 'k6/http';
import execution from 'k6/execution';
import { uid } from '../../utils.js';

export const options = {
  stages: [
    // { target: 1, duration: '1s' },
    { target: 100, duration: '1s' },
    { target: 100, duration: '58s' },
    { target: 0, duration: '1s' },
    // { target: 100, duration: '30s' },
    // { target: 200, duration: '1m' },
    // { target: 200, duration: '1m' },
    // { target: 100, duration: '30s' },
    // { target: 0, duration: '30s' },
  ],
};

export default function () {
  let params;
  let resp;
  let match;
  let regex;
  let url;
  let token;
  const correlation_vars = {};

  group('Default group', function () {
    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        'Upgrade-Insecure-Requests': `1`,
        Accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/admin`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `text/css,*/*;q=0.1`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/global.css`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/browser-checker.js?v=1`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/umi.2793ffba.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.dayjs.45ed1676.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.entities.8159ac3e.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.lodash-es.99877438.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.uuid.15e7bb90.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm._at_ant-design.5b9b3ce7.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.antd.168d1e29.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `text/css,*/*;q=0.1`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/p__index.b415ed71.chunk.css`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm._at_antv.56fcebdf.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.mathjs.fd97f3b7.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm._at_formily.f71b1c62.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.lodash.5dcc1c5e.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm._at_rc-component.5f4cc5e2.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.rc-picker.89eafb74.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.ahooks.c5b165dc.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.rc-table.c5aa8a0d.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.rc-cascader.cf6ec555.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.rc-tree-select.5597dcbf.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.axios.29caebe1.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.rc-select.44fb85b4.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm._at_budibase.b1200847.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm._at_umijs.7f6c4722.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.handlebars.ade4c4fe.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.sanitize-html.506a0a55.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.rc-menu.da4ef0ce.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.html5-qrcode.e32faec8.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.rc-image.d550fa79.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.rc-slider.d2d511ab.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.rc-tree.49888c60.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.htmlparser2.1a3babb6.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.picomatch.af2fa5bc.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.gl-matrix.d851d654.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm._at_dnd-kit.ebb2cc42.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.react-dom.b9fb5fd7.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.react-image-lightbox.264960e7.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.i18next.98bb572b.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.decimal.js.19391b1c.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.bignumber.js.cb49cd48.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm._at_formulajs.0bdd8ac2.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.react-router-dom.2109af81.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.moment.36abbf2c.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.jstat.733c0b2c.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.json5.d58066fd.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/npm.buffer.bc3fb79b.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/6858.082255a5.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/p__index.f3ede44c.async.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        'X-Role': `anonymous`,
        Accept: `application/json, text/plain, */*`,
        'X-Timezone': `+08:00`,
        'X-With-ACL-Meta': `true`,
        'X-Hostname': `192.168.11.130`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/app:getLang`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/favicon_no_exist.ico`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        'X-Timezone': `+08:00`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        'X-Hostname': `192.168.11.130`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/pm:listEnabled`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-acl/dist/client/index.js?version=1.8.23&t=1756867850000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-action-bulk-edit/dist/client/index.js?version=1.8.23&t=1756867850000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-action-bulk-update/dist/client/index.js?version=1.8.23&t=1756867850000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-action-custom-request/dist/client/index.js?version=1.8.23&t=1756867850000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-action-duplicate/dist/client/index.js?version=1.8.23&t=1756867850000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-action-export/dist/client/index.js?version=1.8.23&t=1756867851000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-action-import/dist/client/index.js?version=1.8.23&t=1756867850000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-action-print/dist/client/index.js?version=1.8.23&t=1756867851000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-auth/dist/client/index.js?version=1.8.23&t=1756867852000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-async-task-manager/dist/client/index.js?version=1.8.23&t=1756867851000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-ai/dist/client/index.js?version=1.8.23&t=1756867851000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-block-iframe/dist/client/index.js?version=1.8.23&t=1756867853000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-block-workbench/dist/client/index.js?version=1.8.23&t=1756867852000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-calendar/dist/client/index.js?version=1.8.23&t=1756867853000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-client/dist/client/index.js?version=1.8.23&t=1756867853000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-collection-sql/dist/client/index.js?version=1.8.23&t=1756867853000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-collection-tree/dist/client/index.js?version=1.8.23&t=1756867853000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-data-source-main/dist/client/index.js?version=1.8.23&t=1756867854000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-data-source-manager/dist/client/index.js?version=1.8.23&t=1756867853000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-data-visualization/dist/client/index.js?version=1.8.23&t=1756867854000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-environment-variables/dist/client/index.js?version=1.8.23&t=1756867854000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-error-handler/dist/client/index.js?version=1.8.23&t=1756867854000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-field-formula/dist/client/index.js?version=1.8.23&t=1756867854000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-field-sequence/dist/client/index.js?version=1.8.23&t=1756867854000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-field-sort/dist/client/index.js?version=1.8.23&t=1756867855000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-file-manager/dist/client/index.js?version=1.8.23&t=1756867854000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-gantt/dist/client/index.js?version=1.8.23&t=1756867855000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-text-copy/dist/client/index.js?version=1.8.23&t=1756867856000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-kanban/dist/client/index.js?version=1.8.23&t=1756867855000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-logger/dist/client/index.js?version=1.8.23&t=1756867855000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-notification-manager/dist/client/index.js?version=1.8.23&t=1756867856000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-notification-in-app-message/dist/client/index.js?version=1.8.23&t=1756867856000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-mobile/dist/client/index.js?version=1.8.23&t=1756867855000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-system-settings/dist/client/index.js?version=1.8.23&t=1756867856000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-ui-schema-storage/dist/client/index.js?version=1.8.23&t=1756867856000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-user-data-sync/dist/client/index.js?version=1.8.23&t=1756867856000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-users/dist/client/index.js?version=1.8.23&t=1756867856000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-verification/dist/client/index.js?version=1.8.23&t=1756867856000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-workflow/dist/client/index.js?version=1.8.23&t=1756867856000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-workflow-action-trigger/dist/client/index.js?version=1.8.23&t=1756867856000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-workflow-aggregate/dist/client/index.js?version=1.8.23&t=1756867856000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-workflow-delay/dist/client/index.js?version=1.8.23&t=1756867857000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-workflow-loop/dist/client/index.js?version=1.8.23&t=1756867857000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-workflow-parallel/dist/client/index.js?version=1.8.23&t=1756867857000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-workflow-request/dist/client/index.js?version=1.8.23&t=1756867857000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-workflow-sql/dist/client/index.js?version=1.8.23&t=1756867857000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-workflow-notification/dist/client/index.js?version=1.8.23&t=1756867857000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-theme-editor/dist/client/index.js?version=1.8.23&t=1756867856000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-block-template/dist/client/index.js?version=1.8.23&t=1756867853000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-license/dist/client/index.js?version=1.8.23&t=1756867855000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-backups/dist/client/index.js?version=1.8.23&t=1757439042000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-lock-adapter-redis/dist/client/index.js?version=1.8.22&t=1756791347000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-pubsub-adapter-redis/dist/client/index.js?version=1.8.22&t=1756791390000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-queue-adapter-redis/dist/client/index.js?version=1.8.22&t=1756791402000`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-auth/dist/client/949aa789879cb8b0.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/favicon/favicon.ico`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        'X-Timezone': `+08:00`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        'X-Hostname': `192.168.11.130`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/auth:check`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 401': (r) => r.status === 401 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-data-source-manager/dist/client/ea8518999398682d.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        'X-Timezone': `+08:00`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        'X-Hostname': `192.168.11.130`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/systemSettings:get`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-theme-editor/dist/client/f54828f43cde7d12.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        'X-Timezone': `+08:00`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        'X-Hostname': `192.168.11.130`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/roles:check`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 401': (r) => r.status === 401 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        'X-Timezone': `+08:00`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        'X-Hostname': `192.168.11.130`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/themeConfig:list?sort=id&paginate=false`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/signin?redirect=/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-auth/dist/client/33daef301eb29bcf.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        'X-Timezone': `+08:00`,
        'Content-Type': `application/json`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        'X-Hostname': `192.168.11.130`,
        Origin: `${__ENV.TARGET_ORIGIN}`,
        Referer: `${__ENV.TARGET_ORIGIN}/signin?redirect=/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/authenticators:publicList`;
    resp = http.request('POST', url, `{}`, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `*/*`,
        Referer: `${__ENV.TARGET_ORIGIN}/signin?redirect=/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/static/plugins/@nocobase/plugin-auth/dist/client/662f930270b54313.js`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Hostname': `192.168.11.130`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'Content-Type': `application/json`,
        'X-Locale': `en-US`,
        Origin: `${__ENV.TARGET_ORIGIN}`,
        Referer: `${__ENV.TARGET_ORIGIN}/signin?redirect=/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/auth:signIn`;
    resp = http.request('POST', url, `{"account":"nocobase","password":"admin123"}`, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    token = resp.json('data.token');

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Hostname': `192.168.11.130`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/signin?redirect=/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/auth:check`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Hostname': `192.168.11.130`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/roles:check`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Hostname': `192.168.11.130`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/blockTemplates:list?filter[configured][$isTruly]=true&filter[type][$ne]=Mobile&paginate=false`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Hostname': `192.168.11.130`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/themeConfig:list?sort=id&paginate=false`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Hostname': `192.168.11.130`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'Content-Type': `application/json`,
        'X-Locale': `en-US`,
        Origin: `${__ENV.TARGET_ORIGIN}`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/userWorkflowTasks:listMine?filter=%7B%22type%22:[]%7D`;
    resp = http.request('POST', url, `{}`, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Hostname': `192.168.11.130`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/environmentVariables?paginate=false`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Hostname': `192.168.11.130`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/systemSettings:get`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Hostname': `192.168.11.130`,
        'X-Role': `root`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/desktopRoutes:listAccessible?tree=true&sort=sort`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/flwak70a1tp`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/storage/uploads/logo-n0msv8.png`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Hostname': `192.168.11.130`,
        'X-Role': `root`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/flwak70a1tp`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/asyncTasks:list`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Hostname': `192.168.11.130`,
        'X-Role': `root`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/flwak70a1tp`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/myInAppMessages:count?filter[status]=unread`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Hostname': `192.168.11.130`,
        'X-Role': `root`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/flwak70a1tp`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/uiSchemaTemplates:list?paginate=false`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Hostname': `192.168.11.130`,
        'X-Role': `root`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/flwak70a1tp`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/app:getInfo`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Hostname': `192.168.11.130`,
        'X-Role': `root`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'Content-Type': `application/json`,
        'X-Locale': `en-US`,
        Origin: `${__ENV.TARGET_ORIGIN}`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/flwak70a1tp`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/dataSources:listEnabled?paginate=false&appends[]=collections`;
    resp = http.request('POST', url, `{}`, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Hostname': `192.168.11.130`,
        'X-Role': `root`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/flwak70a1tp`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/uiSchemas:getJsonSchema/flwak70a1tp`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Hostname': `192.168.11.130`,
        'X-Role': `root`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'Content-Type': `application/json`,
        'X-Locale': `en-US`,
        Origin: `${__ENV.TARGET_ORIGIN}`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/flwak70a1tp`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/collections:listMeta`;
    resp = http.request('POST', url, `{}`, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Hostname': `192.168.11.130`,
        'X-Role': `root`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/flwak70a1tp`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/uiSchemas:getJsonSchema/p8r7e2uagi2`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Hostname': `192.168.11.130`,
        'X-Role': `root`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/flwak70a1tp`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/posts:list?pageSize=20&appends[]=category&appends[]=tags&appends[]=createdBy&appends[]=updatedBy&filter=%7B%7D`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Hostname': `192.168.11.130`,
        'X-Role': `root`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/flwak70a1tp/popups/6jpajycbqcl`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/categories:list?pageSize=200&filter=%7B%7D`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Hostname': `192.168.11.130`,
        'X-Role': `root`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/flwak70a1tp/popups/6jpajycbqcl`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/tags:list?pageSize=200&filter=%7B%7D`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Hostname': `192.168.11.130`,
        'X-Role': `root`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'Content-Type': `application/json`,
        'X-Locale': `en-US`,
        Origin: `${__ENV.TARGET_ORIGIN}`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/flwak70a1tp/popups/6jpajycbqcl`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/posts:create`;
    resp = http.request(
      'POST',
      url,
      JSON.stringify({
        allowComments: true,
        featured: false,
        viewCount: 3,
        read: 0,
        score: 0,
        title: uid(),
        subTitle: uid(),
        content: uid(),
        slug: uid(),
        musicUrl: uid(),
        excerpt: uid(),
        coverImage: uid(),
        publishedAt: '2025-09-11T15:25:28.000Z',
        category: {
          lastPostedAt: null,
          id: 11,
          createdAt: '2025-09-09T18:55:29.470Z',
          updatedAt: '2025-09-09T18:55:29.470Z',
          title: 'ducimus fugit suspendo',
          subTitle: 'Subiungo cresco texo admiratio velit canonicus patria adsidue ex.',
          description:
            'Adduco iusto laudantium. Ratione umerus totidem cursus vergo conventus pectus explicabo. Sonitus vilicus creator vester ubi crur.',
          slug: '0wpdu0easwd',
          sort: 10,
          coverImageUrl: 'https://loremflickr.com/640/480?lock=3311738422296576',
          url: 'https://frightening-antling.info',
          followerCount: 1061,
          articleCount: 0,
          hidden: false,
          themeColor: '#7c181c',
          icon: 'ð³ï¸',
          allowComments: true,
          parentId: null,
          moderatorId: null,
          createdById: null,
          updatedById: null,
        },
        tags: [
          {
            lastUsedAt: null,
            id: 6,
            createdAt: '2025-09-09T18:55:29.510Z',
            updatedAt: '2025-09-09T18:55:29.510Z',
            name: '9q74kvldzix',
            description: 'Studio abutor quia cilicium sumptus defessus.',
            color: '#342624',
            icon: 'ð',
            slug: 'o78niik6cpf',
            isFeatured: false,
            usageCount: 0,
            followerCount: 2921,
            synonyms: null,
            isOfficial: false,
            moderationStatus: 'approved',
            group: 'tertius',
            seoTitle: 'Thermae constans atqui vinculum adfectus quibusdam demergo venia vespillo.',
            seoDescription:
              'Laboriosam acerbitas sui. Usque tametsi absens uredo minus condico creptio crux tamisium. Coerceo spes debeo ocer adsidue paulatim.',
            reviewNotes: null,
            curatorId: null,
            createdById: null,
            updatedById: null,
          },
          {
            lastUsedAt: null,
            id: 5,
            createdAt: '2025-09-09T18:55:29.510Z',
            updatedAt: '2025-09-09T18:55:29.510Z',
            name: '028oixvc0gq',
            description: 'Acsi vilis somniculosus vobis temeritas.',
            color: '#52143f',
            icon: 'ð§',
            slug: 's4d4nd925dp',
            isFeatured: true,
            usageCount: 0,
            followerCount: 682,
            synonyms: null,
            isOfficial: true,
            moderationStatus: 'approved',
            group: 'tepesco',
            seoTitle: 'Apostolus acerbitas vespillo adversus decimus toties.',
            seoDescription:
              'Vicissitudo sum admoneo ambulo decimus sufficio. Derideo clamo veritatis canonicus. Arca cura valeo suffoco decimus delego thesis aeneus cultura sophismata.',
            reviewNotes: null,
            curatorId: null,
            createdById: null,
            updatedById: null,
          },
        ],
      }),
      params,
    );

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Hostname': `192.168.11.130`,
        'X-Role': `root`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/flwak70a1tp/popups/6jpajycbqcl`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/posts:list?pageSize=20&appends[]=category&appends[]=tags&appends[]=createdBy&appends[]=updatedBy&filter=%7B%7D`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });
  });
  sleep(1);
}
