// Generated by Grafana k6 Studio (1.7.0) on 2025-09-11T15:31:05.716Z

import { group, sleep, check } from 'k6';
import http from 'k6/http';

import { uid } from '../../utils.js';

export const options = {
  stages: [
    // { target: 1, duration: '1s' },
    // { target: 100, duration: '1s' },
    // { target: 100, duration: '58s' },
    // { target: 0, duration: '1s' },

    // 10min
    { target: 100, duration: '30s' },
    { target: 200, duration: '30s' },
    { target: 200, duration: '8m' },
    { target: 100, duration: '30s' },
    { target: 0, duration: '30s' },
  ],
};

export default function () {
  let params;
  let resp;
  let match;
  let regex;
  let url;
  let token;
  const correlation_vars = {};

  group('Default group', function () {
    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        'Upgrade-Insecure-Requests': `1`,
        Accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/admin/`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        'X-Role': `anonymous`,
        Accept: `application/json, text/plain, */*`,
        'X-Timezone': `+08:00`,
        'X-With-ACL-Meta': `true`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/app:getLang`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        'X-Timezone': `+08:00`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/pm:listEnabled`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        'X-Timezone': `+08:00`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/auth:check`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 401': (r) => r.status === 401 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        'X-Timezone': `+08:00`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/systemSettings:get`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        'X-Timezone': `+08:00`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/roles:check`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 401': (r) => r.status === 401 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        'X-Timezone': `+08:00`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/themeConfig:list?sort=id&paginate=false`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Accept: `application/json, text/plain, */*`,
        'X-Timezone': `+08:00`,
        'Content-Type': `application/json`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Origin: `${__ENV.ORIGIN}`,
        Referer: `${__ENV.ORIGIN}/signin?redirect=/admin/`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/authenticators:publicList`;
    resp = http.request('POST', url, `{}`, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'Content-Type': `application/json`,
        'X-Locale': `en-US`,
        Origin: `${__ENV.ORIGIN}`,
        Referer: `${__ENV.ORIGIN}/signin?redirect=/admin/`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/auth:signIn`;
    resp = http.request('POST', url, JSON.stringify({ account: __ENV.USERNAME, password: __ENV.PASSWORD }), params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    token = resp.json('data.token');

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.ORIGIN}/signin?redirect=/admin/`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/auth:check`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/roles:check`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/blockTemplates:list?filter[configured][$isTruly]=true&filter[type][$ne]=Mobile&paginate=false`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/themeConfig:list?sort=id&paginate=false`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'Content-Type': `application/json`,
        'X-Locale': `en-US`,
        Origin: `${__ENV.ORIGIN}`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/userWorkflowTasks:listMine?filter=%7B%22type%22:[]%7D`;
    resp = http.request('POST', url, `{}`, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/environmentVariables?paginate=false`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/systemSettings:get`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Role': `root`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/desktopRoutes:listAccessible?tree=true&sort=sort`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Role': `root`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/flwak70a1tp`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/asyncTasks:list`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Role': `root`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/flwak70a1tp`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/myInAppMessages:count?filter[status]=unread`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Role': `root`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/flwak70a1tp`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/uiSchemaTemplates:list?paginate=false`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Role': `root`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/flwak70a1tp`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/app:getInfo`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Role': `root`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'Content-Type': `application/json`,
        'X-Locale': `en-US`,
        Origin: `${__ENV.ORIGIN}`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/flwak70a1tp`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/dataSources:listEnabled?paginate=false&appends[]=collections`;
    resp = http.request('POST', url, `{}`, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Role': `root`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/flwak70a1tp`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/uiSchemas:getJsonSchema/flwak70a1tp`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Role': `root`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'Content-Type': `application/json`,
        'X-Locale': `en-US`,
        Origin: `${__ENV.ORIGIN}`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/flwak70a1tp`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/collections:listMeta`;
    resp = http.request('POST', url, `{}`, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Role': `root`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/flwak70a1tp`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/uiSchemas:getJsonSchema/p8r7e2uagi2`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Role': `root`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/flwak70a1tp`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/posts:list?pageSize=20&appends[]=category&appends[]=tags&appends[]=createdBy&appends[]=updatedBy&filter=%7B%7D`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Role': `root`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/flwak70a1tp/popups/6jpajycbqcl`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/categories:list?pageSize=200&filter=%7B%7D`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Role': `root`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/flwak70a1tp/popups/6jpajycbqcl`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/tags:list?pageSize=200&filter=%7B%7D`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Role': `root`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'Content-Type': `application/json`,
        'X-Locale': `en-US`,
        Origin: `${__ENV.ORIGIN}`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/flwak70a1tp/popups/6jpajycbqcl`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/posts:create`;
    resp = http.request(
      'POST',
      url,
      JSON.stringify({
        allowComments: true,
        featured: false,
        viewCount: 3,
        read: 0,
        score: 0,
        title: uid(),
        subTitle: uid(),
        content: uid(),
        slug: uid(),
        musicUrl: uid(),
        excerpt: uid(),
        coverImage: uid(),
        publishedAt: '2025-09-11T15:25:28.000Z',
        category: {
          lastPostedAt: null,
          id: 11,
          createdAt: '2025-09-09T18:55:29.470Z',
          updatedAt: '2025-09-09T18:55:29.470Z',
          title: 'ducimus fugit suspendo',
          subTitle: 'Subiungo cresco texo admiratio velit canonicus patria adsidue ex.',
          description:
            'Adduco iusto laudantium. Ratione umerus totidem cursus vergo conventus pectus explicabo. Sonitus vilicus creator vester ubi crur.',
          slug: '0wpdu0easwd',
          sort: 10,
          coverImageUrl: 'https://loremflickr.com/640/480?lock=3311738422296576',
          url: 'https://frightening-antling.info',
          followerCount: 1061,
          articleCount: 0,
          hidden: false,
          themeColor: '#7c181c',
          icon: 'ð³ï¸',
          allowComments: true,
          parentId: null,
          moderatorId: null,
          createdById: null,
          updatedById: null,
        },
        tags: [
          {
            lastUsedAt: null,
            id: 6,
            createdAt: '2025-09-09T18:55:29.510Z',
            updatedAt: '2025-09-09T18:55:29.510Z',
            name: '9q74kvldzix',
            description: 'Studio abutor quia cilicium sumptus defessus.',
            color: '#342624',
            icon: 'ð',
            slug: 'o78niik6cpf',
            isFeatured: false,
            usageCount: 0,
            followerCount: 2921,
            synonyms: null,
            isOfficial: false,
            moderationStatus: 'approved',
            group: 'tertius',
            seoTitle: 'Thermae constans atqui vinculum adfectus quibusdam demergo venia vespillo.',
            seoDescription:
              'Laboriosam acerbitas sui. Usque tametsi absens uredo minus condico creptio crux tamisium. Coerceo spes debeo ocer adsidue paulatim.',
            reviewNotes: null,
            curatorId: null,
            createdById: null,
            updatedById: null,
          },
          {
            lastUsedAt: null,
            id: 5,
            createdAt: '2025-09-09T18:55:29.510Z',
            updatedAt: '2025-09-09T18:55:29.510Z',
            name: '028oixvc0gq',
            description: 'Acsi vilis somniculosus vobis temeritas.',
            color: '#52143f',
            icon: 'ð§',
            slug: 's4d4nd925dp',
            isFeatured: true,
            usageCount: 0,
            followerCount: 682,
            synonyms: null,
            isOfficial: true,
            moderationStatus: 'approved',
            group: 'tepesco',
            seoTitle: 'Apostolus acerbitas vespillo adversus decimus toties.',
            seoDescription:
              'Vicissitudo sum admoneo ambulo decimus sufficio. Derideo clamo veritatis canonicus. Arca cura valeo suffoco decimus delego thesis aeneus cultura sophismata.',
            reviewNotes: null,
            curatorId: null,
            createdById: null,
            updatedById: null,
          },
        ],
      }),
      params,
    );

    check(resp, { 'status equals 200': (r) => r.status === 200 });

    params = {
      headers: {
        'Proxy-Connection': `keep-alive`,
        Authorization: `Bearer ${token}`,
        'X-Authenticator': `basic`,
        'X-Timezone': `+08:00`,
        'X-Role': `root`,
        Accept: `application/json, text/plain, */*`,
        'X-With-ACL-Meta': `true`,
        'X-Locale': `en-US`,
        Referer: `${__ENV.TARGET_ORIGIN}/admin/flwak70a1tp/popups/6jpajycbqcl`,
        'Accept-Encoding': `gzip, deflate`,
        'Accept-Language': `zh-CN,zh;q=0.9`,
      },
      cookies: {},
    };

    url = http.url`${__ENV.TARGET_ORIGIN}/api/posts:list?pageSize=20&appends[]=category&appends[]=tags&appends[]=createdBy&appends[]=updatedBy&filter=%7B%7D`;
    resp = http.request('GET', url, null, params);

    check(resp, { 'status equals 200': (r) => r.status === 200 });
  });

  sleep(1);
}
