// Deployment targets. A remote is one App on one Hub, named the way a git remote is, and the list lives in the
// project's `.nocobase/hub.json` so everyone who checks the project out deploys to the same places. The file holds
// addresses only; API keys live in the user's credentials file.
import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { HubCliError } from './errors.ts';

/** The project file the remotes are kept in, relative to the App root. */
export const REMOTES_FILE: string = '.nocobase/hub.json';

/** What a remote URL names: the Hub, and the App on it. */
export interface RemoteTarget {
  /** The remote URL as written in `.nocobase/hub.json`, normalized. */
  readonly url: string;
  /** The Hub application URL, including its mount path, such as `https://hub.example/main`. */
  readonly hub: string;
  readonly appId: string;
}

export interface Remote extends RemoteTarget {
  readonly name: string;
}

/** The content of `.nocobase/hub.json`. */
export interface RemotesFile {
  default?: string;
  remotes: Record<string, string>;
}

const REMOTE_NAME = /^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/;
const APP_ID = /^[A-Za-z0-9_-]+$/;

/**
 * Splits a remote URL, `<Hub URL>/apps/<App ID>`, at its last `/apps/` segment, so a Hub mounted under a path that
 * itself contains `apps` still parses.
 */
export function parseRemoteUrl(input: string): RemoteTarget {
  let url: URL;
  try {
    url = new URL(input.trim());
  } catch {
    throw invalidRemoteUrl();
  }
  if (
    !['http:', 'https:'].includes(url.protocol) ||
    url.username ||
    url.password ||
    url.search ||
    url.hash
  )
    throw invalidRemoteUrl();
  const pathname = url.pathname.replace(/\/+$/, '');
  const index = pathname.lastIndexOf('/apps/');
  const appId = index === -1 ? '' : pathname.slice(index + '/apps/'.length);
  if (!APP_ID.test(appId)) throw invalidRemoteUrl();
  const hub = `${url.origin}${pathname.slice(0, index)}`;
  return { url: `${hub}/apps/${appId}`, hub, appId };
}

export function assertRemoteName(name: string): void {
  if (!REMOTE_NAME.test(name))
    throw new HubCliError(
      'INVALID_REMOTE_NAME',
      'A remote name is 1–64 letters, digits, dots, underscores or hyphens, starting with a letter or digit.',
      2,
    );
}

export async function readRemotes(root: string): Promise<RemotesFile> {
  let text: string;
  try {
    text = await readFile(path.join(root, REMOTES_FILE), 'utf8');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT')
      return { remotes: {} };
    throw invalidRemotesFile();
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch {
    throw invalidRemotesFile();
  }
  if (!isRecord(parsed) || !isRecord(parsed.remotes))
    throw invalidRemotesFile();
  const remotes: Record<string, string> = {};
  for (const [name, url] of Object.entries(parsed.remotes)) {
    if (!REMOTE_NAME.test(name) || typeof url !== 'string')
      throw invalidRemotesFile();
    remotes[name] = url;
  }
  const file: RemotesFile = { remotes };
  if (parsed.default !== undefined) {
    if (typeof parsed.default !== 'string' || !REMOTE_NAME.test(parsed.default))
      throw invalidRemotesFile();
    file.default = parsed.default;
  }
  return file;
}

export async function writeRemotes(
  root: string,
  file: RemotesFile,
): Promise<void> {
  const target = path.join(root, REMOTES_FILE);
  await mkdir(path.dirname(target), { recursive: true });
  const ordered: RemotesFile = {
    ...(file.default === undefined ? {} : { default: file.default }),
    remotes: file.remotes,
  };
  // Written beside the target and renamed over it, so a failed write never leaves half a file behind.
  const temporary = `${target}.${process.pid}.tmp`;
  await writeFile(temporary, `${JSON.stringify(ordered, null, 2)}\n`);
  await rename(temporary, target);
}

/**
 * Whether the App root's `.gitignore` keeps `.nocobase/hub.json` out of version control. Applications generated by
 * `@nocobase/create-app` before the file existed ignore the whole `.nocobase/` directory, so a remote added there
 * would silently never reach another checkout.
 */
export async function remotesIgnoredByGit(root: string): Promise<boolean> {
  let text: string;
  try {
    text = await readFile(path.join(root, '.gitignore'), 'utf8');
  } catch {
    return false;
  }
  return text.split(/\r?\n/u).some((line) => {
    const pattern = line.trim().replace(/^\//u, '').replace(/\/$/u, '');
    return pattern === '.nocobase' || pattern === REMOTES_FILE;
  });
}

/** The remote a command acts on: the one `--remote` names, otherwise the default. */
export async function resolveRemote(
  root: string,
  name: string | undefined,
): Promise<Remote> {
  const file = await readRemotes(root);
  const selected = name ?? file.default;
  if (selected === undefined) {
    throw new HubCliError(
      'NO_REMOTE',
      Object.keys(file.remotes).length === 0
        ? `No remote is configured. Add one with hub remote add <name> <url>; it is saved in ${REMOTES_FILE}.`
        : `No default remote is set. Pass --remote, or set "default" in ${REMOTES_FILE}.`,
      2,
    );
  }
  // An own property only: the names are user input, and `constructor` or `__proto__` would otherwise resolve.
  const url = Object.hasOwn(file.remotes, selected)
    ? file.remotes[selected]
    : undefined;
  if (url === undefined)
    throw new HubCliError(
      'NO_REMOTE',
      `Remote "${selected}" is not in ${REMOTES_FILE}. List the remotes with hub remote list.`,
      2,
    );
  return { name: selected, ...parseRemoteUrl(url) };
}

function invalidRemoteUrl(): HubCliError {
  return new HubCliError(
    'INVALID_REMOTE_URL',
    'A remote URL is <Hub URL>/apps/<App ID>, such as https://hub.example/main/apps/crm: HTTP(S), without credentials, query or fragment.',
    2,
  );
}

function invalidRemotesFile(): HubCliError {
  return new HubCliError(
    'INVALID_REMOTES_FILE',
    `${REMOTES_FILE} is not readable JSON of the form { "default": "<name>", "remotes": { "<name>": "<url>" } }.`,
    2,
  );
}

export function isRecord(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}
