import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { parse } from 'yaml';

import { buildConfigFile, generateAuthSecret } from '../src/lib/config-file.ts';

const packageRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '..',
);

/**
 * The real example from the default template, so the placeholders this module rewrites are tested against the file it
 * will actually be handed rather than against a fixture that can quietly diverge from it.
 */
async function readDefaultTemplateExample(): Promise<string> {
  return readFile(
    path.join(
      packageRoot,
      '../../templates/app-template-default/config.example.yml',
    ),
    'utf8',
  );
}

const KEY = 'k'.repeat(64);

function parsed(config: string): Record<string, unknown> {
  return parse(config) as Record<string, unknown>;
}

describe('buildConfigFile', () => {
  it('fills in the first secrets key in an example that declares secrets.keys', () => {
    // The shape the templates' config.example.yml takes once they move from auth.secret and session.secret to
    // secrets.keys; the templates still carry the older shape, which the test below covers.
    const config = buildConfigFile({
      example: [
        'secrets:',
        '  keys:',
        '    - version: 1',
        '      key: replace-with-a-unique-secret',
        '',
        'auth:',
        '  emailAndPassword:',
        '    enabled: true',
      ].join('\n'),
      secretsKey: KEY,
    });

    expect(parsed(config).secrets).toEqual({
      keys: [{ version: 1, key: KEY }],
    });
    expect(config).not.toContain('replace-with-a-unique-secret');
    expect(parsed(config).auth).not.toHaveProperty('secret');
    expect(parsed(config)).not.toHaveProperty('session.secret');
  });

  /** The example is the only documentation of what an application can be configured with, so none of it is dropped. */
  it('keeps the rest of the example, comments included', async () => {
    const config = buildConfigFile({
      example: await readDefaultTemplateExample(),
      secretsKey: KEY,
    });

    expect(config).toContain('# Values under client are public');
    expect(config).toContain('notification:');
    expect(config).toContain('    title: NocoBase');
    expect(config).toContain('  workerId: 0');
  });

  it('replaces the example instruction with a generated header', async () => {
    const config = buildConfigFile({
      example: await readDefaultTemplateExample(),
      secretsKey: KEY,
    });

    expect(config.split('\n')[0]).toBe('# Generated by nocobase config init.');
    expect(config).not.toContain('Copy this file to config.yml');
  });

  /** A commented-out section has to end up live, and its explanatory comments have to survive the uncommenting. */
  it('uncomments a section rather than appending a duplicate key', () => {
    const config = buildConfigFile({
      example: [
        '# Copy this file to config.yml before starting.',
        '# secrets:',
        '#   # The first key is current.',
        '#   keys:',
        '#     - version: 1',
        '#       key: replace-with-a-unique-secret',
        '',
        'client:',
        '  app:',
        '    title: X',
      ].join('\n'),
      secretsKey: KEY,
    });

    expect(config).toContain('  # The first key is current.');
    expect(parsed(config).secrets).toEqual({
      keys: [{ version: 1, key: KEY }],
    });
    expect(config.match(/^secrets:/gmu)).toHaveLength(1);
  });

  it('adds the section when the example never mentions it', () => {
    const config = buildConfigFile({
      example: 'client:\n  app:\n    title: X\n',
      secretsKey: KEY,
    });

    expect(parsed(config).secrets).toEqual({
      keys: [{ version: 1, key: KEY }],
    });
  });

  it('still fills the live secrets of an older example', () => {
    const config = buildConfigFile({
      example: [
        'auth:',
        '  secret: replace-with-a-unique-secret',
        'session:',
        '  # Use the same value.',
        '  secret: replace-with-a-unique-secret',
      ].join('\n'),
      secret: 'test-secret',
      secretsKey: KEY,
    });

    expect(parsed(config)).toMatchObject({
      auth: { secret: 'test-secret' },
      session: { secret: 'test-secret' },
      secrets: { keys: [{ version: 1, key: KEY }] },
    });
  });

  it('generates a strong key when there is no example at all', () => {
    const config = buildConfigFile();
    const secrets = parsed(config).secrets as {
      keys: { version: number; key: string }[];
    };

    expect(secrets.keys).toHaveLength(1);
    expect(secrets.keys[0]!.version).toBe(1);
    expect(secrets.keys[0]!.key).toMatch(/^[0-9a-f]{64}$/u);
  });
});

describe('generateAuthSecret', () => {
  it('produces a distinct URL-safe secret each time', () => {
    const first = generateAuthSecret();
    const second = generateAuthSecret();

    expect(first).not.toBe(second);
    expect(first).toMatch(/^[\w-]+$/u);
    expect(first.length).toBeGreaterThanOrEqual(43);
  });
});
