export default [
  {
    key: 'p11jhxi44ua',
    name: 'users',
    title: '{{t("Users")}}',
    inherit: false,
    hidden: false,
    fields: [
      {
        key: '539j8plsr7g',
        name: 'id',
        type: 'bigInt',
        interface: 'id',
        collectionName: 'users',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: '7tokm32quhd',
        uiSchema: {
          'x-uid': '7tokm32quhd',
          name: 'h40texk2ibk',
          type: 'number',
          title: '{{t("ID")}}',
          'x-component': 'InputNumber',
          'x-read-pretty': true,
        },
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
      },
      {
        key: '2r4k4p0lp6v',
        name: 'nickname',
        type: 'string',
        interface: 'input',
        collectionName: 'users',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: 'pby3in1fpyp',
        uiSchema: {
          'x-uid': 'pby3in1fpyp',
          name: 'po6o5d80k4k',
          type: 'string',
          title: '{{t("Nickname")}}',
          'x-component': 'Input',
        },
      },
      {
        key: '5cb0uzzwwz3',
        name: 'email',
        type: 'string',
        interface: 'email',
        collectionName: 'users',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: 'nhg1ogufui7',
        uiSchema: {
          'x-uid': 'nhg1ogufui7',
          name: 'kjbj6hzy73c',
          type: 'string',
          title: '{{t("Email")}}',
          'x-component': 'Input',
          'x-validator': 'email',
          required: true,
        },
        unique: true,
      },
      {
        key: 'bq7vneqouj6',
        name: 'phone',
        type: 'string',
        interface: 'phone',
        collectionName: 'users',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: 'hwuxm4bsti2',
        uiSchema: {
          'x-uid': 'hwuxm4bsti2',
          name: 'xnfvwqtxonk',
          type: 'string',
          title: '{{t("Phone")}}',
          'x-component': 'Input',
          'x-validator': 'phone',
          required: true,
        },
        unique: true,
      },
      {
        key: 'y6huaegts1j',
        name: 'password',
        type: 'password',
        interface: 'password',
        collectionName: 'users',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: '36fci0anqoy',
        uiSchema: {
          'x-uid': '36fci0anqoy',
          name: 'rwed5ao5kzc',
          type: 'string',
          title: '{{t("Password")}}',
          'x-component': 'Password',
        },
        hidden: true,
      },
      {
        key: 'x8c9y839ent',
        name: 'appLang',
        type: 'string',
        interface: null,
        collectionName: 'users',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: null,
        uiSchema: null,
      },
      {
        key: 'mek31aqe6jf',
        name: 'resetToken',
        type: 'string',
        interface: null,
        collectionName: 'users',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: null,
        uiSchema: null,
        unique: true,
        hidden: true,
      },
      {
        key: 'yooeszi4j49',
        name: 'sort',
        type: 'sort',
        interface: null,
        collectionName: 'users',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: null,
        uiSchema: null,
        hidden: true,
      },
      {
        key: 'h6zo6pahshc',
        name: 'createdById',
        type: 'context',
        interface: null,
        collectionName: 'users',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: null,
        uiSchema: null,
        dataType: 'bigInt',
        dataIndex: 'state.currentUser.id',
        createOnly: true,
        visible: true,
        index: true,
      },
      {
        key: '6brzede04ds',
        name: 'createdBy',
        type: 'belongsTo',
        interface: null,
        collectionName: 'users',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: null,
        uiSchema: null,
        target: 'users',
        foreignKey: 'createdById',
        targetKey: 'id',
      },
      {
        key: '3sma9ld4hd8',
        name: 'updatedById',
        type: 'context',
        interface: null,
        collectionName: 'users',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: null,
        uiSchema: null,
        dataType: 'bigInt',
        dataIndex: 'state.currentUser.id',
        visible: true,
        index: true,
      },
      {
        key: '8pc2cniqffk',
        name: 'updatedBy',
        type: 'belongsTo',
        interface: null,
        collectionName: 'users',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: null,
        uiSchema: null,
        target: 'users',
        foreignKey: 'updatedById',
        targetKey: 'id',
      },
      {
        key: 't3n5e5i5aqi',
        name: 'roles',
        type: 'belongsToMany',
        interface: 'm2m',
        collectionName: 'users',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: 'ekht84unce9',
        uiSchema: {
          'x-uid': 'ekht84unce9',
          name: 'i986b4uga1e',
          type: 'array',
          title: '{{t("Roles")}}',
          'x-component': 'RecordPicker',
          'x-component-props': { multiple: true, fieldNames: { label: 'title', value: 'name' } },
        },
        target: 'roles',
        foreignKey: 'userId',
        otherKey: 'roleName',
        onDelete: 'CASCADE',
        sourceKey: 'id',
        targetKey: 'name',
        through: 'rolesUsers',
      },
      {
        key: 'zldz2kzmjp8',
        name: 'jobs',
        type: 'belongsToMany',
        interface: null,
        collectionName: 'users',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: null,
        uiSchema: null,
        through: 'users_jobs',
        onDelete: 'CASCADE',
        foreignKey: 'userId',
        sourceKey: 'id',
        otherKey: 'jobId',
        targetKey: 'id',
      },
      {
        key: '1zf47w8favz',
        name: 'usersJobs',
        type: 'hasMany',
        interface: null,
        collectionName: 'users',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: null,
        uiSchema: null,
        target: 'users_jobs',
        foreignKey: 'userId',
        sourceKey: 'id',
        targetKey: 'id',
      },
    ],
    sortable: 'sort',
    model: 'UserModel',
    createdBy: true,
    updatedBy: true,
    logging: true,
  },
  {
    key: '81m8z9fwjqw',
    name: 'roles',
    title: '{{t("Roles")}}',
    inherit: false,
    hidden: false,
    fields: [
      {
        key: 'zsyd6b234ho',
        name: 'name',
        type: 'uid',
        interface: 'input',
        collectionName: 'roles',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: 'a4xmigogr8v',
        uiSchema: {
          'x-uid': 'a4xmigogr8v',
          name: '49bqhzimaee',
          type: 'string',
          title: '{{t("Role UID")}}',
          'x-component': 'Input',
        },
        prefix: 'r_',
        primaryKey: true,
      },
      {
        key: 'd26zd61agjq',
        name: 'title',
        type: 'string',
        interface: 'input',
        collectionName: 'roles',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: 'g87dg1j1nff',
        uiSchema: {
          'x-uid': 'g87dg1j1nff',
          name: '174qwalj80s',
          type: 'string',
          title: '{{t("Role name")}}',
          'x-component': 'Input',
        },
        unique: true,
      },
      {
        key: '8bd7nwramh3',
        name: 'description',
        type: 'string',
        interface: null,
        collectionName: 'roles',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: null,
        uiSchema: null,
      },
      {
        key: 'ibydvi4z870',
        name: 'strategy',
        type: 'json',
        interface: null,
        collectionName: 'roles',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: null,
        uiSchema: null,
      },
      {
        key: 'exjl8o6atmq',
        name: 'default',
        type: 'boolean',
        interface: null,
        collectionName: 'roles',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: null,
        uiSchema: null,
        defaultValue: false,
      },
      {
        key: '32vzsducp57',
        name: 'hidden',
        type: 'boolean',
        interface: null,
        collectionName: 'roles',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: null,
        uiSchema: null,
        defaultValue: false,
      },
      {
        key: 's2qmtuevjny',
        name: 'allowConfigure',
        type: 'boolean',
        interface: null,
        collectionName: 'roles',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: null,
        uiSchema: null,
      },
      {
        key: 'v3ibbib6385',
        name: 'allowNewMenu',
        type: 'boolean',
        interface: null,
        collectionName: 'roles',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: null,
        uiSchema: null,
      },
      {
        key: 'jvaokn1tbx7',
        name: 'menuUiSchemas',
        type: 'belongsToMany',
        interface: null,
        collectionName: 'roles',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: null,
        uiSchema: null,
        target: 'uiSchemas',
        targetKey: 'x-uid',
        onDelete: 'CASCADE',
        foreignKey: 'roleName',
        sourceKey: 'name',
        otherKey: 'uiSchemaXUid',
        through: 'rolesUischemas',
      },
      {
        key: '615ce3dh5o8',
        name: 'resources',
        type: 'hasMany',
        interface: null,
        collectionName: 'roles',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: null,
        uiSchema: null,
        target: 'rolesResources',
        sourceKey: 'name',
        targetKey: 'name',
        foreignKey: 'roleName',
      },
      {
        key: 'iqzei2hramd',
        name: 'snippets',
        type: 'set',
        interface: null,
        collectionName: 'roles',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: null,
        uiSchema: null,
      },
      {
        key: 'uy9oyd5t4j7',
        name: 'sort',
        type: 'sort',
        interface: null,
        collectionName: 'roles',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: null,
        uiSchema: null,
        hidden: true,
      },
    ],
    autoGenId: false,
    model: 'RoleModel',
    filterTargetKey: 'name',
    sortable: true,
  },
  {
    key: 'wsakr0ngbgo',
    name: 't_3ljrbttnj3r',
    title: 'A',
    inherit: false,
    hidden: false,
    fields: [
      {
        key: 'gnuur5hxc2p',
        name: 'id',
        type: 'bigInt',
        interface: 'id',
        collectionName: 't_3ljrbttnj3r',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: 'xanl30gtu74',
        uiSchema: {
          'x-uid': 'xanl30gtu74',
          name: 'ohdnbxcrjmy',
          type: 'number',
          title: '{{t("ID")}}',
          'x-component': 'InputNumber',
          'x-read-pretty': true,
        },
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
      },
      {
        key: 'gehxbch3me0',
        name: 'f_wekzfdysa8b',
        type: 'bigInt',
        interface: 'integer',
        collectionName: 't_3ljrbttnj3r',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: 'q39vbpp1g5b',
        uiSchema: {
          'x-uid': 'q39vbpp1g5b',
          name: '39db1p24pf3',
          type: 'number',
          title: 'f_wekzfdysa8b',
          'x-component': 'InputNumber',
          'x-read-pretty': true,
        },
        isForeignKey: true,
      },
      {
        key: 'owy55g63zyf',
        name: 'createdAt',
        type: 'date',
        interface: 'createdAt',
        collectionName: 't_3ljrbttnj3r',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: 'xj5b2thmmuv',
        uiSchema: {
          'x-uid': 'xj5b2thmmuv',
          name: '32rc66qt18u',
          type: 'datetime',
          title: '{{t("Created at")}}',
          'x-component': 'DatePicker',
          'x-component-props': {},
          'x-read-pretty': true,
        },
        field: 'createdAt',
      },
      {
        key: '77tp89nucg7',
        name: 'createdBy',
        type: 'belongsTo',
        interface: 'createdBy',
        collectionName: 't_3ljrbttnj3r',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: '5mwvnqmvkwi',
        uiSchema: {
          'x-uid': '5mwvnqmvkwi',
          name: 'dbacbw7r3sa',
          type: 'object',
          title: '{{t("Created by")}}',
          'x-component': 'RecordPicker',
          'x-component-props': { fieldNames: { value: 'id', label: 'nickname' } },
          'x-read-pretty': true,
        },
        target: 'users',
        foreignKey: 'createdById',
        targetKey: 'id',
      },
      {
        key: '0ig27tqa4vm',
        name: 'updatedAt',
        type: 'date',
        interface: 'updatedAt',
        collectionName: 't_3ljrbttnj3r',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: 'u1u9caciqu2',
        uiSchema: {
          'x-uid': 'u1u9caciqu2',
          name: '9i1h44gjfo5',
          type: 'string',
          title: '{{t("Last updated at")}}',
          'x-component': 'DatePicker',
          'x-component-props': {},
          'x-read-pretty': true,
        },
        field: 'updatedAt',
      },
      {
        key: 'l36pg7lgkj5',
        name: 'updatedBy',
        type: 'belongsTo',
        interface: 'updatedBy',
        collectionName: 't_3ljrbttnj3r',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: 'nwa0v7eqjgl',
        uiSchema: {
          'x-uid': 'nwa0v7eqjgl',
          name: 'kghlflwoqql',
          type: 'object',
          title: '{{t("Last updated by")}}',
          'x-component': 'RecordPicker',
          'x-component-props': { fieldNames: { value: 'id', label: 'nickname' } },
          'x-read-pretty': true,
        },
        target: 'users',
        foreignKey: 'updatedById',
        targetKey: 'id',
      },
      {
        key: 'mr5g5qro53b',
        name: 'f_h0fs07wamiv',
        type: 'string',
        interface: 'input',
        collectionName: 't_3ljrbttnj3r',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: 'ygrpxmnk6gx',
        uiSchema: {
          'x-uid': 'ygrpxmnk6gx',
          name: '4teu1kv5itv',
          type: 'string',
          'x-component': 'Input',
          title: 'F1',
        },
      },
      {
        key: '9nnmpj93os9',
        name: 'f_9h89dzktg77',
        type: 'text',
        interface: 'textarea',
        collectionName: 't_3ljrbttnj3r',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: 'qddms7ozrq1',
        uiSchema: {
          'x-uid': 'qddms7ozrq1',
          name: '0nlrgt2vg4z',
          type: 'string',
          'x-component': 'Input.TextArea',
          title: 'F2',
        },
      },
      {
        key: 's7qn6dyrzp8',
        name: 'f_s3c68j59cpx',
        type: 'hasMany',
        interface: 'o2m',
        collectionName: 't_3ljrbttnj3r',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: 'gyuo8qq874s',
        uiSchema: {
          'x-uid': 'gyuo8qq874s',
          name: '4x6yyp8ltwv',
          'x-component': 'RecordPicker',
          'x-component-props': { multiple: true, fieldNames: { label: 'id', value: 'id' } },
          title: 'B',
        },
        foreignKey: 'f_alnc2eyvxsh',
        onDelete: 'SET NULL',
        target: 't_u6nuabfj92v',
        targetKey: 'id',
        sourceKey: 'id',
      },
    ],
    logging: true,
    autoGenId: true,
    createdBy: true,
    updatedBy: true,
    createdAt: true,
    updatedAt: true,
    sortable: true,
    template: 'general',
  },
  {
    key: 'jlxmbzo0czi',
    name: 't_u6nuabfj92v',
    title: 'B',
    inherit: false,
    hidden: false,
    fields: [
      {
        key: 'uu1c0fh5ld0',
        name: 'id',
        type: 'bigInt',
        interface: 'id',
        collectionName: 't_u6nuabfj92v',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: 'wo755e4ys2i',
        uiSchema: {
          'x-uid': 'wo755e4ys2i',
          name: 'erb7uyn9c90',
          type: 'number',
          title: '{{t("ID")}}',
          'x-component': 'InputNumber',
          'x-read-pretty': true,
        },
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
      },
      {
        key: '7tgsh8y6hax',
        name: 'f_alnc2eyvxsh',
        type: 'bigInt',
        interface: 'integer',
        collectionName: 't_u6nuabfj92v',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: '5etryw6z7p1',
        uiSchema: {
          'x-uid': '5etryw6z7p1',
          name: 'a7sude2hxdd',
          type: 'number',
          title: 'f_alnc2eyvxsh',
          'x-component': 'InputNumber',
          'x-read-pretty': true,
        },
        isForeignKey: true,
      },
      {
        key: 'v786su0c5ks',
        name: 'createdAt',
        type: 'date',
        interface: 'createdAt',
        collectionName: 't_u6nuabfj92v',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: '6ghk9jju627',
        uiSchema: {
          'x-uid': '6ghk9jju627',
          name: 'awic1at1p2k',
          type: 'datetime',
          title: '{{t("Created at")}}',
          'x-component': 'DatePicker',
          'x-component-props': {},
          'x-read-pretty': true,
        },
        field: 'createdAt',
      },
      {
        key: 'uxnnl48t04u',
        name: 'createdBy',
        type: 'belongsTo',
        interface: 'createdBy',
        collectionName: 't_u6nuabfj92v',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: 't3b270e7aqr',
        uiSchema: {
          'x-uid': 't3b270e7aqr',
          name: 'fsvjgsm0lzl',
          type: 'object',
          title: '{{t("Created by")}}',
          'x-component': 'RecordPicker',
          'x-component-props': { fieldNames: { value: 'id', label: 'nickname' } },
          'x-read-pretty': true,
        },
        target: 'users',
        foreignKey: 'createdById',
        targetKey: 'id',
      },
      {
        key: 'dvseekuoijq',
        name: 'updatedAt',
        type: 'date',
        interface: 'updatedAt',
        collectionName: 't_u6nuabfj92v',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: 'lzcsr7ih9mw',
        uiSchema: {
          'x-uid': 'lzcsr7ih9mw',
          name: 'gfkobpfv1c8',
          type: 'string',
          title: '{{t("Last updated at")}}',
          'x-component': 'DatePicker',
          'x-component-props': {},
          'x-read-pretty': true,
        },
        field: 'updatedAt',
      },
      {
        key: 'dqqrldo5qc7',
        name: 'updatedBy',
        type: 'belongsTo',
        interface: 'updatedBy',
        collectionName: 't_u6nuabfj92v',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: 'ex081ln9ng5',
        uiSchema: {
          'x-uid': 'ex081ln9ng5',
          name: '6zrk0u24qp9',
          type: 'object',
          title: '{{t("Last updated by")}}',
          'x-component': 'RecordPicker',
          'x-component-props': { fieldNames: { value: 'id', label: 'nickname' } },
          'x-read-pretty': true,
        },
        target: 'users',
        foreignKey: 'updatedById',
        targetKey: 'id',
      },
      {
        key: 'pte8n7wni25',
        name: 'f_scfxiy0r2oh',
        type: 'string',
        interface: 'input',
        collectionName: 't_u6nuabfj92v',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: 'qn621av27ug',
        uiSchema: {
          'x-uid': 'qn621av27ug',
          name: 'gvrtmug183z',
          type: 'string',
          'x-component': 'Input',
          title: 'F1',
        },
      },
      {
        key: 'z3k3ys20td8',
        name: 'f_z7d2oyefw7o',
        type: 'string',
        interface: 'input',
        collectionName: 't_u6nuabfj92v',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: 'oct4qmecbhk',
        uiSchema: {
          'x-uid': 'oct4qmecbhk',
          name: 'wzija27th4z',
          type: 'string',
          'x-component': 'Input',
          title: 'F2',
        },
      },
    ],
    logging: true,
    autoGenId: true,
    createdBy: true,
    updatedBy: true,
    createdAt: true,
    updatedAt: true,
    sortable: true,
    template: 'general',
  },
  {
    key: '320wb7ieepn',
    name: 't_5eg6u82bbnw',
    title: 'C',
    inherit: false,
    hidden: false,
    fields: [
      {
        key: '1rheavbio9y',
        name: 'id',
        type: 'bigInt',
        interface: 'id',
        collectionName: 't_5eg6u82bbnw',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: '3c9sht17apl',
        uiSchema: {
          'x-uid': '3c9sht17apl',
          name: 'qy2ai8k4ucv',
          type: 'number',
          title: '{{t("ID")}}',
          'x-component': 'InputNumber',
          'x-read-pretty': true,
        },
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
      },
      {
        key: '2yfiplf01y0',
        name: 'createdAt',
        type: 'date',
        interface: 'createdAt',
        collectionName: 't_5eg6u82bbnw',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: '8s55p7uvue9',
        uiSchema: {
          'x-uid': '8s55p7uvue9',
          name: '760nblctscd',
          type: 'datetime',
          title: '{{t("Created at")}}',
          'x-component': 'DatePicker',
          'x-component-props': {},
          'x-read-pretty': true,
        },
        field: 'createdAt',
      },
      {
        key: 'n4g9nc6j29o',
        name: 'createdBy',
        type: 'belongsTo',
        interface: 'createdBy',
        collectionName: 't_5eg6u82bbnw',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: 'uxhw7x39oee',
        uiSchema: {
          'x-uid': 'uxhw7x39oee',
          name: 'z8woq4i0xkq',
          type: 'object',
          title: '{{t("Created by")}}',
          'x-component': 'RecordPicker',
          'x-component-props': { fieldNames: { value: 'id', label: 'nickname' } },
          'x-read-pretty': true,
        },
        target: 'users',
        foreignKey: 'createdById',
        targetKey: 'id',
      },
      {
        key: '2z7ua9nkwao',
        name: 'updatedAt',
        type: 'date',
        interface: 'updatedAt',
        collectionName: 't_5eg6u82bbnw',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: 'lr6aqanmiu0',
        uiSchema: {
          'x-uid': 'lr6aqanmiu0',
          name: 'kqtkwb1pw4u',
          type: 'string',
          title: '{{t("Last updated at")}}',
          'x-component': 'DatePicker',
          'x-component-props': {},
          'x-read-pretty': true,
        },
        field: 'updatedAt',
      },
      {
        key: 'mzxannhqgqj',
        name: 'updatedBy',
        type: 'belongsTo',
        interface: 'updatedBy',
        collectionName: 't_5eg6u82bbnw',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: 'p9r7bc9fugf',
        uiSchema: {
          'x-uid': 'p9r7bc9fugf',
          name: 'b0wqhyt9wx9',
          type: 'object',
          title: '{{t("Last updated by")}}',
          'x-component': 'RecordPicker',
          'x-component-props': { fieldNames: { value: 'id', label: 'nickname' } },
          'x-read-pretty': true,
        },
        target: 'users',
        foreignKey: 'updatedById',
        targetKey: 'id',
      },
      {
        key: '1bxbs2q42um',
        name: 'F1',
        type: 'string',
        interface: 'input',
        collectionName: 't_5eg6u82bbnw',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: 'ptwridyoolc',
        uiSchema: {
          'x-uid': 'ptwridyoolc',
          name: '5otgw5weaf3',
          type: 'string',
          'x-component': 'Input',
          title: 'F1',
        },
      },
      {
        key: '0oqkv94uv3p',
        name: 'F2',
        type: 'text',
        interface: 'textarea',
        collectionName: 't_5eg6u82bbnw',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: 'blp5kymcfbw',
        uiSchema: {
          'x-uid': 'blp5kymcfbw',
          name: 'fmcb2aulvqh',
          type: 'string',
          'x-component': 'Input.TextArea',
          title: 'F2',
        },
      },
    ],
    logging: true,
    autoGenId: true,
    createdBy: true,
    updatedBy: true,
    createdAt: true,
    updatedAt: true,
    sortable: true,
    template: 'general',
  },
  {
    key: 'kbo5njtupo7',
    name: 't_zf5tj2ctfxj',
    title: 'C1',
    inherit: false,
    hidden: false,
    fields: [
      {
        key: 'c39dhmibvlz',
        name: 'id',
        type: 'bigInt',
        interface: 'id',
        collectionName: 't_zf5tj2ctfxj',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: 'rhvywkuswja',
        uiSchema: {
          'x-uid': 'rhvywkuswja',
          name: 'oba41c4z414',
          type: 'number',
          title: '{{t("ID")}}',
          'x-component': 'InputNumber',
          'x-read-pretty': true,
        },
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
      },
      {
        key: 'b5qtockp38u',
        name: 'createdAt',
        type: 'date',
        interface: 'createdAt',
        collectionName: 't_zf5tj2ctfxj',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: 'dlch7by3cpc',
        uiSchema: {
          'x-uid': 'dlch7by3cpc',
          name: 'lfyidilnnzl',
          type: 'datetime',
          title: '{{t("Created at")}}',
          'x-component': 'DatePicker',
          'x-component-props': {},
          'x-read-pretty': true,
        },
        field: 'createdAt',
      },
      {
        key: 'wmyojhhgyp1',
        name: 'createdBy',
        type: 'belongsTo',
        interface: 'createdBy',
        collectionName: 't_zf5tj2ctfxj',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: 'ol6vw9ks4tt',
        uiSchema: {
          'x-uid': 'ol6vw9ks4tt',
          name: 'swhjvgqm25k',
          type: 'object',
          title: '{{t("Created by")}}',
          'x-component': 'RecordPicker',
          'x-component-props': { fieldNames: { value: 'id', label: 'nickname' } },
          'x-read-pretty': true,
        },
        target: 'users',
        foreignKey: 'createdById',
        targetKey: 'id',
      },
      {
        key: 'x6ig9kvho93',
        name: 'updatedAt',
        type: 'date',
        interface: 'updatedAt',
        collectionName: 't_zf5tj2ctfxj',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: 'xsaigncxaml',
        uiSchema: {
          'x-uid': 'xsaigncxaml',
          name: 'jkzzdsi0bgc',
          type: 'string',
          title: '{{t("Last updated at")}}',
          'x-component': 'DatePicker',
          'x-component-props': {},
          'x-read-pretty': true,
        },
        field: 'updatedAt',
      },
      {
        key: 't7x0o3fbi6t',
        name: 'updatedBy',
        type: 'belongsTo',
        interface: 'updatedBy',
        collectionName: 't_zf5tj2ctfxj',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: 'dlswd23v7hm',
        uiSchema: {
          'x-uid': 'dlswd23v7hm',
          name: 'grwpgulhhvc',
          type: 'object',
          title: '{{t("Last updated by")}}',
          'x-component': 'RecordPicker',
          'x-component-props': { fieldNames: { value: 'id', label: 'nickname' } },
          'x-read-pretty': true,
        },
        target: 'users',
        foreignKey: 'updatedById',
        targetKey: 'id',
      },
    ],
    logging: true,
    autoGenId: true,
    createdBy: true,
    updatedBy: true,
    createdAt: true,
    updatedAt: true,
    sortable: true,
    template: 'general',
    inherits: ['t_5eg6u82bbnw'],
  },
  {
    key: '55a8kd7drzk',
    name: 't_7okpddajfxm',
    title: 'C11',
    inherit: false,
    hidden: false,
    fields: [
      {
        key: 'zlas4ihpr7y',
        name: 'id',
        type: 'bigInt',
        interface: 'id',
        collectionName: 't_7okpddajfxm',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: '2rnl5wkgpao',
        uiSchema: {
          'x-uid': '2rnl5wkgpao',
          name: 'sg0djj3rvgz',
          type: 'number',
          title: '{{t("ID")}}',
          'x-component': 'InputNumber',
          'x-read-pretty': true,
        },
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
      },
      {
        key: 'bqqfeg2k1os',
        name: 'createdAt',
        type: 'date',
        interface: 'createdAt',
        collectionName: 't_7okpddajfxm',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: '8wwtzp2mmgy',
        uiSchema: {
          'x-uid': '8wwtzp2mmgy',
          name: 'ofmom3n1yuf',
          type: 'datetime',
          title: '{{t("Created at")}}',
          'x-component': 'DatePicker',
          'x-component-props': {},
          'x-read-pretty': true,
        },
        field: 'createdAt',
      },
      {
        key: '9w2eth0okcc',
        name: 'createdBy',
        type: 'belongsTo',
        interface: 'createdBy',
        collectionName: 't_7okpddajfxm',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: 'bya9n5vrqlu',
        uiSchema: {
          'x-uid': 'bya9n5vrqlu',
          name: 'n0wusiai3aw',
          type: 'object',
          title: '{{t("Created by")}}',
          'x-component': 'RecordPicker',
          'x-component-props': { fieldNames: { value: 'id', label: 'nickname' } },
          'x-read-pretty': true,
        },
        target: 'users',
        foreignKey: 'createdById',
        targetKey: 'id',
      },
      {
        key: 'n4iunq7398c',
        name: 'updatedAt',
        type: 'date',
        interface: 'updatedAt',
        collectionName: 't_7okpddajfxm',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: 'p14m8jb9476',
        uiSchema: {
          'x-uid': 'p14m8jb9476',
          name: 'ngy94y78rhw',
          type: 'string',
          title: '{{t("Last updated at")}}',
          'x-component': 'DatePicker',
          'x-component-props': {},
          'x-read-pretty': true,
        },
        field: 'updatedAt',
      },
      {
        key: 'sc1datypf62',
        name: 'updatedBy',
        type: 'belongsTo',
        interface: 'updatedBy',
        collectionName: 't_7okpddajfxm',
        parentKey: null,
        reverseKey: null,
        uiSchemaUid: '2qyvd78ewua',
        uiSchema: {
          'x-uid': '2qyvd78ewua',
          name: 'zjn5om3v5p3',
          type: 'object',
          title: '{{t("Last updated by")}}',
          'x-component': 'RecordPicker',
          'x-component-props': { fieldNames: { value: 'id', label: 'nickname' } },
          'x-read-pretty': true,
        },
        target: 'users',
        foreignKey: 'updatedById',
        targetKey: 'id',
      },
    ],
    logging: true,
    autoGenId: true,
    createdBy: true,
    updatedBy: true,
    createdAt: true,
    updatedAt: true,
    sortable: true,
    template: 'general',
    inherits: ['t_zf5tj2ctfxj'],
  },
];
