import { randomBytes } from 'node:crypto';

import { generateSecretKey } from '@nocobase/secrets';

export function generateAuthSecret(): string {
  return randomBytes(32).toString('base64url');
}

export { generateSecretKey };

export interface BuildConfigFileOptions {
  /**
   * Contents of the application's `config.example.yml`, used as the base so its comments and commented-out sections
   * reach the user.
   */
  readonly example?: string;
  /** What an older example's live `auth.secret` and `session.secret` are filled with. */
  readonly secret?: string;
  /** The first secrets key, version 1. Generated when not given. */
  readonly secretsKey?: string;
}

/**
 * Builds the `config.yml` an application starts with.
 *
 * The application's own `config.example.yml` is the base rather than a file assembled here. It is the one place that
 * documents what an application can be configured with — the notification channels, the LLM services, the additional
 * database connections — and every line of it is written for someone about to edit it. A file generated from scratch
 * carried a fraction of that and went stale the moment the example grew.
 *
 * Only the secrets are filled in, because they are the one thing the example cannot ship: `secrets.keys` has no safe
 * default, and the example's placeholder is rejected at startup precisely so that a copy made by hand cannot run on a
 * key published in this repository. Everything else the example already answers, including the database, which the
 * caller configures for the selected dialect before filling secrets. An older example that still carries live
 * `auth.secret` and `session.secret` keys has those filled too, so it does not start on the placeholder.
 */
export function buildConfigFile(options: BuildConfigFileOptions = {}): string {
  const base =
    options.example === undefined ? FALLBACK_CONFIG : retitle(options.example);

  let result = setSecretsKey(base, options.secretsKey ?? generateSecretKey());
  const secret = options.secret ?? generateAuthSecret();
  for (const section of ['auth', 'session']) {
    result = replaceLiveSectionSecret(result, section, secret);
  }

  return `${result.trimEnd()}\n`;
}

/**
 * Writes the first secrets key into the `secrets` section, live or commented out, replacing the example's `key:`
 * line so its comments stay attached, or adds the section when the example has none.
 */
function setSecretsKey(contents: string, key: string): string {
  const block = [
    'secrets:',
    `${DEFAULT_INDENT}keys:`,
    `${DEFAULT_INDENT}${DEFAULT_INDENT}- version: 1`,
    `${DEFAULT_INDENT}${DEFAULT_INDENT}  key: ${yamlString(key)}`,
  ];
  let lines = contents.split(/\r?\n/u);
  let header = lines.findIndex((line) => /^secrets\s*:/u.test(line));
  if (header === -1) {
    header = lines.findIndex((line) => /^#\s*secrets\s*:/u.test(line));
    if (header !== -1) lines = uncommentBlock(lines, header);
  }
  if (header === -1) {
    return [contents.trimEnd(), '', ...block, ''].join('\n');
  }
  const end = sectionEnd(lines, header);
  for (let index = header + 1; index < end; index += 1) {
    const match = /^(\s+(?:-\s+)?)(?:#\s*)?key\s*:/u.exec(lines[index]);
    if (match) {
      lines[index] = `${match[1]}key: ${yamlString(key)}`;
      return lines.join('\n');
    }
  }
  lines.splice(header, end - header, ...block);
  return lines.join('\n');
}

/** Fills a live `secret:` key of a live top-level section, leaving every other shape alone. */
function replaceLiveSectionSecret(
  contents: string,
  section: string,
  secret: string,
): string {
  const lines = contents.split(/\r?\n/u);
  const header = lines.findIndex((line) =>
    new RegExp(`^${section}\\s*:`, 'u').test(line),
  );
  if (header === -1) return contents;
  const end = sectionEnd(lines, header);
  for (let index = header + 1; index < end; index += 1) {
    const match = /^(\s+)secret\s*:/u.exec(lines[index]);
    if (match) {
      lines[index] = `${match[1]}secret: ${yamlString(secret)}`;
      return lines.join('\n');
    }
  }
  return contents;
}

const GENERATED_HEADER = '# Generated by nocobase config init.';

/**
 * Replaces the example's opening instruction, which stops being true the moment the file is the `config.yml` it was
 * telling the reader to make. A leading comment that says nothing of the sort is left alone and the header goes above
 * it, since an example is not required to open with an instruction at all.
 */
function retitle(example: string): string {
  const lines = example.split(/\r?\n/u);
  const opening = lines[0] ?? '';

  return /^#.*\bcopy\b.*\bconfig\.yml\b/iu.test(opening)
    ? [GENERATED_HEADER, ...lines.slice(1)].join('\n')
    : [GENERATED_HEADER, ...lines].join('\n');
}

/**
 * Written when the application ships no `config.example.yml`, so the result always has the secrets it cannot start
 * without. Everything else falls back to the defaults in the application's own `server/config/`.
 */
const FALLBACK_CONFIG = `${GENERATED_HEADER}\n`;

/** Indentation for a key inserted into a section that has none to copy. */
const DEFAULT_INDENT = '  ';

/**
 * Uncomments a commented-out block: its header and every commented line under it, up to the first line that is not.
 *
 * One `#` and at most one space after it are removed, which turns `#   secret: x` into `   secret: x` and leaves a
 * nested `#   # Use the same value` as the comment `  # Use the same value` it was written as.
 */
function uncommentBlock(lines: readonly string[], header: number): string[] {
  const result = [...lines];

  for (let index = header; index < result.length; index += 1) {
    const line = result[index];

    if (!line.startsWith('#')) {
      break;
    }

    result[index] = line.replace(/^#[^\S\n]?/u, '');
  }

  return result;
}

/**
 * The line after the last one belonging to the section. A top-level key or a top-level comment starts at column zero,
 * so anything indented or blank is still inside.
 */
function sectionEnd(lines: readonly string[], header: number): number {
  for (let index = header + 1; index < lines.length; index += 1) {
    const line = lines[index];

    if (line.trim() !== '' && !/^\s/u.test(line)) {
      return index;
    }
  }

  return lines.length;
}

function yamlString(value: string): string {
  return JSON.stringify(value);
}
