/**
 * This file is part of the NocoBase (R) project.
 * Copyright (c) 2020-2024 NocoBase Co., Ltd.
 * Authors: NocoBase Team.
 *
 * This project is dual-licensed under AGPL-3.0 and NocoBase Commercial License.
 * For more information, please refer to: https://www.nocobase.com/agreement.
 */

import { Command, Flags } from '@oclif/core';
import { removeEnv } from '../../lib/auth-store.js';
import {
  formatMissingManagedAppEnvMessage,
  managedAppLifecycleEnvVars,
  resolveManagedAppRuntime,
  runLocalNocoBaseCommand,
  type ManagedAppRuntime,
} from '../../lib/app-runtime.js';
import { hasExplicitEnvSelection } from '../../lib/env-guard.js';
import { resolveEnvProxyEntryDir, resolveLegacyNginxEnvProxyAppOutputPath } from '../../lib/env-proxy.ts';
import { resolveConfiguredStoragePath } from '../../lib/env-paths.js';
import { input } from '../../lib/inquirer.ts';
import { announceTargetEnv, failTask, isInteractiveTerminal, printInfo, startTask, succeedTask } from '../../lib/ui.js';
import path from 'node:path';
import {
  builtinDbContainerName,
  managedDockerNetworkName,
  removeDockerContainerIfExists,
  removeDockerNetworkIfUnused,
  removePathIfExists,
  resolveManagedLocalAppPath,
  shouldRemoveManagedLocalAppFiles,
} from './shared.js';

function formatDestroyFailure(envName: string, message: string): string {
  return [
    `Couldn't destroy env "${envName}".`,
    'Some managed local resources may still exist. Check Docker, local app files, and storage data, then try again.',
    `Details: ${message}`,
  ].join('\n');
}

function formatDestroyForceRequiredMessage(envName: string, explicitEnv: boolean): string {
  if (!explicitEnv) {
    return [
      `Refusing to destroy current env "${envName}" without explicit selection in non-interactive mode.`,
      `Re-run with \`--env ${envName} --force\` to destroy this env.`,
    ].join('\n');
  }

  return [
    `Refusing to destroy env "${envName}" without confirmation in non-interactive mode.`,
    `Re-run with \`--env ${envName} --force\` to destroy this env.`,
  ].join('\n');
}

function buildDestroyPrompt(
  runtime: ManagedAppRuntime,
  options: { explicitEnv: boolean; removesManagedLocalAppFiles: boolean; removesStorageData: boolean },
): string {
  const subject = options.explicitEnv ? `env "${runtime.envName}"` : `current env "${runtime.envName}"`;
  const lines = [`Destroy ${subject}?`];

  if (runtime.kind === 'http' || runtime.kind === 'ssh') {
    lines.push('This env has no CLI-managed local app or database runtime on this machine.');
    lines.push('Only the saved CLI env config will be removed. External services are not touched.');
  } else {
    lines.push('This removes managed app runtime resources.');
    if (runtime.env.config.builtinDb) {
      lines.push('CLI-managed built-in database runtime will also be removed.');
    } else {
      lines.push('External database resources are not managed by the CLI and will be left untouched.');
    }
    if (options.removesManagedLocalAppFiles) {
      lines.push('CLI-managed local app files will also be removed.');
    }
    lines.push('Env-specific proxy entry files generated by `nb proxy` will also be removed when present.');
    if (options.removesStorageData) {
      lines.push('Storage data will be removed.');
    } else {
      lines.push('No saved storage path was found for this env.');
    }
    lines.push('The saved CLI env config will be removed.');
  }

  lines.push(`Type "${runtime.envName}" to confirm:`);
  return lines.join('\n');
}

async function confirmDestroy(
  runtime: ManagedAppRuntime,
  options: {
    explicitEnv: boolean;
    force: boolean;
    removesManagedLocalAppFiles: boolean;
    removesStorageData: boolean;
  },
): Promise<boolean> {
  if (!isInteractiveTerminal()) {
    if (!options.explicitEnv) {
      throw new Error(formatDestroyForceRequiredMessage(runtime.envName, false));
    }
    if (options.force) {
      return true;
    }
    throw new Error(formatDestroyForceRequiredMessage(runtime.envName, options.explicitEnv));
  }

  if (options.force) {
    return true;
  }

  try {
    await input({
      message: buildDestroyPrompt(runtime, options),
      required: true,
      validate: (value) => (value.trim() === runtime.envName ? true : `Type "${runtime.envName}" to confirm.`),
      placeholder: runtime.envName,
    });
    return true;
  } catch {
    return false;
  }
}

export default class AppDestroy extends Command {
  static override hidden = true;
  static override description = 'Deprecated compatibility alias for `nb env remove <name> --purge`.';

  static override examples = [
    '<%= config.bin %> <%= command.id %> --env app1',
    '<%= config.bin %> <%= command.id %> --env app1 --force',
  ];

  static override flags = {
    env: Flags.string({
      char: 'e',
      description: 'CLI env name to destroy. Defaults to the current env when omitted in interactive mode',
    }),
    force: Flags.boolean({
      char: 'f',
      description: 'Skip confirmation and destroy the selected env immediately',
      default: false,
    }),
    verbose: Flags.boolean({
      description: 'Show raw output from destruction commands',
      default: false,
    }),
  };

  public async run(): Promise<void> {
    const { flags } = await this.parse(AppDestroy);
    const requestedEnv = flags.env?.trim() || undefined;
    const explicitEnv = Boolean(requestedEnv && hasExplicitEnvSelection(this.argv));
    const runtime = await resolveManagedAppRuntime(requestedEnv);

    if (!runtime) {
      this.error(formatMissingManagedAppEnvMessage(requestedEnv));
    }

    const removesManagedLocalAppFiles =
      runtime.kind === 'local' &&
      Boolean(resolveManagedLocalAppPath(runtime)) &&
      shouldRemoveManagedLocalAppFiles(runtime);
    const removesStorageData =
      (runtime.kind === 'local' || runtime.kind === 'docker') &&
      Boolean(resolveConfiguredStoragePath(runtime.env.config));

    let confirmed = false;
    try {
      confirmed = await confirmDestroy(runtime, {
        explicitEnv,
        force: flags.force,
        removesManagedLocalAppFiles,
        removesStorageData,
      });
    } catch (error: unknown) {
      this.error(error instanceof Error ? error.message : String(error));
    }
    if (!confirmed) {
      return;
    }

    announceTargetEnv(runtime.envName);

    try {
      if (runtime.kind === 'docker') {
        startTask(`Removing Docker app container for "${runtime.envName}"...`);
        const state = await removeDockerContainerIfExists(runtime.containerName, {
          stdio: flags.verbose ? 'inherit' : 'ignore',
        });
        succeedTask(
          state === 'removed'
            ? `Docker app container removed for "${runtime.envName}".`
            : `No Docker app container found for "${runtime.envName}".`,
        );
      } else if (runtime.kind === 'local') {
        startTask(`Stopping local NocoBase app for "${runtime.envName}"...`);
        await runLocalNocoBaseCommand(runtime, ['pm2', 'kill'], {
          env: managedAppLifecycleEnvVars(),
          stdio: flags.verbose ? 'inherit' : 'ignore',
        });
        succeedTask(`Local NocoBase app stopped for "${runtime.envName}".`);
      }

      if (runtime.kind === 'local' || runtime.kind === 'docker') {
        const dbContainer = builtinDbContainerName(runtime);
        if (dbContainer) {
          startTask(`Removing built-in database container for "${runtime.envName}"...`);
          const state = await removeDockerContainerIfExists(dbContainer, {
            stdio: flags.verbose ? 'inherit' : 'ignore',
          });
          succeedTask(
            state === 'removed'
              ? `Built-in database container removed for "${runtime.envName}".`
              : `No built-in database container found for "${runtime.envName}".`,
          );
        } else {
          printInfo(`External database resources for "${runtime.envName}" were left untouched.`);
        }

        const networkName = managedDockerNetworkName(runtime);
        if (networkName) {
          startTask(`Removing Docker network for "${runtime.envName}" if unused...`);
          const state = await removeDockerNetworkIfUnused(networkName);
          if (state === 'removed') {
            succeedTask(`Docker network removed for "${runtime.envName}".`);
          } else if (state === 'missing') {
            succeedTask(`No Docker network found for "${runtime.envName}".`);
          } else {
            succeedTask(`Docker network is still in use for "${runtime.envName}". Keeping it.`);
          }
        }

        if (runtime.kind === 'local') {
          const localAppPath = resolveManagedLocalAppPath(runtime);
          if (localAppPath && removesManagedLocalAppFiles) {
            startTask(`Removing managed local app files for "${runtime.envName}"...`);
            await removePathIfExists(localAppPath, `managed app files for "${runtime.envName}"`);
            succeedTask(`Managed local app files removed for "${runtime.envName}".`);
          } else {
            printInfo(`No saved local app path found for "${runtime.envName}".`);
          }
        }

        const proxyEntryDirs = [
          resolveEnvProxyEntryDir(runtime.envName, { provider: 'nginx' }),
          resolveEnvProxyEntryDir(runtime.envName, { provider: 'caddy' }),
          path.dirname(resolveLegacyNginxEnvProxyAppOutputPath(runtime.envName)),
        ];
        startTask(`Removing proxy entry files for "${runtime.envName}"...`);
        for (const proxyEntryDir of proxyEntryDirs) {
          await removePathIfExists(proxyEntryDir, `proxy entry files for "${runtime.envName}"`);
        }
        succeedTask(`Proxy entry files removed for "${runtime.envName}".`);

        const configuredStoragePath = resolveConfiguredStoragePath(runtime.env.config);
        if (configuredStoragePath) {
          startTask(`Removing storage data for "${runtime.envName}"...`);
          await removePathIfExists(configuredStoragePath, `storage data for "${runtime.envName}"`);
          succeedTask(`Storage data removed for "${runtime.envName}".`);
        } else {
          printInfo(`No saved storage path found for "${runtime.envName}".`);
        }
      } else {
        printInfo(`No CLI-managed local app or database runtime exists for "${runtime.envName}" on this machine.`);
      }

      startTask(`Removing saved CLI env config for "${runtime.envName}"...`);
      const result = await removeEnv(runtime.envName);
      succeedTask(
        `Saved CLI env config removed for "${runtime.envName}"${
          result.lastEnv ? ` (last env: ${result.lastEnv})` : ''
        }.`,
      );
    } catch (error: unknown) {
      failTask(`Failed to destroy env "${runtime.envName}".`);
      this.error(formatDestroyFailure(runtime.envName, error instanceof Error ? error.message : String(error)));
    }
  }
}
