gzip on;
gzip_types
    text/plain
    text/css
    text/xml
    text/markdown
    text/javascript
    application/javascript
    application/json
    application/manifest+json
    application/atom+xml
    application/rss+xml
    application/xml
    application/xml+rss
    application/xhtml+xml
    application/wasm
    image/svg+xml;
