map $http_upgrade $connection_upgrade {
    default upgrade;
    ""      close;
}

map $http_x_forwarded_proto $upstream_x_forwarded_proto {
    default $http_x_forwarded_proto;
    ""      $scheme;
}

map $http_host $final_host {
    default $http_host;
    ""      $host;
}
