add_header Cache-Control "public" always;
add_header Content-Security-Policy "sandbox" always;
add_header X-Content-Type-Options "nosniff" always;

access_log off;
autoindex off;

# Force potentially renderable uploaded files to download.
location ~* \.(?:htm|html|pdf|svg|svgz|xht|xhtml|xml|xsl|xslt)$ {
    add_header Cache-Control "public" always;
    add_header Content-Security-Policy "sandbox" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Content-Disposition "attachment" always;
}

# Let Markdown files render as plain Markdown text.
location ~* \.md$ {
    default_type text/markdown;

    add_header Cache-Control "public" always;
    add_header Content-Security-Policy "sandbox" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Content-Disposition "inline" always;
}
