/**
 * This file is part of the NocoBase (R) project.
 * Copyright (c) 2020-2024 NocoBase Co., Ltd.
 * Authors: NocoBase Team.
 *
 * This project is dual-licensed under AGPL-3.0 and NocoBase Commercial License.
 * For more information, please refer to: https://www.nocobase.com/agreement.
 */

import { generalWithDatetime, PageConfig } from '@nocobase/test/e2e';

/**
 * 1. 一个 Form 区块\一个Table
 * 5. 所有字段都是 time 字段
 */
export const oneFormBlockWithTimeField: PageConfig = {
  collections: generalWithDatetime,
  pageSchema: {
    _isJSONSchemaObject: true,
    version: '2.0',
    type: 'void',
    'x-component': 'Page',
    properties: {
      rzvrcrafmff: {
        type: 'void',
        'x-component': 'Grid',
        'x-initializer': 'page:addBlock',
        properties: {
          '0wlhy5dsdr9': {
            _isJSONSchemaObject: true,
            version: '2.0',
            type: 'void',
            'x-component': 'Grid.Row',
            'x-app-version': '1.6.0-beta.15',
            properties: {
              kl24owuexdn: {
                _isJSONSchemaObject: true,
                version: '2.0',
                type: 'void',
                'x-component': 'Grid.Col',
                'x-app-version': '1.6.0-beta.15',
                properties: {
                  ypuok4w11yk: {
                    _isJSONSchemaObject: true,
                    version: '2.0',
                    type: 'void',
                    'x-decorator': 'TableBlockProvider',
                    'x-acl-action': 'general:list',
                    'x-use-decorator-props': 'useTableBlockDecoratorProps',
                    'x-decorator-props': {
                      collection: 'general',
                      dataSource: 'main',
                      action: 'list',
                      params: {
                        pageSize: 20,
                      },
                      rowKey: 'id',
                      showIndex: true,
                      dragSort: false,
                    },
                    'x-toolbar': 'BlockSchemaToolbar',
                    'x-settings': 'blockSettings:table',
                    'x-component': 'CardItem',
                    'x-filter-targets': [],
                    'x-app-version': '1.6.0-beta.15',
                    properties: {
                      actions: {
                        _isJSONSchemaObject: true,
                        version: '2.0',
                        type: 'void',
                        'x-initializer': 'table:configureActions',
                        'x-component': 'ActionBar',
                        'x-component-props': {
                          style: {
                            marginBottom: 'var(--nb-spacing)',
                          },
                        },
                        'x-app-version': '1.6.0-beta.15',
                        properties: {
                          zdza5lek31e: {
                            _isJSONSchemaObject: true,
                            version: '2.0',
                            title: '{{ t("Refresh") }}',
                            'x-action': 'refresh',
                            'x-component': 'Action',
                            'x-use-component-props': 'useRefreshActionProps',
                            'x-toolbar': 'ActionSchemaToolbar',
                            'x-settings': 'actionSettings:refresh',
                            'x-component-props': {
                              icon: 'ReloadOutlined',
                            },
                            'x-align': 'right',
                            type: 'void',
                            'x-app-version': '1.6.0-beta.15',
                            'x-uid': 'b66wvf7bgz5',
                            'x-async': false,
                            'x-index': 1,
                          },
                        },
                        'x-uid': '3s5zor9kcv2',
                        'x-async': false,
                        'x-index': 1,
                      },
                      f82y42a5fj5: {
                        _isJSONSchemaObject: true,
                        version: '2.0',
                        type: 'array',
                        'x-initializer': 'table:configureColumns',
                        'x-component': 'TableV2',
                        'x-use-component-props': 'useTableBlockProps',
                        'x-component-props': {
                          rowKey: 'id',
                          rowSelection: {
                            type: 'checkbox',
                          },
                        },
                        'x-app-version': '1.6.0-beta.15',
                        properties: {
                          actions: {
                            _isJSONSchemaObject: true,
                            version: '2.0',
                            type: 'void',
                            title: '{{ t("Actions") }}',
                            'x-action-column': 'actions',
                            'x-decorator': 'TableV2.Column.ActionBar',
                            'x-component': 'TableV2.Column',
                            'x-toolbar': 'TableColumnSchemaToolbar',
                            'x-initializer': 'table:configureItemActions',
                            'x-settings': 'fieldSettings:TableColumn',
                            'x-toolbar-props': {
                              initializer: 'table:configureItemActions',
                            },
                            'x-app-version': '1.6.0-beta.15',
                            properties: {
                              '5izameu4igy': {
                                _isJSONSchemaObject: true,
                                version: '2.0',
                                type: 'void',
                                'x-decorator': 'DndContext',
                                'x-component': 'Space',
                                'x-component-props': {
                                  split: '|',
                                },
                                'x-app-version': '1.6.0-beta.15',
                                'x-uid': 'nysl3krhacu',
                                'x-async': false,
                                'x-index': 1,
                              },
                            },
                            'x-uid': 'rmf73e9uby5',
                            'x-async': false,
                            'x-index': 1,
                          },
                          ysvcucujup7: {
                            _isJSONSchemaObject: true,
                            version: '2.0',
                            type: 'void',
                            'x-decorator': 'TableV2.Column.Decorator',
                            'x-toolbar': 'TableColumnSchemaToolbar',
                            'x-settings': 'fieldSettings:TableColumn',
                            'x-component': 'TableV2.Column',
                            'x-app-version': '1.6.0-beta.15',
                            properties: {
                              time: {
                                _isJSONSchemaObject: true,
                                version: '2.0',
                                'x-collection-field': 'general.time',
                                'x-component': 'CollectionField',
                                'x-component-props': {},
                                'x-read-pretty': true,
                                'x-decorator': null,
                                'x-decorator-props': {
                                  labelStyle: {
                                    display: 'none',
                                  },
                                },
                                'x-app-version': '1.6.0-beta.15',
                                'x-uid': 'p168mtpnfmt',
                                'x-async': false,
                                'x-index': 1,
                              },
                            },
                            'x-uid': 'l3vanfk00ha',
                            'x-async': false,
                            'x-index': 2,
                          },
                        },
                        'x-uid': 'dkj7c2zq5cz',
                        'x-async': false,
                        'x-index': 2,
                      },
                    },
                    'x-uid': 'm0fxi87rolp',
                    'x-async': false,
                    'x-index': 1,
                  },
                },
                'x-uid': 'ws6yw0yn42w',
                'x-async': false,
                'x-index': 1,
              },
            },
            'x-uid': 'vl9c8frvxdd',
            'x-async': false,
            'x-index': 1,
          },
          '0trnz9rwsi4': {
            _isJSONSchemaObject: true,
            version: '2.0',
            type: 'void',
            'x-component': 'Grid.Row',
            'x-app-version': '1.6.0-beta.15',
            properties: {
              ln6eil4s9be: {
                _isJSONSchemaObject: true,
                version: '2.0',
                type: 'void',
                'x-component': 'Grid.Col',
                'x-app-version': '1.6.0-beta.15',
                properties: {
                  ekyzyofaaxe: {
                    _isJSONSchemaObject: true,
                    version: '2.0',
                    type: 'void',
                    'x-acl-action-props': {
                      skipScopeCheck: true,
                    },
                    'x-acl-action': 'general:create',
                    'x-decorator': 'FormBlockProvider',
                    'x-use-decorator-props': 'useCreateFormBlockDecoratorProps',
                    'x-decorator-props': {
                      dataSource: 'main',
                      collection: 'general',
                    },
                    'x-toolbar': 'BlockSchemaToolbar',
                    'x-settings': 'blockSettings:createForm',
                    'x-component': 'CardItem',
                    'x-app-version': '1.6.0-beta.15',
                    properties: {
                      '3q33gyop9ek': {
                        _isJSONSchemaObject: true,
                        version: '2.0',
                        type: 'void',
                        'x-component': 'FormV2',
                        'x-use-component-props': 'useCreateFormBlockProps',
                        'x-app-version': '1.6.0-beta.15',
                        properties: {
                          grid: {
                            _isJSONSchemaObject: true,
                            version: '2.0',
                            type: 'void',
                            'x-component': 'Grid',
                            'x-initializer': 'form:configureFields',
                            'x-app-version': '1.6.0-beta.15',
                            properties: {
                              npethz0pi6n: {
                                _isJSONSchemaObject: true,
                                version: '2.0',
                                type: 'void',
                                'x-component': 'Grid.Row',
                                'x-app-version': '1.6.0-beta.15',
                                properties: {
                                  hwo4zfvt9s2: {
                                    _isJSONSchemaObject: true,
                                    version: '2.0',
                                    type: 'void',
                                    'x-component': 'Grid.Col',
                                    'x-app-version': '1.6.0-beta.15',
                                    properties: {
                                      time: {
                                        'x-uid': '5n1gx6bun4s',
                                        _isJSONSchemaObject: true,
                                        version: '2.0',
                                        type: 'string',
                                        'x-toolbar': 'FormItemSchemaToolbar',
                                        'x-settings': 'fieldSettings:FormItem',
                                        'x-component': 'CollectionField',
                                        'x-decorator': 'FormItem',
                                        'x-collection-field': 'general.time',
                                        'x-component-props': {
                                          format: 'h:mm a',
                                        },
                                        'x-app-version': '1.6.0-beta.15',
                                        'x-async': false,
                                        'x-index': 1,
                                      },
                                    },
                                    'x-uid': 'sja1qwtgf59',
                                    'x-async': false,
                                    'x-index': 1,
                                  },
                                },
                                'x-uid': 'yjf75lkkznn',
                                'x-async': false,
                                'x-index': 1,
                              },
                            },
                            'x-uid': 'cl1ioo6i3so',
                            'x-async': false,
                            'x-index': 1,
                          },
                          wziiurulfe3: {
                            _isJSONSchemaObject: true,
                            version: '2.0',
                            type: 'void',
                            'x-initializer': 'createForm:configureActions',
                            'x-component': 'ActionBar',
                            'x-component-props': {
                              layout: 'one-column',
                            },
                            'x-app-version': '1.6.0-beta.15',
                            'x-uid': 'df4m26frb8o',
                            'x-async': false,
                            'x-index': 2,
                          },
                        },
                        'x-uid': 'zlraro8gb64',
                        'x-async': false,
                        'x-index': 1,
                      },
                    },
                    'x-uid': 'w1zmvb66sdn',
                    'x-async': false,
                    'x-index': 1,
                  },
                },
                'x-uid': '7vy2vphp2u3',
                'x-async': false,
                'x-index': 1,
              },
            },
            'x-uid': '48wwintt9ru',
            'x-async': false,
            'x-index': 2,
          },
        },
        name: 'e46pcjcbi86',
        'x-uid': 'n4d6da78d5e',
        'x-async': true,
        'x-index': 1,
      },
    },
    'x-uid': 'ml7rypfikcm',
    'x-async': true,
    'x-index': 1,
  },
};

/**
 * 1. 一个 Form 区块\一个Table
 * 5. 所有字段都是 time 字段
 */
export const oneTableBlockWithTimeField: PageConfig = {
  collections: generalWithDatetime,
  pageSchema: {
    _isJSONSchemaObject: true,
    version: '2.0',
    type: 'void',
    'x-component': 'Page',
    properties: {
      rzvrcrafmff: {
        type: 'void',
        'x-component': 'Grid',
        'x-initializer': 'page:addBlock',
        properties: {
          '0wlhy5dsdr9': {
            _isJSONSchemaObject: true,
            version: '2.0',
            type: 'void',
            'x-component': 'Grid.Row',
            'x-app-version': '1.6.0-beta.15',
            properties: {
              kl24owuexdn: {
                _isJSONSchemaObject: true,
                version: '2.0',
                type: 'void',
                'x-component': 'Grid.Col',
                'x-app-version': '1.6.0-beta.15',
                properties: {
                  ypuok4w11yk: {
                    _isJSONSchemaObject: true,
                    version: '2.0',
                    type: 'void',
                    'x-decorator': 'TableBlockProvider',
                    'x-acl-action': 'general:list',
                    'x-use-decorator-props': 'useTableBlockDecoratorProps',
                    'x-decorator-props': {
                      collection: 'general',
                      dataSource: 'main',
                      action: 'list',
                      params: {
                        pageSize: 20,
                      },
                      rowKey: 'id',
                      showIndex: true,
                      dragSort: false,
                    },
                    'x-toolbar': 'BlockSchemaToolbar',
                    'x-settings': 'blockSettings:table',
                    'x-component': 'CardItem',
                    'x-filter-targets': [],
                    'x-app-version': '1.6.0-beta.15',
                    properties: {
                      actions: {
                        _isJSONSchemaObject: true,
                        version: '2.0',
                        type: 'void',
                        'x-initializer': 'table:configureActions',
                        'x-component': 'ActionBar',
                        'x-component-props': {
                          style: {
                            marginBottom: 'var(--nb-spacing)',
                          },
                        },
                        'x-app-version': '1.6.0-beta.15',
                        properties: {
                          zdza5lek31e: {
                            _isJSONSchemaObject: true,
                            version: '2.0',
                            title: '{{ t("Refresh") }}',
                            'x-action': 'refresh',
                            'x-component': 'Action',
                            'x-use-component-props': 'useRefreshActionProps',
                            'x-toolbar': 'ActionSchemaToolbar',
                            'x-settings': 'actionSettings:refresh',
                            'x-component-props': {
                              icon: 'ReloadOutlined',
                            },
                            'x-align': 'right',
                            type: 'void',
                            'x-app-version': '1.6.0-beta.15',
                            'x-uid': 'b66wvf7bgz5',
                            'x-async': false,
                            'x-index': 1,
                          },
                        },
                        'x-uid': '3s5zor9kcv2',
                        'x-async': false,
                        'x-index': 1,
                      },
                      f82y42a5fj5: {
                        _isJSONSchemaObject: true,
                        version: '2.0',
                        type: 'array',
                        'x-initializer': 'table:configureColumns',
                        'x-component': 'TableV2',
                        'x-use-component-props': 'useTableBlockProps',
                        'x-component-props': {
                          rowKey: 'id',
                          rowSelection: {
                            type: 'checkbox',
                          },
                        },
                        'x-app-version': '1.6.0-beta.15',
                        properties: {
                          actions: {
                            _isJSONSchemaObject: true,
                            version: '2.0',
                            type: 'void',
                            title: '{{ t("Actions") }}',
                            'x-action-column': 'actions',
                            'x-decorator': 'TableV2.Column.ActionBar',
                            'x-component': 'TableV2.Column',
                            'x-toolbar': 'TableColumnSchemaToolbar',
                            'x-initializer': 'table:configureItemActions',
                            'x-settings': 'fieldSettings:TableColumn',
                            'x-toolbar-props': {
                              initializer: 'table:configureItemActions',
                            },
                            'x-app-version': '1.6.0-beta.15',
                            properties: {
                              '5izameu4igy': {
                                _isJSONSchemaObject: true,
                                version: '2.0',
                                type: 'void',
                                'x-decorator': 'DndContext',
                                'x-component': 'Space',
                                'x-component-props': {
                                  split: '|',
                                },
                                'x-app-version': '1.6.0-beta.15',
                                'x-uid': 'nysl3krhacu',
                                'x-async': false,
                                'x-index': 1,
                              },
                            },
                            'x-uid': 'rmf73e9uby5',
                            'x-async': false,
                            'x-index': 1,
                          },
                          ysvcucujup7: {
                            _isJSONSchemaObject: true,
                            version: '2.0',
                            type: 'void',
                            'x-decorator': 'TableV2.Column.Decorator',
                            'x-toolbar': 'TableColumnSchemaToolbar',
                            'x-settings': 'fieldSettings:TableColumn',
                            'x-component': 'TableV2.Column',
                            'x-app-version': '1.6.0-beta.15',
                            properties: {
                              time: {
                                _isJSONSchemaObject: true,
                                version: '2.0',
                                'x-collection-field': 'general.time',
                                'x-component': 'CollectionField',
                                'x-component-props': {},
                                'x-read-pretty': true,
                                'x-decorator': null,
                                'x-decorator-props': {
                                  labelStyle: {
                                    display: 'none',
                                  },
                                },
                                'x-app-version': '1.6.0-beta.15',
                                'x-uid': 'p168mtpnfmt',
                                'x-async': false,
                                'x-index': 1,
                              },
                            },
                            'x-uid': 'l3vanfk00ha',
                            'x-async': false,
                            'x-index': 2,
                          },
                        },
                        'x-uid': 'dkj7c2zq5cz',
                        'x-async': false,
                        'x-index': 2,
                      },
                    },
                    'x-uid': 'm0fxi87rolp',
                    'x-async': false,
                    'x-index': 1,
                  },
                },
                'x-uid': 'ws6yw0yn42w',
                'x-async': false,
                'x-index': 1,
              },
            },
            'x-uid': 'vl9c8frvxdd',
            'x-async': false,
            'x-index': 1,
          },
        },
        name: 'e46pcjcbi86',
        'x-uid': 'n4d6da78d5e',
        'x-async': true,
        'x-index': 1,
      },
    },
    'x-uid': 'ml7rypfikcm',
    'x-async': true,
    'x-index': 1,
  },
};
