/**
 * This file is part of the NocoBase (R) project.
 * Copyright (c) 2020-2024 NocoBase Co., Ltd.
 * Authors: NocoBase Team.
 *
 * This project is dual-licensed under AGPL-3.0 and NocoBase Commercial License.
 * For more information, please refer to: https://www.nocobase.com/agreement.
 */
import { createAvatar } from '@dicebear/core';
import * as notionists from '@dicebear/notionists';

export const avatars = (seed: string, options?: any) => {
  const avatar = createAvatar(notionists, {
    ...avatarsMap[seed],
    gestureProbability: 0,
    scale: 130,
    ...options,
  });
  return avatar.toDataUri();
};

export const avatarsMap = {
  'notion-0-female': {
    seed: 'notion-0-female',
    gender: 'female',
    hair: ['variant08'],
    lips: ['variant21'],
    eyes: ['variant03'],
    brows: ['variant04'],
    backgroundColor: ['fff7ed'],
    beardProbability: 0,
    glassesProbability: 0,
  },
  'notion-1-female': {
    seed: 'notion-1-female',
    gender: 'female',
    hair: ['variant43'],
    lips: ['variant13'],
    eyes: ['variant03'],
    brows: ['variant08'],
    backgroundColor: ['fae8ff'],
    beardProbability: 0,
    glassesProbability: 0,
  },
  'notion-2-male': {
    seed: 'notion-2-male',
    gender: 'male',
    hair: ['variant12'],
    lips: ['variant22'],
    eyes: ['variant03'],
    brows: ['variant05'],
    backgroundColor: ['fff7ed'],
    beard: ['variant10'],
    beardProbability: 68,
    glasses: ['variant03'],
    glassesProbability: 100,
  },
  'notion-3-male': {
    seed: 'notion-3-male',
    gender: 'male',
    hair: ['variant56'],
    lips: ['variant04'],
    eyes: ['variant05'],
    brows: ['variant10'],
    backgroundColor: ['e0e7ff'],
    beardProbability: 0,
    glasses: ['variant11'],
    glassesProbability: 100,
  },
  'notion-4-female': {
    seed: 'notion-4-female',
    gender: 'female',
    hair: ['variant08'],
    lips: ['variant21'],
    eyes: ['variant05'],
    brows: ['variant08'],
    backgroundColor: ['f0fdf4'],
    beardProbability: 0,
    glassesProbability: 0,
  },
  'notion-5-male': {
    seed: 'notion-5-male',
    gender: 'male',
    hair: ['variant34'],
    lips: ['variant21'],
    eyes: ['variant05'],
    brows: ['variant04'],
    backgroundColor: ['e0e7ff'],
    beardProbability: 0,
    glasses: ['variant03'],
    glassesProbability: 100,
  },
  'notion-6-female': {
    seed: 'notion-6-female',
    gender: 'female',
    hair: ['variant02'],
    lips: ['variant13'],
    eyes: ['variant02'],
    brows: ['variant07'],
    backgroundColor: ['c0aede'],
    beardProbability: 0,
    glasses: ['variant08'],
    glassesProbability: 100,
  },
  'notion-7-male': {
    seed: 'notion-7-male',
    gender: 'male',
    hair: ['variant17'],
    lips: ['variant04'],
    eyes: ['variant03'],
    brows: ['variant04'],
    backgroundColor: ['fce7f3'],
    beard: ['variant03'],
    beardProbability: 61,
    glasses: ['variant11'],
    glassesProbability: 100,
  },
  'notion-8-male': {
    seed: 'notion-8-male',
    gender: 'male',
    hair: ['variant18'],
    lips: ['variant13'],
    eyes: ['variant02'],
    brows: ['variant02'],
    backgroundColor: ['e0f2fe'],
    beard: ['variant12'],
    beardProbability: 38,
    glassesProbability: 0,
  },
  'notion-9-female': {
    seed: 'notion-9-female',
    gender: 'female',
    hair: ['variant57'],
    lips: ['variant13'],
    eyes: ['variant04'],
    brows: ['variant09'],
    backgroundColor: ['e0f2fe'],
    beardProbability: 0,
    glasses: ['variant08'],
    glassesProbability: 100,
  },
  'notion-10-male': {
    seed: 'notion-10-male',
    gender: 'male',
    hair: ['variant34'],
    lips: ['variant13'],
    eyes: ['variant02'],
    brows: ['variant01'],
    backgroundColor: ['ede9fe'],
    beardProbability: 0,
    glasses: ['variant03'],
    glassesProbability: 100,
  },
  'notion-11-male': {
    seed: 'notion-11-male',
    gender: 'male',
    hair: ['variant07'],
    lips: ['variant21'],
    eyes: ['variant02'],
    brows: ['variant07'],
    backgroundColor: ['e0f7fa'],
    beardProbability: 0,
    glasses: ['variant08'],
    glassesProbability: 100,
  },
  'notion-12-male': {
    seed: 'notion-12-male',
    gender: 'male',
    hair: ['variant49'],
    lips: ['variant22'],
    eyes: ['variant02'],
    brows: ['variant09'],
    backgroundColor: ['d1d4f9'],
    beardProbability: 0,
    glasses: ['variant08'],
    glassesProbability: 100,
  },
  'notion-13-male': {
    seed: 'notion-13-male',
    gender: 'male',
    hair: ['hat'],
    lips: ['variant22'],
    eyes: ['variant02'],
    brows: ['variant04'],
    backgroundColor: ['fae8ff'],
    beard: ['variant11'],
    beardProbability: 46,
    glassesProbability: 0,
  },
  'notion-14-male': {
    seed: 'notion-14-male',
    gender: 'male',
    hair: ['variant21'],
    lips: ['variant13'],
    eyes: ['variant02'],
    brows: ['variant05'],
    backgroundColor: ['fef3c7'],
    beardProbability: 0,
    glasses: ['variant11'],
    glassesProbability: 100,
  },
  'notion-15-female': {
    seed: 'notion-15-female',
    gender: 'female',
    hair: ['variant29'],
    lips: ['variant21'],
    eyes: ['variant05'],
    brows: ['variant12'],
    backgroundColor: ['d1d4f9'],
    beardProbability: 0,
    glassesProbability: 0,
  },
  'notion-16-male': {
    seed: 'notion-16-male',
    gender: 'male',
    hair: ['variant24'],
    lips: ['variant21'],
    eyes: ['variant05'],
    brows: ['variant07'],
    backgroundColor: ['fef3c7'],
    beardProbability: 0,
    glasses: ['variant03'],
    glassesProbability: 100,
  },
  'notion-17-female': {
    seed: 'notion-17-female',
    gender: 'female',
    hair: ['variant28'],
    lips: ['variant04'],
    eyes: ['variant04'],
    brows: ['variant08'],
    backgroundColor: ['b6e3f4'],
    beardProbability: 0,
    glassesProbability: 0,
  },
  'notion-18-male': {
    seed: 'notion-18-male',
    gender: 'male',
    hair: ['variant18'],
    lips: ['variant04'],
    eyes: ['variant02'],
    brows: ['variant09'],
    backgroundColor: ['ffdfbf'],
    beard: ['variant12'],
    beardProbability: 40,
    glassesProbability: 0,
  },
  'notion-19-male': {
    seed: 'notion-19-male',
    gender: 'male',
    hair: ['variant22'],
    lips: ['variant22'],
    eyes: ['variant04'],
    brows: ['variant07'],
    backgroundColor: ['fce7f3'],
    beardProbability: 0,
    glassesProbability: 0,
  },
  'notion-20-female': {
    seed: 'notion-20-female',
    gender: 'female',
    hair: ['variant28'],
    lips: ['variant13'],
    eyes: ['variant03'],
    brows: ['variant01'],
    backgroundColor: ['fae8ff'],
    beardProbability: 0,
    glasses: ['variant11'],
    glassesProbability: 100,
  },
  'notion-21-male': {
    seed: 'notion-21-male',
    gender: 'male',
    hair: ['variant56'],
    lips: ['variant13'],
    eyes: ['variant03'],
    brows: ['variant02'],
    backgroundColor: ['b6e3f4'],
    beard: ['variant10'],
    beardProbability: 68,
    glassesProbability: 0,
  },
  'notion-22-male': {
    seed: 'notion-22-male',
    gender: 'male',
    hair: ['variant60'],
    lips: ['variant22'],
    eyes: ['variant05'],
    brows: ['variant08'],
    backgroundColor: ['e0f7fa'],
    beard: ['variant11'],
    beardProbability: 59,
    glasses: ['variant11'],
    glassesProbability: 100,
  },
  'notion-23-female': {
    seed: 'notion-23-female',
    gender: 'female',
    hair: ['variant28'],
    lips: ['variant21'],
    eyes: ['variant04'],
    brows: ['variant07'],
    backgroundColor: ['fef9c3'],
    beardProbability: 0,
    glasses: ['variant08'],
    glassesProbability: 100,
  },
  'notion-24-male': {
    seed: 'notion-24-male',
    gender: 'male',
    hair: ['variant06'],
    lips: ['variant04'],
    eyes: ['variant02'],
    brows: ['variant09'],
    backgroundColor: ['fff7ed'],
    beard: ['variant09'],
    beardProbability: 24,
    glasses: ['variant08'],
    glassesProbability: 100,
  },
  'notion-25-male': {
    seed: 'notion-25-male',
    gender: 'male',
    hair: ['variant06'],
    lips: ['variant04'],
    eyes: ['variant02'],
    brows: ['variant11'],
    backgroundColor: ['ede9fe'],
    beard: ['variant09'],
    beardProbability: 55,
    glasses: ['variant03'],
    glassesProbability: 100,
  },
  'notion-26-female': {
    seed: 'notion-26-female',
    gender: 'female',
    hair: ['variant57'],
    lips: ['variant22'],
    eyes: ['variant05'],
    brows: ['variant09'],
    backgroundColor: ['ffdfbf'],
    beardProbability: 0,
    glasses: ['variant03'],
    glassesProbability: 100,
  },
  'notion-27-female': {
    seed: 'notion-27-female',
    gender: 'female',
    hair: ['variant02'],
    lips: ['variant21'],
    eyes: ['variant04'],
    brows: ['variant08'],
    backgroundColor: ['e0f7fa'],
    beardProbability: 0,
    glasses: ['variant11'],
    glassesProbability: 100,
  },
  'notion-28-female': {
    seed: 'notion-28-female',
    gender: 'female',
    hair: ['variant43'],
    lips: ['variant04'],
    eyes: ['variant05'],
    brows: ['variant10'],
    backgroundColor: ['c0aede'],
    beardProbability: 0,
    glassesProbability: 0,
  },
  'notion-29-male': {
    seed: 'notion-29-male',
    gender: 'male',
    hair: ['variant07'],
    lips: ['variant22'],
    eyes: ['variant01'],
    brows: ['variant09'],
    backgroundColor: ['e0f2fe'],
    beardProbability: 0,
    glassesProbability: 0,
  },
  'notion-30-female': {
    seed: 'notion-30-female',
    gender: 'female',
    hair: ['variant41'],
    lips: ['variant21'],
    eyes: ['variant04'],
    brows: ['variant11'],
    backgroundColor: ['fff7ed'],
    beardProbability: 0,
    glasses: ['variant03'],
    glassesProbability: 100,
  },
  'notion-31-female': {
    seed: 'notion-31-female',
    gender: 'female',
    hair: ['variant39'],
    lips: ['variant21'],
    eyes: ['variant02'],
    brows: ['variant02'],
    backgroundColor: ['ffd5dc'],
    beardProbability: 0,
    glasses: ['variant03'],
    glassesProbability: 100,
  },
  'notion-32-female': {
    seed: 'notion-32-female',
    gender: 'female',
    hair: ['variant46'],
    lips: ['variant13'],
    eyes: ['variant03'],
    brows: ['variant05'],
    backgroundColor: ['e0e7ff'],
    beardProbability: 0,
    glassesProbability: 0,
  },
  'notion-33-male': {
    seed: 'notion-33-male',
    gender: 'male',
    hair: ['variant19'],
    lips: ['variant13'],
    eyes: ['variant04'],
    brows: ['variant08'],
    backgroundColor: ['c0aede'],
    beardProbability: 0,
    glasses: ['variant08'],
    glassesProbability: 100,
  },
  'notion-34-female': {
    seed: 'notion-34-female',
    gender: 'female',
    hair: ['variant58'],
    lips: ['variant13'],
    eyes: ['variant02'],
    brows: ['variant11'],
    backgroundColor: ['fce7f3'],
    beardProbability: 0,
    glassesProbability: 0,
  },
  'notion-35-male': {
    seed: 'notion-35-male',
    gender: 'male',
    hair: ['variant22'],
    lips: ['variant21'],
    eyes: ['variant03'],
    brows: ['variant12'],
    backgroundColor: ['fff7ed'],
    beardProbability: 0,
    glasses: ['variant03'],
    glassesProbability: 100,
  },
  'notion-36-female': {
    seed: 'notion-36-female',
    gender: 'female',
    hair: ['variant36'],
    lips: ['variant13'],
    eyes: ['variant04'],
    brows: ['variant12'],
    backgroundColor: ['b6e3f4'],
    beardProbability: 0,
    glassesProbability: 0,
  },
  'notion-37-female': {
    seed: 'notion-37-female',
    gender: 'female',
    hair: ['variant48'],
    lips: ['variant21'],
    eyes: ['variant03'],
    brows: ['variant02'],
    backgroundColor: ['ede9fe'],
    beardProbability: 0,
    glassesProbability: 0,
  },
  'notion-38-female': {
    seed: 'notion-38-female',
    gender: 'female',
    hair: ['variant43'],
    lips: ['variant21'],
    eyes: ['variant02'],
    brows: ['variant02'],
    backgroundColor: ['d1d4f9'],
    beardProbability: 0,
    glassesProbability: 0,
  },
  'notion-39-female': {
    seed: 'notion-39-female',
    gender: 'female',
    hair: ['variant39'],
    lips: ['variant21'],
    eyes: ['variant01'],
    brows: ['variant11'],
    backgroundColor: ['ffdfbf'],
    beardProbability: 0,
    glasses: ['variant03'],
    glassesProbability: 100,
  },
  'notion-40-male': {
    seed: 'notion-40-male',
    gender: 'male',
    hair: ['variant44'],
    lips: ['variant21'],
    eyes: ['variant01'],
    brows: ['variant02'],
    backgroundColor: ['fef9c3'],
    beardProbability: 0,
    glasses: ['variant08'],
    glassesProbability: 100,
  },
  'notion-41-female': {
    seed: 'notion-41-female',
    gender: 'female',
    hair: ['variant45'],
    lips: ['variant21'],
    eyes: ['variant02'],
    brows: ['variant02'],
    backgroundColor: ['fff7ed'],
    beardProbability: 0,
    glasses: ['variant03'],
    glassesProbability: 100,
  },
  'notion-42-female': {
    seed: 'notion-42-female',
    gender: 'female',
    hair: ['variant58'],
    lips: ['variant13'],
    eyes: ['variant04'],
    brows: ['variant01'],
    backgroundColor: ['f0fdf4'],
    beardProbability: 0,
    glasses: ['variant03'],
    glassesProbability: 100,
  },
  'notion-43-female': {
    seed: 'notion-43-female',
    gender: 'female',
    hair: ['variant36'],
    lips: ['variant22'],
    eyes: ['variant01'],
    brows: ['variant12'],
    backgroundColor: ['e0f2fe'],
    beardProbability: 0,
    glasses: ['variant03'],
    glassesProbability: 100,
  },
  'notion-44-male': {
    seed: 'notion-44-male',
    gender: 'male',
    hair: ['variant32'],
    lips: ['variant13'],
    eyes: ['variant02'],
    brows: ['variant09'],
    backgroundColor: ['fff7ed'],
    beard: ['variant09'],
    beardProbability: 56,
    glasses: ['variant03'],
    glassesProbability: 100,
  },
  'notion-45-female': {
    seed: 'notion-45-female',
    gender: 'female',
    hair: ['variant45'],
    lips: ['variant22'],
    eyes: ['variant04'],
    brows: ['variant10'],
    backgroundColor: ['c0aede'],
    beardProbability: 0,
    glasses: ['variant03'],
    glassesProbability: 100,
  },
  'notion-46-male': {
    seed: 'notion-46-male',
    gender: 'male',
    hair: ['variant12'],
    lips: ['variant04'],
    eyes: ['variant02'],
    brows: ['variant02'],
    backgroundColor: ['fff7ed'],
    beard: ['variant03'],
    beardProbability: 75,
    glassesProbability: 0,
  },
  'notion-47-female': {
    seed: 'notion-47-female',
    gender: 'female',
    hair: ['variant41'],
    lips: ['variant21'],
    eyes: ['variant04'],
    brows: ['variant01'],
    backgroundColor: ['fce7f3'],
    beardProbability: 0,
    glasses: ['variant11'],
    glassesProbability: 100,
  },
  'notion-48-male': {
    seed: 'notion-48-male',
    gender: 'male',
    hair: ['variant07'],
    lips: ['variant04'],
    eyes: ['variant05'],
    brows: ['variant09'],
    backgroundColor: ['e0e7ff'],
    beardProbability: 0,
    glassesProbability: 0,
  },
  'notion-49-male': {
    seed: 'notion-49-male',
    gender: 'male',
    hair: ['variant60'],
    lips: ['variant22'],
    eyes: ['variant02'],
    brows: ['variant12'],
    backgroundColor: ['fef3c7'],
    beard: ['variant09'],
    beardProbability: 31,
    glasses: ['variant11'],
    glassesProbability: 100,
  },
};
