/**
 * This file is part of the NocoBase (R) project.
 * Copyright (c) 2020-2024 NocoBase Co., Ltd.
 * Authors: NocoBase Team.
 *
 * This project is dual-licensed under AGPL-3.0 and NocoBase Commercial License.
 * For more information, please refer to: https://www.nocobase.com/agreement.
 */
import { createAvatar } from '@dicebear/core';
import * as nocobaseAvatars from '@nocobase/ai-employee-avatars';
export const avatars = (seed: string, options?: any) => {
  const avatar = createAvatar(nocobaseAvatars, {
    ...avatarsMap[seed],
    gestureProbability: 0,
    scale: 100,
    ...options,
  });
  return avatar.toDataUri();
};

export const avatarsMap = {
  'nocobase-001-male': {
    seed: 'nocobase-001-male',
    gender: 'male',
    base: ['green'],
    hair: ['man002'],
    mouth: ['unisex001'],
    clothes: ['unisex008'],
    earing: ['unisex001'],
    earingProbability: 100,
    glasses: undefined,
    glassesProbability: 0,
  },
  'nocobase-002-female': {
    seed: 'nocobase-002-female',
    gender: 'female',
    base: ['green'],
    hair: ['woman006'],
    mouth: ['unisex001'],
    clothes: ['woman002'],
    earing: ['woman001'],
    earingProbability: 100,
    glasses: undefined,
    glassesProbability: 0,
  },
  'nocobase-003-male': {
    seed: 'nocobase-003-male',
    gender: 'male',
    base: ['green'],
    hair: ['man004'],
    mouth: ['unisex001'],
    clothes: ['unisex-013'],
    earing: undefined,
    earingProbability: 0,
    glasses: ['unisex001'],
    glassesProbability: 100,
  },
  'nocobase-004-female': {
    seed: 'nocobase-004-female',
    gender: 'female',
    base: ['blue'],
    hair: ['woman010'],
    mouth: ['unisex001'],
    clothes: ['unisex012'],
    earing: ['woman004'],
    earingProbability: 100,
    glasses: undefined,
    glassesProbability: 0,
  },
  'nocobase-005-female': {
    seed: 'nocobase-005-female',
    gender: 'female',
    base: ['red'],
    hair: ['woman010'],
    mouth: ['unisex001'],
    clothes: ['woman002'],
    earing: undefined,
    earingProbability: 0,
    glasses: ['unisex001'],
    glassesProbability: 100,
  },
  'nocobase-006-female': {
    seed: 'nocobase-006-female',
    gender: 'female',
    base: ['yellow'],
    hair: ['woman008'],
    mouth: ['unisex001'],
    clothes: ['unisex-013'],
    earing: ['unisex001'],
    earingProbability: 100,
    glasses: ['unisex002'],
    glassesProbability: 100,
  },
  'nocobase-007-female': {
    seed: 'nocobase-007-female',
    gender: 'female',
    base: ['red'],
    hair: ['woman001'],
    mouth: ['unisex001'],
    clothes: ['unisex-015'],
    earing: undefined,
    earingProbability: 0,
    glasses: undefined,
    glassesProbability: 0,
  },
  'nocobase-008-male': {
    seed: 'nocobase-008-male',
    gender: 'male',
    base: ['red'],
    hair: ['man008'],
    mouth: ['unisex001'],
    clothes: ['unisex-014'],
    earing: undefined,
    earingProbability: 0,
    glasses: undefined,
    glassesProbability: 0,
  },
  'nocobase-009-female': {
    seed: 'nocobase-009-female',
    gender: 'female',
    base: ['red'],
    hair: ['woman003'],
    mouth: ['unisex001'],
    clothes: ['woman002'],
    earing: undefined,
    earingProbability: 0,
    glasses: ['unisex002'],
    glassesProbability: 100,
  },
  'nocobase-010-female': {
    seed: 'nocobase-010-female',
    gender: 'female',
    base: ['purple'],
    hair: ['woman009'],
    mouth: ['unisex001'],
    clothes: ['woman004'],
    earing: ['woman002'],
    earingProbability: 100,
    glasses: ['unisex001'],
    glassesProbability: 100,
  },
  'nocobase-011-male': {
    seed: 'nocobase-011-male',
    gender: 'male',
    base: ['blue'],
    hair: ['man006'],
    mouth: ['unisex001'],
    clothes: ['unisex006'],
    earing: undefined,
    earingProbability: 0,
    glasses: ['unisex001'],
    glassesProbability: 100,
  },
  'nocobase-012-female': {
    seed: 'nocobase-012-female',
    gender: 'female',
    base: ['purple'],
    hair: ['woman005'],
    mouth: ['unisex001'],
    clothes: ['unisex010'],
    earing: ['woman004'],
    earingProbability: 100,
    glasses: ['unisex001'],
    glassesProbability: 100,
  },
  'nocobase-013-male': {
    seed: 'nocobase-013-male',
    gender: 'male',
    base: ['green'],
    hair: ['man005'],
    mouth: ['unisex001'],
    clothes: ['unisex-013'],
    earing: undefined,
    earingProbability: 0,
    glasses: ['unisex002'],
    glassesProbability: 100,
  },
  'nocobase-014-female': {
    seed: 'nocobase-014-female',
    gender: 'female',
    base: ['purple'],
    hair: ['woman011'],
    mouth: ['unisex001'],
    clothes: ['unisex001'],
    earing: undefined,
    earingProbability: 0,
    glasses: ['unisex002'],
    glassesProbability: 100,
  },
  'nocobase-015-male': {
    seed: 'nocobase-015-male',
    gender: 'male',
    base: ['blue'],
    hair: ['man007'],
    mouth: ['unisex001'],
    clothes: ['unisex003'],
    earing: ['unisex001'],
    earingProbability: 100,
    glasses: undefined,
    glassesProbability: 0,
  },
  'nocobase-016-female': {
    seed: 'nocobase-016-female',
    gender: 'female',
    base: ['purple'],
    hair: ['woman004'],
    mouth: ['unisex001'],
    clothes: ['unisex011'],
    earing: undefined,
    earingProbability: 0,
    glasses: undefined,
    glassesProbability: 0,
  },
  'nocobase-017-male': {
    seed: 'nocobase-017-male',
    gender: 'male',
    base: ['green'],
    hair: ['man004'],
    mouth: ['unisex001'],
    clothes: ['unisex010'],
    earing: ['unisex001'],
    earingProbability: 100,
    glasses: undefined,
    glassesProbability: 0,
  },
  'nocobase-018-female': {
    seed: 'nocobase-018-female',
    gender: 'female',
    base: ['green'],
    hair: ['woman005'],
    mouth: ['unisex001'],
    clothes: ['unisex002'],
    earing: undefined,
    earingProbability: 0,
    glasses: ['unisex002'],
    glassesProbability: 100,
  },
  'nocobase-019-male': {
    seed: 'nocobase-019-male',
    gender: 'male',
    base: ['green'],
    hair: ['man002'],
    mouth: ['unisex001'],
    clothes: ['unisex-014'],
    earing: ['unisex002'],
    earingProbability: 100,
    glasses: ['unisex002'],
    glassesProbability: 100,
  },
  'nocobase-020-male': {
    seed: 'nocobase-020-male',
    gender: 'male',
    base: ['blue'],
    hair: ['man006'],
    mouth: ['unisex001'],
    clothes: ['unisex004'],
    earing: ['unisex002'],
    earingProbability: 100,
    glasses: undefined,
    glassesProbability: 0,
  },
  'nocobase-021-female': {
    seed: 'nocobase-021-female',
    gender: 'female',
    base: ['blue'],
    hair: ['woman005'],
    mouth: ['unisex001'],
    clothes: ['unisex009'],
    earing: ['unisex002'],
    earingProbability: 100,
    glasses: undefined,
    glassesProbability: 0,
  },
  'nocobase-022-female': {
    seed: 'nocobase-022-female',
    gender: 'female',
    base: ['yellow'],
    hair: ['woman012'],
    mouth: ['unisex001'],
    clothes: ['unisex016'],
    earing: ['unisex002'],
    earingProbability: 100,
    glasses: ['unisex002'],
    glassesProbability: 100,
  },
  'nocobase-023-female': {
    seed: 'nocobase-023-female',
    gender: 'female',
    base: ['red'],
    hair: ['woman001'],
    mouth: ['unisex001'],
    clothes: ['unisex011'],
    earing: undefined,
    earingProbability: 0,
    glasses: undefined,
    glassesProbability: 0,
  },
  'nocobase-024-male': {
    seed: 'nocobase-024-male',
    gender: 'male',
    base: ['red'],
    hair: ['man004'],
    mouth: ['unisex001'],
    clothes: ['unisex-015'],
    earing: ['unisex002'],
    earingProbability: 100,
    glasses: ['unisex002'],
    glassesProbability: 100,
  },
  'nocobase-025-female': {
    seed: 'nocobase-025-female',
    gender: 'female',
    base: ['red'],
    hair: ['woman012'],
    mouth: ['unisex001'],
    clothes: ['unisex008'],
    earing: ['woman003'],
    earingProbability: 100,
    glasses: ['unisex002'],
    glassesProbability: 100,
  },
  'nocobase-026-female': {
    seed: 'nocobase-026-female',
    gender: 'female',
    base: ['yellow'],
    hair: ['woman012'],
    mouth: ['unisex001'],
    clothes: ['unisex-015'],
    earing: undefined,
    earingProbability: 0,
    glasses: ['unisex002'],
    glassesProbability: 100,
  },
  'nocobase-027-male': {
    seed: 'nocobase-027-male',
    gender: 'male',
    base: ['blue'],
    hair: ['man003'],
    mouth: ['unisex001'],
    clothes: ['unisex006'],
    earing: ['unisex001'],
    earingProbability: 100,
    glasses: undefined,
    glassesProbability: 0,
  },
  'nocobase-028-male': {
    seed: 'nocobase-028-male',
    gender: 'male',
    base: ['yellow'],
    hair: ['man001'],
    mouth: ['unisex001'],
    clothes: ['unisex-013'],
    earing: undefined,
    earingProbability: 0,
    glasses: undefined,
    glassesProbability: 0,
  },
  'nocobase-029-male': {
    seed: 'nocobase-029-male',
    gender: 'male',
    base: ['blue'],
    hair: ['man004'],
    mouth: ['unisex001'],
    clothes: ['unisex003'],
    earing: undefined,
    earingProbability: 0,
    glasses: undefined,
    glassesProbability: 0,
  },
  'nocobase-030-male': {
    seed: 'nocobase-030-male',
    gender: 'male',
    base: ['green'],
    hair: ['man002'],
    mouth: ['unisex001'],
    clothes: ['unisex007'],
    earing: undefined,
    earingProbability: 0,
    glasses: ['unisex002'],
    glassesProbability: 100,
  },
  'nocobase-031-male': {
    seed: 'nocobase-031-male',
    gender: 'male',
    base: ['green'],
    hair: ['man005'],
    mouth: ['unisex001'],
    clothes: ['unisex-014'],
    earing: ['unisex002'],
    earingProbability: 100,
    glasses: undefined,
    glassesProbability: 0,
  },
  'nocobase-032-female': {
    seed: 'nocobase-032-female',
    gender: 'female',
    base: ['red'],
    hair: ['woman006'],
    mouth: ['unisex001'],
    clothes: ['unisex009'],
    earing: undefined,
    earingProbability: 0,
    glasses: undefined,
    glassesProbability: 0,
  },
  'nocobase-033-male': {
    seed: 'nocobase-033-male',
    gender: 'male',
    base: ['yellow'],
    hair: ['man002'],
    mouth: ['unisex001'],
    clothes: ['unisex-014'],
    earing: undefined,
    earingProbability: 0,
    glasses: undefined,
    glassesProbability: 0,
  },
  'nocobase-034-male': {
    seed: 'nocobase-034-male',
    gender: 'male',
    base: ['red'],
    hair: ['man005'],
    mouth: ['unisex001'],
    clothes: ['unisex009'],
    earing: ['unisex001'],
    earingProbability: 100,
    glasses: undefined,
    glassesProbability: 0,
  },
  'nocobase-035-female': {
    seed: 'nocobase-035-female',
    gender: 'female',
    base: ['green'],
    hair: ['woman005'],
    mouth: ['unisex001'],
    clothes: ['unisex007'],
    earing: ['woman003'],
    earingProbability: 100,
    glasses: ['unisex002'],
    glassesProbability: 100,
  },
  'nocobase-036-female': {
    seed: 'nocobase-036-female',
    gender: 'female',
    base: ['green'],
    hair: ['woman001'],
    mouth: ['unisex001'],
    clothes: ['unisex006'],
    earing: undefined,
    earingProbability: 0,
    glasses: ['unisex001'],
    glassesProbability: 100,
  },
  'nocobase-037-male': {
    seed: 'nocobase-037-male',
    gender: 'male',
    base: ['yellow'],
    hair: ['man001'],
    mouth: ['unisex001'],
    clothes: ['unisex-015'],
    earing: undefined,
    earingProbability: 0,
    glasses: undefined,
    glassesProbability: 0,
  },
  'nocobase-038-male': {
    seed: 'nocobase-038-male',
    gender: 'male',
    base: ['yellow'],
    hair: ['man003'],
    mouth: ['unisex001'],
    clothes: ['unisex007'],
    earing: undefined,
    earingProbability: 0,
    glasses: ['unisex002'],
    glassesProbability: 100,
  },
  'nocobase-039-female': {
    seed: 'nocobase-039-female',
    gender: 'female',
    base: ['purple'],
    hair: ['woman012'],
    mouth: ['unisex001'],
    clothes: ['unisex011'],
    earing: undefined,
    earingProbability: 0,
    glasses: ['unisex002'],
    glassesProbability: 100,
  },
  'nocobase-040-male': {
    seed: 'nocobase-040-male',
    gender: 'male',
    base: ['green'],
    hair: ['man001'],
    mouth: ['unisex001'],
    clothes: ['unisex001'],
    earing: ['unisex002'],
    earingProbability: 100,
    glasses: ['unisex002'],
    glassesProbability: 100,
  },
  'nocobase-041-male': {
    seed: 'nocobase-041-male',
    gender: 'male',
    base: ['red'],
    hair: ['man002'],
    mouth: ['unisex001'],
    clothes: ['unisex005'],
    earing: undefined,
    earingProbability: 0,
    glasses: undefined,
    glassesProbability: 0,
  },
  'nocobase-042-female': {
    seed: 'nocobase-042-female',
    gender: 'female',
    base: ['green'],
    hair: ['woman009'],
    mouth: ['unisex001'],
    clothes: ['unisex007'],
    earing: undefined,
    earingProbability: 0,
    glasses: undefined,
    glassesProbability: 0,
  },
  'nocobase-043-female': {
    seed: 'nocobase-043-female',
    gender: 'female',
    base: ['blue'],
    hair: ['woman007'],
    mouth: ['unisex001'],
    clothes: ['woman002'],
    earing: ['woman002'],
    earingProbability: 100,
    glasses: undefined,
    glassesProbability: 0,
  },
  'nocobase-044-male': {
    seed: 'nocobase-044-male',
    gender: 'male',
    base: ['purple'],
    hair: ['man003'],
    mouth: ['unisex001'],
    clothes: ['unisex006'],
    earing: undefined,
    earingProbability: 0,
    glasses: undefined,
    glassesProbability: 0,
  },
  'nocobase-045-female': {
    seed: 'nocobase-045-female',
    gender: 'female',
    base: ['purple'],
    hair: ['woman002'],
    mouth: ['unisex001'],
    clothes: ['unisex005'],
    earing: undefined,
    earingProbability: 0,
    glasses: undefined,
    glassesProbability: 0,
  },
  'nocobase-046-female': {
    seed: 'nocobase-046-female',
    gender: 'female',
    base: ['green'],
    hair: ['woman009'],
    mouth: ['unisex001'],
    clothes: ['unisex-014'],
    earing: undefined,
    earingProbability: 0,
    glasses: undefined,
    glassesProbability: 0,
  },
  'nocobase-047-male': {
    seed: 'nocobase-047-male',
    gender: 'male',
    base: ['red'],
    hair: ['man006'],
    mouth: ['unisex001'],
    clothes: ['unisex004'],
    earing: ['unisex002'],
    earingProbability: 100,
    glasses: undefined,
    glassesProbability: 0,
  },
  'nocobase-048-male': {
    seed: 'nocobase-048-male',
    gender: 'male',
    base: ['purple'],
    hair: ['man004'],
    mouth: ['unisex001'],
    clothes: ['unisex005'],
    earing: ['unisex002'],
    earingProbability: 100,
    glasses: ['unisex001'],
    glassesProbability: 100,
  },
  'nocobase-049-female': {
    seed: 'nocobase-049-female',
    gender: 'female',
    base: ['red'],
    hair: ['woman007'],
    mouth: ['unisex001'],
    clothes: ['unisex008'],
    earing: ['woman004'],
    earingProbability: 100,
    glasses: undefined,
    glassesProbability: 0,
  },
  'nocobase-050-male': {
    seed: 'nocobase-050-male',
    gender: 'male',
    base: ['purple'],
    hair: ['man005'],
    mouth: ['unisex001'],
    clothes: ['unisex-015'],
    earing: undefined,
    earingProbability: 0,
    glasses: undefined,
    glassesProbability: 0,
  },
};
