import { dayjs } from '@nocobase/utils';
import { lowerCase } from 'lodash';

/**
 * 为json对象中collections节点的name、title属性添加后缀
 * 为json对象中fields节点的collectionName、through、target性添加后缀
 * @param jsonObj json对象
 * @param appendText 后缀文本
 */
export function appendJsonCollectionName(jsonObj: any, appendText: string) {
  appendCollectionsNode(jsonObj, appendText);
  for (const item of jsonObj['collections'][0]['fields']) {
    appendFieldsNode(item, appendText);
  }
  return jsonObj;
}

function appendCollectionsNode(jsonObj: any, appendText: string) {
  jsonObj['collections'][0]['name'] += appendText;
  jsonObj['collections'][0]['title'] += appendText;
}
function appendFieldsNode(jsonObj: any, appendText: string) {
  for (const key in jsonObj) {
    if (key === 'collectionName' || key === 'through' || key === 'target') {
      jsonObj[key] += appendText;
    }
  }
}
/**
 * @returns 生成3位随机小写字母
 */
export function generateRandomLetters() {
  let result = '';
  const characters = 'abcdefghijklmnopqrstuvwxyz';
  for (let i = 0; i < 3; i++) {
    result += characters.charAt(Math.floor(Math.random() * characters.length));
  }
  return result;
}
/**
 * builtin_ 为NocoBase内置模板，同NocoBase在页面创建效果一致主要用法3种：
 *  1是测试用例仅需一个无业务字段的表即可验证，
 *  2是作为多对多的中间表，
 *  3是存在先表后关系字段的情况，使用create内置模板表再update表的方式更新数据表来添加全部字段
 * e2e_ 按照不同场景的数据表，可以多个测试用例共用一个或一套数据表
 */
export const builtin_General = {
  collections: [
    {
      key: 'hqh4qy21m46',
      name: 'tt_amt_org',
      title: '自动>组织[普通表]',
      inherit: false,
      hidden: false,
      description: null,
      fields: [
        {
          key: 'z3fvals50xp',
          name: 'id',
          type: 'bigInt',
          interface: 'id',
          description: null,
          collectionName: 'tt_amt_org',
          parentKey: null,
          reverseKey: null,
          autoIncrement: true,
          primaryKey: true,
          allowNull: false,
          uiSchema: {
            type: 'number',
            title: '{{t("ID")}}',
            'x-component': 'InputNumber',
            'x-read-pretty': true,
          },
        },
        {
          key: '3cp1zy4ogle',
          name: 'createdAt',
          type: 'date',
          interface: 'createdAt',
          description: null,
          collectionName: 'tt_amt_org',
          parentKey: null,
          reverseKey: null,
          field: 'createdAt',
          uiSchema: {
            type: 'datetime',
            title: '{{t("Created at")}}',
            'x-component': 'DatePicker',
            'x-component-props': {},
            'x-read-pretty': true,
          },
        },
        {
          key: '6l38n4nt7nb',
          name: 'createdBy',
          type: 'belongsTo',
          interface: 'createdBy',
          description: null,
          collectionName: 'tt_amt_org',
          parentKey: null,
          reverseKey: null,
          target: 'users',
          foreignKey: 'createdById',
          uiSchema: {
            type: 'object',
            title: '{{t("Created by")}}',
            'x-component': 'AssociationField',
            'x-component-props': {
              fieldNames: {
                value: 'id',
                label: 'nickname',
              },
            },
            'x-read-pretty': true,
          },
          targetKey: 'id',
        },
        {
          key: '3xds0p7ersr',
          name: 'updatedAt',
          type: 'date',
          interface: 'updatedAt',
          description: null,
          collectionName: 'tt_amt_org',
          parentKey: null,
          reverseKey: null,
          field: 'updatedAt',
          uiSchema: {
            type: 'string',
            title: '{{t("Last updated at")}}',
            'x-component': 'DatePicker',
            'x-component-props': {},
            'x-read-pretty': true,
          },
        },
        {
          key: 'slqyx974mzc',
          name: 'updatedBy',
          type: 'belongsTo',
          interface: 'updatedBy',
          description: null,
          collectionName: 'tt_amt_org',
          parentKey: null,
          reverseKey: null,
          target: 'users',
          foreignKey: 'updatedById',
          uiSchema: {
            type: 'object',
            title: '{{t("Last updated by")}}',
            'x-component': 'AssociationField',
            'x-component-props': {
              fieldNames: {
                value: 'id',
                label: 'nickname',
              },
            },
            'x-read-pretty': true,
          },
          targetKey: 'id',
        },
      ],
      category: [],
      logging: true,
      autoGenId: true,
      createdBy: true,
      updatedBy: true,
      createdAt: true,
      updatedAt: true,
      sortable: true,
      template: 'general',
      view: false,
      schema: 'public',
    },
  ],
};
export const builtin_Calendar = {
  collections: [
    {
      key: '7lfgblnyr0w',
      name: 'tt_amt_org_cld',
      title: '自动>组织[日历表]',
      inherit: false,
      hidden: false,
      description: null,
      fields: [
        {
          key: 'nq6a40fz0nd',
          name: 'cron',
          type: 'string',
          interface: 'select',
          description: null,
          collectionName: 'tt_amt_org_cld',
          parentKey: null,
          reverseKey: null,
          uiSchema: {
            type: 'string',
            title: '{{t("Repeats")}}',
            'x-component': 'CronSet',
            'x-component-props': 'allowClear',
            enum: [
              {
                label: '{{t("Daily")}}',
                value: '0 0 0 * * ?',
              },
              {
                label: '{{t("Weekly")}}',
                value: 'every_week',
              },
              {
                label: '{{t("Monthly")}}',
                value: 'every_month',
              },
              {
                label: '{{t("Yearly")}}',
                value: 'every_year',
              },
            ],
          },
        },
        {
          key: 'qtxt638o4nq',
          name: 'exclude',
          type: 'json',
          interface: null,
          description: null,
          collectionName: 'tt_amt_org_cld',
          parentKey: null,
          reverseKey: null,
        },
        {
          key: 'ly88an4fg8f',
          name: 'id',
          type: 'bigInt',
          interface: 'id',
          description: null,
          collectionName: 'tt_amt_org_cld',
          parentKey: null,
          reverseKey: null,
          autoIncrement: true,
          primaryKey: true,
          allowNull: false,
          uiSchema: {
            type: 'number',
            title: '{{t("ID")}}',
            'x-component': 'InputNumber',
            'x-read-pretty': true,
          },
        },
        {
          key: '8fiqtpovg79',
          name: 'createdAt',
          type: 'date',
          interface: 'createdAt',
          description: null,
          collectionName: 'tt_amt_org_cld',
          parentKey: null,
          reverseKey: null,
          field: 'createdAt',
          uiSchema: {
            type: 'datetime',
            title: '{{t("Created at")}}',
            'x-component': 'DatePicker',
            'x-component-props': {},
            'x-read-pretty': true,
          },
        },
        {
          key: 'hup33jdnp9j',
          name: 'createdBy',
          type: 'belongsTo',
          interface: 'createdBy',
          description: null,
          collectionName: 'tt_amt_org_cld',
          parentKey: null,
          reverseKey: null,
          target: 'users',
          foreignKey: 'createdById',
          uiSchema: {
            type: 'object',
            title: '{{t("Created by")}}',
            'x-component': 'AssociationField',
            'x-component-props': {
              fieldNames: {
                value: 'id',
                label: 'nickname',
              },
            },
            'x-read-pretty': true,
          },
          targetKey: 'id',
        },
        {
          key: '4ky6wvfhduq',
          name: 'updatedAt',
          type: 'date',
          interface: 'updatedAt',
          description: null,
          collectionName: 'tt_amt_org_cld',
          parentKey: null,
          reverseKey: null,
          field: 'updatedAt',
          uiSchema: {
            type: 'string',
            title: '{{t("Last updated at")}}',
            'x-component': 'DatePicker',
            'x-component-props': {},
            'x-read-pretty': true,
          },
        },
        {
          key: '1xht59blk26',
          name: 'updatedBy',
          type: 'belongsTo',
          interface: 'updatedBy',
          description: null,
          collectionName: 'tt_amt_org_cld',
          parentKey: null,
          reverseKey: null,
          target: 'users',
          foreignKey: 'updatedById',
          uiSchema: {
            type: 'object',
            title: '{{t("Last updated by")}}',
            'x-component': 'AssociationField',
            'x-component-props': {
              fieldNames: {
                value: 'id',
                label: 'nickname',
              },
            },
            'x-read-pretty': true,
          },
          targetKey: 'id',
        },
      ],
      category: [],
      logging: true,
      template: 'calendar',
      view: false,
      createdBy: true,
      updatedBy: true,
      createdAt: true,
      updatedAt: true,
      sortable: true,
      schema: 'public',
    },
  ],
};
export const builtin_Tree = {
  collections: [
    {
      key: 'wvgsufr1uxv',
      name: 'tt_amt_org_tree',
      title: '自动>组织[树表]',
      inherit: false,
      hidden: false,
      description: null,
      fields: [
        {
          key: '4ihc87rzn00',
          name: 'parentId',
          type: 'bigInt',
          interface: 'integer',
          description: null,
          collectionName: 'tt_amt_org_tree',
          parentKey: null,
          reverseKey: null,
          isForeignKey: true,
          uiSchema: {
            type: 'number',
            title: '{{t("Parent ID")}}',
            'x-component': 'InputNumber',
            'x-read-pretty': true,
          },
          target: 'tt_amt_org_tree',
        },
        {
          key: 'j58bfihyjdy',
          name: 'parent',
          type: 'belongsTo',
          interface: 'm2o',
          description: null,
          collectionName: 'tt_amt_org_tree',
          parentKey: null,
          reverseKey: null,
          foreignKey: 'parentId',
          treeParent: true,
          onDelete: 'CASCADE',
          uiSchema: {
            title: '{{t("Parent")}}',
            'x-component': 'AssociationField',
            'x-component-props': {
              multiple: false,
              fieldNames: {
                label: 'id',
                value: 'id',
              },
            },
          },
          target: 'tt_amt_org_tree',
          targetKey: 'id',
        },
        {
          key: '6r6b98g0hcz',
          name: 'children',
          type: 'hasMany',
          interface: 'o2m',
          description: null,
          collectionName: 'tt_amt_org_tree',
          parentKey: null,
          reverseKey: null,
          foreignKey: 'parentId',
          treeChildren: true,
          onDelete: 'CASCADE',
          uiSchema: {
            title: '{{t("Children")}}',
            'x-component': 'AssociationField',
            'x-component-props': {
              multiple: true,
              fieldNames: {
                label: 'id',
                value: 'id',
              },
            },
          },
          target: 'tt_amt_org_tree',
          targetKey: 'id',
          sourceKey: 'id',
        },
        {
          key: 'hju1ggqps4n',
          name: 'id',
          type: 'bigInt',
          interface: 'id',
          description: null,
          collectionName: 'tt_amt_org_tree',
          parentKey: null,
          reverseKey: null,
          autoIncrement: true,
          primaryKey: true,
          allowNull: false,
          uiSchema: {
            type: 'number',
            title: '{{t("ID")}}',
            'x-component': 'InputNumber',
            'x-read-pretty': true,
          },
        },
        {
          key: '1y7rpmh8muj',
          name: 'createdAt',
          type: 'date',
          interface: 'createdAt',
          description: null,
          collectionName: 'tt_amt_org_tree',
          parentKey: null,
          reverseKey: null,
          field: 'createdAt',
          uiSchema: {
            type: 'datetime',
            title: '{{t("Created at")}}',
            'x-component': 'DatePicker',
            'x-component-props': {},
            'x-read-pretty': true,
          },
        },
        {
          key: 'ieknujjdkv9',
          name: 'createdBy',
          type: 'belongsTo',
          interface: 'createdBy',
          description: null,
          collectionName: 'tt_amt_org_tree',
          parentKey: null,
          reverseKey: null,
          target: 'users',
          foreignKey: 'createdById',
          uiSchema: {
            type: 'object',
            title: '{{t("Created by")}}',
            'x-component': 'AssociationField',
            'x-component-props': {
              fieldNames: {
                value: 'id',
                label: 'nickname',
              },
            },
            'x-read-pretty': true,
          },
          targetKey: 'id',
        },
        {
          key: 'cv35rzoqna6',
          name: 'updatedAt',
          type: 'date',
          interface: 'updatedAt',
          description: null,
          collectionName: 'tt_amt_org_tree',
          parentKey: null,
          reverseKey: null,
          field: 'updatedAt',
          uiSchema: {
            type: 'string',
            title: '{{t("Last updated at")}}',
            'x-component': 'DatePicker',
            'x-component-props': {},
            'x-read-pretty': true,
          },
        },
        {
          key: 'z21wfpry7uh',
          name: 'updatedBy',
          type: 'belongsTo',
          interface: 'updatedBy',
          description: null,
          collectionName: 'tt_amt_org_tree',
          parentKey: null,
          reverseKey: null,
          target: 'users',
          foreignKey: 'updatedById',
          uiSchema: {
            type: 'object',
            title: '{{t("Last updated by")}}',
            'x-component': 'AssociationField',
            'x-component-props': {
              fieldNames: {
                value: 'id',
                label: 'nickname',
              },
            },
            'x-read-pretty': true,
          },
          targetKey: 'id',
        },
      ],
      category: [],
      logging: true,
      autoGenId: true,
      createdBy: true,
      updatedBy: true,
      createdAt: true,
      updatedAt: true,
      sortable: true,
      template: 'tree',
      view: false,
      tree: 'adjacencyList',
      schema: 'public',
    },
  ],
};
export const builtin_File = {
  collections: [
    {
      key: '6hzed4cvpxo',
      name: 'tt_amt_file',
      title: '自动>档案[文件表]',
      inherit: false,
      hidden: false,
      description: null,
      fields: [
        {
          key: 'qo0w8dcl45u',
          name: 'title',
          type: 'string',
          interface: 'input',
          description: null,
          collectionName: 'tt_amt_file',
          parentKey: null,
          reverseKey: null,
          deletable: false,
          uiSchema: {
            type: 'string',
            title: '{{t("Title")}}',
            'x-component': 'Input',
          },
        },
        {
          key: 'ayzc9b3aee5',
          name: 'filename',
          type: 'string',
          interface: 'input',
          description: null,
          collectionName: 'tt_amt_file',
          parentKey: null,
          reverseKey: null,
          deletable: false,
          uiSchema: {
            type: 'string',
            title: '{{t("File name", { ns: "file-manager" })}}',
            'x-component': 'Input',
            'x-read-pretty': true,
          },
        },
        {
          key: 'ftn60zv1rfr',
          name: 'extname',
          type: 'string',
          interface: 'input',
          description: null,
          collectionName: 'tt_amt_file',
          parentKey: null,
          reverseKey: null,
          deletable: false,
          uiSchema: {
            type: 'string',
            title: '{{t("Extension name", { ns: "file-manager" })}}',
            'x-component': 'Input',
            'x-read-pretty': true,
          },
        },
        {
          key: '59oj6m0r8be',
          name: 'size',
          type: 'integer',
          interface: 'integer',
          description: null,
          collectionName: 'tt_amt_file',
          parentKey: null,
          reverseKey: null,
          deletable: false,
          uiSchema: {
            type: 'number',
            title: '{{t("Size", { ns: "file-manager" })}}',
            'x-component': 'InputNumber',
            'x-read-pretty': true,
            'x-component-props': {
              stringMode: true,
              step: '0',
            },
          },
        },
        {
          key: 'burt1tfbcjx',
          name: 'mimetype',
          type: 'string',
          interface: 'input',
          description: null,
          collectionName: 'tt_amt_file',
          parentKey: null,
          reverseKey: null,
          deletable: false,
          uiSchema: {
            type: 'string',
            title: '{{t("Mime type", { ns: "file-manager" })}}',
            'x-component': 'Input',
            'x-read-pretty': true,
          },
        },
        {
          key: '1zfhbqod0i1',
          name: 'path',
          type: 'string',
          interface: 'input',
          description: null,
          collectionName: 'tt_amt_file',
          parentKey: null,
          reverseKey: null,
          deletable: false,
          uiSchema: {
            type: 'string',
            title: '{{t("Path")}}',
            'x-component': 'Input',
            'x-read-pretty': true,
          },
        },
        {
          key: 'b0bmsmrfqqw',
          name: 'url',
          type: 'string',
          interface: 'input',
          description: null,
          collectionName: 'tt_amt_file',
          parentKey: null,
          reverseKey: null,
          deletable: false,
          uiSchema: {
            type: 'string',
            title: '{{t("URL")}}',
            'x-component': 'Input.URL',
            'x-read-pretty': true,
          },
        },
        {
          key: 'indgsp9sqqq',
          name: 'preview',
          type: 'string',
          interface: 'url',
          description: null,
          collectionName: 'tt_amt_file',
          parentKey: null,
          reverseKey: null,
          field: 'url',
          deletable: false,
          uiSchema: {
            type: 'string',
            title: '{{t("Preview")}}',
            'x-component': 'Preview',
            'x-read-pretty': true,
          },
        },
        {
          key: '2p8d1h46x9l',
          name: 'storage',
          type: 'belongsTo',
          interface: null,
          description: null,
          collectionName: 'tt_amt_file',
          parentKey: null,
          reverseKey: null,
          comment: '存储引擎',
          target: 'storages',
          foreignKey: 'storageId',
          deletable: false,
          targetKey: 'id',
        },
        {
          key: 'im0yegvb5jt',
          name: 'meta',
          type: 'jsonb',
          interface: null,
          description: null,
          collectionName: 'tt_amt_file',
          parentKey: null,
          reverseKey: null,
          deletable: false,
          defaultValue: {},
        },
        {
          key: 'tjr9nr5thoh',
          name: 'id',
          type: 'bigInt',
          interface: 'id',
          description: null,
          collectionName: 'tt_amt_file',
          parentKey: null,
          reverseKey: null,
          autoIncrement: true,
          primaryKey: true,
          allowNull: false,
          uiSchema: {
            type: 'number',
            title: '{{t("ID")}}',
            'x-component': 'InputNumber',
            'x-read-pretty': true,
          },
        },
        {
          key: 's48vjiqbjcq',
          name: 'createdAt',
          type: 'date',
          interface: 'createdAt',
          description: null,
          collectionName: 'tt_amt_file',
          parentKey: null,
          reverseKey: null,
          field: 'createdAt',
          uiSchema: {
            type: 'datetime',
            title: '{{t("Created at")}}',
            'x-component': 'DatePicker',
            'x-component-props': {},
            'x-read-pretty': true,
          },
        },
        {
          key: 'y3t7jii4m8w',
          name: 'createdBy',
          type: 'belongsTo',
          interface: 'createdBy',
          description: null,
          collectionName: 'tt_amt_file',
          parentKey: null,
          reverseKey: null,
          target: 'users',
          foreignKey: 'createdById',
          uiSchema: {
            type: 'object',
            title: '{{t("Created by")}}',
            'x-component': 'RecordPicker',
            'x-component-props': {
              fieldNames: {
                value: 'id',
                label: 'nickname',
              },
            },
            'x-read-pretty': true,
          },
          targetKey: 'id',
        },
        {
          key: 'z5gvejdbfyb',
          name: 'updatedAt',
          type: 'date',
          interface: 'updatedAt',
          description: null,
          collectionName: 'tt_amt_file',
          parentKey: null,
          reverseKey: null,
          field: 'updatedAt',
          uiSchema: {
            type: 'string',
            title: '{{t("Last updated at")}}',
            'x-component': 'DatePicker',
            'x-component-props': {},
            'x-read-pretty': true,
          },
        },
        {
          key: 'qgd8zko7b0z',
          name: 'updatedBy',
          type: 'belongsTo',
          interface: 'updatedBy',
          description: null,
          collectionName: 'tt_amt_file',
          parentKey: null,
          reverseKey: null,
          target: 'users',
          foreignKey: 'updatedById',
          uiSchema: {
            type: 'object',
            title: '{{t("Last updated by")}}',
            'x-component': 'RecordPicker',
            'x-component-props': {
              fieldNames: {
                value: 'id',
                label: 'nickname',
              },
            },
            'x-read-pretty': true,
          },
          targetKey: 'id',
        },
      ],
      category: [],
      logging: true,
      template: 'file',
      view: false,
      createdBy: true,
      updatedBy: true,
      storage: 'local',
      schema: 'public',
    },
  ],
};
export const builtin_Expression = {
  collections: [
    {
      key: 'w77iro3197g',
      name: 'tt_amt_exp',
      title: '自动>表达式[表达式表]',
      inherit: false,
      hidden: false,
      description: null,
      fields: [
        {
          key: 'slc2i7yz2ck',
          name: 'engine',
          type: 'string',
          interface: 'radioGroup',
          description: null,
          collectionName: 'tt_amt_exp',
          parentKey: null,
          reverseKey: null,
          uiSchema: {
            type: 'string',
            title: '{{t("Calculation engine")}}',
            'x-component': 'Radio.Group',
            enum: [
              {
                value: 'math.js',
                label: 'Math.js',
                tooltip:
                  "{{t('Math.js comes with a large set of built-in functions and constants, and offers an integrated solution to work with different data types')}}",
                link: 'https://mathjs.org/',
              },
              {
                value: 'formula.js',
                label: 'Formula.js',
                tooltip: '{{t("Formula.js supports most Microsoft Excel formula functions.")}}',
                link: 'https://formulajs.info/functions/',
              },
            ],
            default: 'formula.js',
          },
        },
        {
          key: 'mlvkdcg2yvq',
          name: 'sourceCollection',
          type: 'string',
          interface: 'select',
          description: null,
          collectionName: 'tt_amt_exp',
          parentKey: null,
          reverseKey: null,
          uiSchema: {
            type: 'string',
            title: '{{t("Collection")}}',
            'x-component': 'CollectionSelect',
            'x-component-props': {},
          },
        },
        {
          key: 'vdzigakt9ne',
          name: 'expression',
          type: 'text',
          interface: 'expression',
          description: null,
          collectionName: 'tt_amt_exp',
          parentKey: null,
          reverseKey: null,
          uiSchema: {
            type: 'string',
            title: '{{t("Expression")}}',
            'x-component': 'DynamicExpression',
          },
        },
        {
          key: 'fx72pqt0fjv',
          name: 'id',
          type: 'bigInt',
          interface: 'id',
          description: null,
          collectionName: 'tt_amt_exp',
          parentKey: null,
          reverseKey: null,
          autoIncrement: true,
          primaryKey: true,
          allowNull: false,
          uiSchema: {
            type: 'number',
            title: '{{t("ID")}}',
            'x-component': 'InputNumber',
            'x-read-pretty': true,
          },
        },
        {
          key: 'owiio66cw1u',
          name: 'createdAt',
          type: 'date',
          interface: 'createdAt',
          description: null,
          collectionName: 'tt_amt_exp',
          parentKey: null,
          reverseKey: null,
          field: 'createdAt',
          uiSchema: {
            type: 'datetime',
            title: '{{t("Created at")}}',
            'x-component': 'DatePicker',
            'x-component-props': {},
            'x-read-pretty': true,
          },
        },
        {
          key: '9fu8kmc69dj',
          name: 'createdBy',
          type: 'belongsTo',
          interface: 'createdBy',
          description: null,
          collectionName: 'tt_amt_exp',
          parentKey: null,
          reverseKey: null,
          target: 'users',
          foreignKey: 'createdById',
          uiSchema: {
            type: 'object',
            title: '{{t("Created by")}}',
            'x-component': 'RecordPicker',
            'x-component-props': {
              fieldNames: {
                value: 'id',
                label: 'nickname',
              },
            },
            'x-read-pretty': true,
          },
          targetKey: 'id',
        },
        {
          key: 'uie8q16z2jj',
          name: 'updatedAt',
          type: 'date',
          interface: 'updatedAt',
          description: null,
          collectionName: 'tt_amt_exp',
          parentKey: null,
          reverseKey: null,
          field: 'updatedAt',
          uiSchema: {
            type: 'string',
            title: '{{t("Last updated at")}}',
            'x-component': 'DatePicker',
            'x-component-props': {},
            'x-read-pretty': true,
          },
        },
        {
          key: '6jzyuc1jzro',
          name: 'updatedBy',
          type: 'belongsTo',
          interface: 'updatedBy',
          description: null,
          collectionName: 'tt_amt_exp',
          parentKey: null,
          reverseKey: null,
          target: 'users',
          foreignKey: 'updatedById',
          uiSchema: {
            type: 'object',
            title: '{{t("Last updated by")}}',
            'x-component': 'RecordPicker',
            'x-component-props': {
              fieldNames: {
                value: 'id',
                label: 'nickname',
              },
            },
            'x-read-pretty': true,
          },
          targetKey: 'id',
        },
      ],
      category: [],
      logging: true,
      template: 'expression',
      view: false,
      createdBy: true,
      updatedBy: true,
      createdAt: true,
      updatedAt: true,
      sortable: true,
      schema: 'public',
    },
  ],
};
//普通表单表场景，无关系字段情况
export const e2e_GeneralFormsTable = {
  collections: [
    {
      key: '86lpobjxamt',
      name: 'tt_amt_org',
      title: '自动>组织[普通表]',
      inherit: false,
      hidden: false,
      fields: [
        {
          key: 'ohxa8xp9amt',
          name: 'id',
          type: 'bigInt',
          interface: 'id',
          collectionName: 'tt_amt_org',
          parentKey: null,
          reverseKey: null,
          autoIncrement: true,
          primaryKey: true,
          allowNull: false,
          uiSchema: {
            type: 'number',
            title: '{{t("ID")}}',
            'x-component': 'InputNumber',
            'x-read-pretty': true,
          },
        },
        {
          key: 'qjit9pcvamt',
          name: 'createdAt',
          type: 'date',
          interface: 'createdAt',
          collectionName: 'tt_amt_org',
          parentKey: null,
          reverseKey: null,
          field: 'createdAt',
          uiSchema: {
            type: 'datetime',
            title: '{{t("Created at")}}',
            'x-component': 'DatePicker',
            'x-component-props': {},
            'x-read-pretty': true,
          },
        },
        {
          key: 'vijs3wcnamt',
          name: 'createdBy',
          type: 'belongsTo',
          interface: 'createdBy',
          collectionName: 'tt_amt_org',
          parentKey: null,
          reverseKey: null,
          target: 'users',
          foreignKey: 'createdById',
          uiSchema: {
            type: 'object',
            title: '{{t("Created by")}}',
            'x-component': 'AssociationField',
            'x-component-props': {
              fieldNames: {
                value: 'id',
                label: 'nickname',
              },
            },
            'x-read-pretty': true,
          },
          targetKey: 'id',
        },
        {
          key: 'zsebjtwiamt',
          name: 'updatedAt',
          type: 'date',
          interface: 'updatedAt',
          collectionName: 'tt_amt_org',
          parentKey: null,
          reverseKey: null,
          field: 'updatedAt',
          uiSchema: {
            type: 'string',
            title: '{{t("Last updated at")}}',
            'x-component': 'DatePicker',
            'x-component-props': {},
            'x-read-pretty': true,
          },
        },
        {
          key: 'fa4c74phamt',
          name: 'updatedBy',
          type: 'belongsTo',
          interface: 'updatedBy',
          collectionName: 'tt_amt_org',
          parentKey: null,
          reverseKey: null,
          target: 'users',
          foreignKey: 'updatedById',
          uiSchema: {
            type: 'object',
            title: '{{t("Last updated by")}}',
            'x-component': 'AssociationField',
            'x-component-props': {
              fieldNames: {
                value: 'id',
                label: 'nickname',
              },
            },
            'x-read-pretty': true,
          },
          targetKey: 'id',
        },
        {
          key: 'mv6h7f8lamt',
          name: 'orgcode',
          type: 'sequence',
          interface: 'sequence',
          collectionName: 'tt_amt_org',
          parentKey: null,
          reverseKey: null,
          patterns: [
            {
              type: 'string',
              options: {
                value: '区域编码',
              },
            },
            {
              type: 'integer',
              options: {
                digits: 9,
                start: 1,
                key: 57450,
              },
            },
          ],
          uiSchema: {
            type: 'string',
            'x-component': 'Input',
            'x-component-props': {},
            title: '公司编号(自动编码)',
          },
          inputable: false,
        },
        {
          key: '44u5zoyyamt',
          name: 'orgname',
          type: 'string',
          interface: 'input',
          collectionName: 'tt_amt_org',
          parentKey: null,
          reverseKey: null,
          uiSchema: {
            type: 'string',
            'x-component': 'Input',
            title: '公司名称(单行文本)',
          },
        },
        {
          key: 'tdq82bb0amt',
          name: 'address',
          type: 'text',
          interface: 'textarea',
          collectionName: 'tt_amt_org',
          parentKey: null,
          reverseKey: null,
          uiSchema: {
            type: 'string',
            'x-component': 'Input.TextArea',
            title: '公司地址(多行文本)',
          },
        },
        {
          key: '10xi6i24amt',
          name: 'phone',
          type: 'string',
          interface: 'phone',
          collectionName: 'tt_amt_org',
          parentKey: null,
          reverseKey: null,
          uiSchema: {
            type: 'string',
            'x-component': 'Input',
            'x-component-props': {
              type: 'tel',
            },
            title: '负责人电话(手机号码)',
          },
        },
        {
          key: 'n3ykqhe4amt',
          name: 'email',
          type: 'string',
          interface: 'email',
          collectionName: 'tt_amt_org',
          parentKey: null,
          reverseKey: null,
          uiSchema: {
            type: 'string',
            'x-component': 'Input',
            'x-validator': 'email',
            title: '电子邮箱(电子邮箱)',
          },
        },
        {
          key: '5ddcgbpqamt',
          name: 'staffnum',
          type: 'bigInt',
          interface: 'integer',
          collectionName: 'tt_amt_org',
          parentKey: null,
          reverseKey: null,
          uiSchema: {
            type: 'number',
            'x-component': 'InputNumber',
            'x-component-props': {
              stringMode: true,
              step: '1',
            },
            'x-validator': 'integer',
            title: '员工人数(整数)',
          },
        },
        {
          key: 'z59sf4ilamt',
          name: 'insurednum',
          type: 'bigInt',
          interface: 'integer',
          collectionName: 'tt_amt_org',
          parentKey: null,
          reverseKey: null,
          uiSchema: {
            type: 'number',
            'x-component': 'InputNumber',
            'x-component-props': {
              stringMode: true,
              step: '1',
            },
            'x-validator': 'integer',
            title: '参保人数(整数)',
          },
        },
        {
          key: 'ecvb3a8xamt',
          name: 'regcapital',
          type: 'double',
          interface: 'number',
          collectionName: 'tt_amt_org',
          parentKey: null,
          reverseKey: null,
          uiSchema: {
            'x-component-props': {
              step: '0.0001',
              stringMode: true,
            },
            type: 'number',
            'x-component': 'InputNumber',
            title: '注册资本(数字)',
          },
        },
        {
          key: 'ierg1fbvamt',
          name: 'paidcapital',
          type: 'double',
          interface: 'number',
          collectionName: 'tt_amt_org',
          parentKey: null,
          reverseKey: null,
          uiSchema: {
            'x-component-props': {
              step: '0.0001',
              stringMode: true,
            },
            type: 'number',
            'x-component': 'InputNumber',
            title: '实缴资本(数字)',
          },
        },
        {
          key: '46kjnywaamt',
          name: 'insuranceratio',
          type: 'float',
          interface: 'percent',
          collectionName: 'tt_amt_org',
          parentKey: null,
          reverseKey: null,
          uiSchema: {
            'x-component-props': {
              step: '0.01',
              stringMode: true,
              addonAfter: '%',
            },
            type: 'string',
            'x-component': 'Percent',
            title: '参保占比(百分比)',
          },
        },
        {
          key: '8j2vkys9amt',
          name: 'isenable',
          type: 'boolean',
          interface: 'checkbox',
          collectionName: 'tt_amt_org',
          parentKey: null,
          reverseKey: null,
          uiSchema: {
            type: 'boolean',
            'x-component': 'Checkbox',
            title: '是否启用(勾选)',
          },
        },
        {
          key: '6f480de5amt',
          name: 'status_singleselect',
          type: 'string',
          interface: 'select',
          collectionName: 'tt_amt_org',
          parentKey: null,
          reverseKey: null,
          uiSchema: {
            enum: [
              {
                value: '1',
                label: '存续',
              },
              {
                value: '2',
                label: '在业',
              },
              {
                value: '3',
                label: '吊销',
              },
              {
                value: '4',
                label: '注销',
              },
              {
                value: '5',
                label: '迁入',
              },
              {
                value: '6',
                label: '迁出',
              },
              {
                value: '7',
                label: '停业',
              },
              {
                value: '8',
                label: '清算',
              },
            ],
            type: 'string',
            'x-component': 'Select',
            title: '公司状态(下拉单选)',
          },
        },
        {
          key: 'fcx8cw1ramt',
          name: 'range_multipleselect',
          type: 'array',
          interface: 'multipleSelect',
          collectionName: 'tt_amt_org',
          parentKey: null,
          reverseKey: null,
          uiSchema: {
            enum: [
              {
                value: 'F3134',
                label: '软件销售',
              },
              {
                value: 'I3006',
                label: '软件开发',
              },
              {
                value: 'I3007',
                label: '人工智能基础软件开发',
              },
              {
                value: 'I3008',
                label: '人工智能应用软件开发',
              },
              {
                value: 'I3010',
                label: '软件外包服务',
              },
              {
                value: 'I3011',
                label: '网络与信息安全软件开发',
              },
              {
                value: 'I3012',
                label: '人工智能理论与算法软件开发',
              },
              {
                value: 'I3014',
                label: '数字文化创意软件开发',
              },
              {
                value: 'I3027',
                label: '信息技术咨询服务',
              },
              {
                value: 'I3032',
                label: '数据处理服务',
              },
              {
                value: 'I3034',
                label: '计算机系统服务',
              },
              {
                value: 'L2032',
                label: '信息咨询服务（不含许可类信息咨询服务）',
              },
              {
                value: 'L2095',
                label: '企业管理咨询',
              },
              {
                value: 'M2070',
                label: '技术服务、技术开发、技术咨询、技术交流、技术转让、技术推广',
              },
              {
                value: 'O3010',
                label: '咨询策划服务',
              },
              {
                value: 'P1029',
                label: '业务培训（不含教育培训、职业技能培训等需取得许可的培训）',
              },
            ],
            type: 'array',
            'x-component': 'Select',
            'x-component-props': {
              mode: 'multiple',
            },
            title: '经营范围(下拉多选)',
          },
          defaultValue: [],
        },
        {
          key: 'z71al7aaamt',
          name: 'status_radio',
          type: 'string',
          interface: 'radioGroup',
          collectionName: 'tt_amt_org',
          parentKey: null,
          reverseKey: null,
          uiSchema: {
            enum: [
              {
                value: '1',
                label: '存续',
              },
              {
                value: '2',
                label: '在业',
              },
              {
                value: '3',
                label: '吊销',
              },
              {
                value: '4',
                label: '注销',
              },
              {
                value: '5',
                label: '迁入',
              },
              {
                value: '6',
                label: '迁出',
              },
              {
                value: '7',
                label: '停业',
              },
              {
                value: '8',
                label: '清算',
              },
            ],
            type: 'string',
            'x-component': 'Radio.Group',
            title: '公司状态(单选)',
          },
        },
        {
          key: 'x8v9qf95amt',
          name: 'range_check',
          type: 'array',
          interface: 'checkboxGroup',
          collectionName: 'tt_amt_org',
          parentKey: null,
          reverseKey: null,
          uiSchema: {
            enum: [
              {
                value: 'F3134',
                label: '软件销售',
              },
              {
                value: 'I3006',
                label: '软件开发',
              },
              {
                value: 'I3007',
                label: '人工智能基础软件开发',
              },
              {
                value: 'I3008',
                label: '人工智能应用软件开发',
              },
              {
                value: 'I3010',
                label: '软件外包服务',
              },
              {
                value: 'I3011',
                label: '网络与信息安全软件开发',
              },
              {
                value: 'I3012',
                label: '人工智能理论与算法软件开发',
              },
              {
                value: 'I3014',
                label: '数字文化创意软件开发',
              },
              {
                value: 'I3027',
                label: '信息技术咨询服务',
              },
              {
                value: 'I3032',
                label: '数据处理服务',
              },
              {
                value: 'I3034',
                label: '计算机系统服务',
              },
              {
                value: 'L2032',
                label: '信息咨询服务（不含许可类信息咨询服务）',
              },
              {
                value: 'L2095',
                label: '企业管理咨询',
              },
              {
                value: 'M2070',
                label: '技术服务、技术开发、技术咨询、技术交流、技术转让、技术推广',
              },
              {
                value: 'O3010',
                label: '咨询策划服务',
              },
              {
                value: 'P1029',
                label: '业务培训（不含教育培训、职业技能培训等需取得许可的培训）',
              },
            ],
            type: 'string',
            'x-component': 'Checkbox.Group',
            title: '经营范围(复选)',
          },
          defaultValue: [],
        },
        {
          key: 'c50l1zguamt',
          name: 'range_markdown',
          type: 'text',
          interface: 'markdown',
          collectionName: 'tt_amt_org',
          parentKey: null,
          reverseKey: null,
          uiSchema: {
            type: 'string',
            'x-component': 'Markdown',
            title: '经营范围(Markdown)',
          },
        },
        {
          key: 'msj1qa4damt',
          name: 'range_richtext',
          type: 'text',
          interface: 'richText',
          collectionName: 'tt_amt_org',
          parentKey: null,
          reverseKey: null,
          uiSchema: {
            type: 'string',
            'x-component': 'RichText',
            title: '经营范围(富文本)',
          },
        },
        {
          key: 'q755hkxmamt',
          name: 'establishdate',
          type: 'date',
          interface: 'datetime',
          collectionName: 'tt_amt_org',
          parentKey: null,
          reverseKey: null,
          uiSchema: {
            'x-component-props': {
              dateFormat: 'YYYY-MM-DD',
              gmt: false,
              showTime: false,
            },
            type: 'string',
            'x-component': 'DatePicker',
            title: '成立日期(日期)',
          },
        },
        {
          key: '9kn4ujeramt',
          name: 'range_json',
          type: 'json',
          interface: 'json',
          collectionName: 'tt_amt_org',
          parentKey: null,
          reverseKey: null,
          defaultValue: null,
          uiSchema: {
            type: 'object',
            'x-component': 'Input.JSON',
            'x-component-props': {
              autoSize: {
                minRows: 5,
              },
            },
            default: null,
            title: '经营范围(JSON)',
          },
        },
        {
          key: 'vqcsj7htamt',
          name: 'url',
          type: 'string',
          interface: 'url',
          collectionName: 'tt_amt_org',
          parentKey: null,
          reverseKey: null,
          uiSchema: {
            type: 'string',
            title: '官网地址(URL)',
            'x-component': 'Input.URL',
          },
        },
        {
          key: '0naiw2nq4j0',
          name: 'insuranceratio_formula',
          type: 'formula',
          interface: 'formula',
          collectionName: 'tt_amt_org',
          parentKey: null,
          reverseKey: null,
          dataType: 'double',
          uiSchema: {
            'x-component-props': {
              step: '0.01',
              stringMode: true,
            },
            type: 'number',
            'x-component': 'Formula.Result',
            'x-read-pretty': true,
            title: '参保占比(公式)',
          },
          engine: 'math.js',
          expression: '100*{{insurednum}}/{{staffnum}}',
        },
        {
          key: 'fd9sqp8usoj',
          name: 'sharesnum',
          type: 'bigInt',
          interface: 'integer',
          collectionName: 'tt_amt_org',
          parentKey: null,
          reverseKey: null,
          uiSchema: {
            type: 'number',
            'x-component': 'InputNumber',
            'x-component-props': {
              stringMode: true,
              step: '1',
            },
            'x-validator': 'integer',
            title: '股票数量(整数)',
          },
        },
      ],
      category: [],
      logging: true,
      autoGenId: true,
      createdBy: true,
      updatedBy: true,
      createdAt: true,
      updatedAt: true,
      sortable: true,
      template: 'general',
    },
  ],
};
export const e2e_GeneralFormsTableData = [
  {
    createdAt: '2023-07-16T21:30:58.000Z',
    updatedAt: '2023-06-20T03:32:01.000Z',
    createdById: 0,
    updatedById: 3,
    id: 86,
    orgcode: '350086',
    orgname: 'Black Logistic LLC',
    address: '闵行区宾川路314号',
    phone: '21-040-5877',
    email: 'cwlam@mail.com',
    url: 'http://www.osara.co.jp/Food',
    staffnum: 25,
    regcapital: 85.8799,
    paidcapital: 297.1762,
    insuranceratio: 29.93,
    isenable: true,
    status_singleselect: '1',
    range_multipleselect: ['F3134', 'I3007', 'I3011', 'I3012', 'I3014', 'I3027'],
    status_radio: '4',
    range_check: ['I3010', 'I3011', 'I3014', 'I3027', 'L2095', 'M2070', 'O3010'],
    establishdate: '2022-03-17T19:44:50.000Z',
  },
  {
    createdAt: '2023-03-14T23:05:00.000Z',
    updatedAt: '2023-07-10T02:25:11.729Z',
    createdById: null,
    updatedById: 4,
    id: 27,
    orgcode: '340027',
    orgname: 'Lisa Telecommunication Inc.',
    address: '43 Zhongshan 5th Rd, Zimaling Shangquan',
    phone: '760-7344-2889',
    email: 'onnaku@gmail.com',
    url: 'https://video.ziyihe404.net/CenturionGardenOutdoor',
    staffnum: 104,
    regcapital: 237.9354,
    paidcapital: 131.6008,
    insuranceratio: 4.22,
    isenable: true,
    status_singleselect: '2',
    range_multipleselect: ['F3134', 'I3032', 'I3034', 'L2032', 'M2070', 'O3010'],
    status_radio: '6',
    range_check: ['F3134', 'I3006', 'I3008', 'I3012', 'M2070', 'O3010'],
    establishdate: '2021-02-19T00:02:48.000Z',
  },
  {
    createdAt: '2023-08-20T18:07:24.000Z',
    updatedAt: '2023-07-10T02:25:11.741Z',
    createdById: 5,
    updatedById: null,
    id: 77,
    orgcode: '450077',
    orgname: '子异有限责任公司',
    address: '619 4th Section  Renmin South Road, Jinjiang District',
    phone: '174-6088-1418',
    email: 'taoshihan1@hotmail.com',
    url: 'https://www.litc908.jp/ArtsHandicraftsSewing',
    staffnum: 37,
    regcapital: 237.5694,
    paidcapital: 94.707,
    insuranceratio: null,
    isenable: true,
    status_singleselect: '2',
    range_multipleselect: ['F3134', 'I3008', 'I3011', 'I3014'],
    status_radio: '5',
    range_check: ['I3006', 'I3007', 'I3008', 'I3010', 'I3034', 'L2032', 'L2095', 'M2070', 'O3010'],
    establishdate: '2023-10-07T23:30:43.000Z',
  },
  {
    createdAt: '2023-07-13T13:20:10.000Z',
    updatedAt: '2023-07-10T02:25:11.737Z',
    createdById: 4,
    updatedById: null,
    id: 41,
    orgcode: '230041',
    orgname: '孙記有限责任公司',
    address: '770 Shennan E Rd, Cai Wu Wei, Luohu District',
    phone: '755-4939-4147',
    email: 'kars16@icloud.com',
    url: 'http://www.lamhy.org/HouseholdKitchenAppliances',
    staffnum: 67,
    regcapital: 14.9121,
    paidcapital: 215.5018,
    insuranceratio: 42.26,
    isenable: true,
    status_singleselect: '7',
    range_multipleselect: [
      'F3134',
      'I3006',
      'I3007',
      'I3008',
      'I3012',
      'I3014',
      'I3027',
      'I3034',
      'L2095',
      'M2070',
      'P1029',
    ],
    status_radio: '1',
    range_check: ['F3134', 'I3010', 'I3032', 'I3034', 'O3010', 'P1029'],
    establishdate: '2022-08-01T01:51:06.000Z',
  },
  {
    createdAt: '2023-04-28T09:13:50.000Z',
    updatedAt: '2023-05-29T08:08:24.000Z',
    createdById: 6,
    updatedById: 5,
    id: 66,
    orgcode: '440066',
    orgname: '吴技术有限责任公司',
    address: '793 Hongqiao Rd., Xu Hui District',
    phone: '21-0094-0906',
    email: 'yyut@icloud.com',
    url: 'https://video.yeowtszhin.us/Appliances',
    staffnum: 45,
    regcapital: null,
    paidcapital: 76.1281,
    insuranceratio: 76.17,
    isenable: true,
    status_singleselect: '2',
    range_multipleselect: ['F3134', 'I3008', 'I3011', 'I3014', 'I3027', 'I3034', 'L2032', 'O3010'],
    status_radio: '4',
    range_check: ['F3134', 'I3011', 'I3014', 'I3027', 'I3032', 'I3034', 'L2095', 'O3010', 'P1029'],
    establishdate: '2023-09-08T01:51:09.000Z',
  },
  {
    createdAt: '2023-07-11T07:34:49.000Z',
    updatedAt: '2023-07-10T02:25:11.736Z',
    createdById: 5,
    updatedById: null,
    id: 25,
    orgcode: '550025',
    orgname: '赵記发展贸易有限责任公司',
    address: '607 Sanlitun Road, Chaoyang District',
    phone: '144-4751-3753',
    email: null,
    url: 'https://video.kakeungw.net/VideoGames',
    staffnum: 64,
    regcapital: 78.8595,
    paidcapital: 71.565,
    insuranceratio: 58.15,
    isenable: true,
    status_singleselect: '7',
    range_multipleselect: ['F3134', 'I3006', 'I3011', 'I3027', 'I3032', 'L2032', 'L2095'],
    status_radio: '6',
    range_check: ['I3008', 'I3027', 'I3034', 'L2032', 'O3010', 'P1029'],
    establishdate: null,
  },
  {
    createdAt: '2023-05-10T18:09:11.000Z',
    updatedAt: '2023-08-13T01:37:53.000Z',
    createdById: 9,
    updatedById: 1,
    id: 20,
    orgcode: '620020',
    orgname: '岚有限责任公司',
    address: '8 Tremont Road',
    phone: '614-635-9277',
    email: 'salazar1985@gmail.com',
    url: 'https://www.gordemily.com/FilmSupplies',
    staffnum: null,
    regcapital: 219.7301,
    paidcapital: 63.6256,
    insuranceratio: 45.43,
    isenable: null,
    status_singleselect: '8',
    range_multipleselect: ['I3006', 'I3007', 'I3008', 'I3012', 'I3014', 'I3027', 'I3034', 'L2032', 'P1029'],
    status_radio: '8',
    range_check: ['F3134', 'I3006', 'I3011', 'I3014', 'I3027', 'I3032', 'L2095', 'M2070'],
    establishdate: '2022-07-05T10:21:51.000Z',
  },
  {
    createdAt: '2023-03-20T17:13:24.000Z',
    updatedAt: '2023-05-16T04:16:34.000Z',
    createdById: 1,
    updatedById: 6,
    id: 62,
    orgcode: '510062',
    orgname: 'Salazar Food LLC',
    address: '716 Huaxia St, Jinghua Shangquan',
    phone: '198-4847-7122',
    email: 'auwingfat1219@gmail.com',
    url: 'https://www.xielu.us/CellPhonesAccessories',
    staffnum: 131,
    regcapital: 273.1562,
    paidcapital: 287.3437,
    insuranceratio: 76.86,
    isenable: true,
    status_singleselect: '7',
    range_multipleselect: [
      'I3006',
      'I3007',
      'I3008',
      'I3010',
      'I3011',
      'I3012',
      'I3032',
      'L2032',
      'L2095',
      'O3010',
      'P1029',
    ],
    status_radio: '5',
    range_check: [
      'F3134',
      'I3006',
      'I3007',
      'I3011',
      'I3014',
      'I3027',
      'I3034',
      'L2032',
      'L2095',
      'M2070',
      'O3010',
      'P1029',
    ],
    establishdate: '2021-12-14T18:38:12.000Z',
  },
  {
    createdAt: '2023-05-05T06:12:02.000Z',
    updatedAt: '2023-05-04T19:41:58.000Z',
    createdById: 3,
    updatedById: 6,
    id: 31,
    orgcode: '430031',
    orgname: 'Hughes LLC',
    address: '980 4th Section  Renmin South Road, Jinjiang District',
    phone: '147-7853-0142',
    email: 'scao@mail.com',
    url: 'http://image.ikedayu1224.com/Baby',
    staffnum: 135,
    regcapital: 139.2834,
    paidcapital: 173.014,
    insuranceratio: 62.83,
    isenable: true,
    status_singleselect: '2',
    range_multipleselect: ['F3134', 'I3006', 'I3014', 'I3032', 'I3034', 'P1029'],
    status_radio: '2',
    range_check: ['F3134', 'I3006', 'I3008', 'I3010', 'I3034', 'M2070', 'O3010', 'P1029'],
    establishdate: '2023-11-10T02:30:06.000Z',
  },
  {
    createdAt: '2023-05-03T05:56:11.000Z',
    updatedAt: '2023-07-29T02:33:20.000Z',
    createdById: 8,
    updatedById: 4,
    id: 55,
    orgcode: '310055',
    orgname: '睿有限责任公司',
    address: '75 Huaxia St, Jinghua Shangquan',
    phone: '760-789-1994',
    email: 'skudo73@outlook.com',
    url: 'http://image.kenta1.com/ToolsHomeDecoration',
    staffnum: 101,
    regcapital: 168.9348,
    paidcapital: 242.9576,
    insuranceratio: 28.11,
    isenable: true,
    status_singleselect: '8',
    range_multipleselect: ['I3006', 'I3008', 'I3014', 'L2095', 'M2070'],
    status_radio: '8',
    range_check: ['F3134', 'I3006', 'I3007', 'I3008', 'I3012', 'I3014', 'I3034', 'L2095', 'M2070', 'O3010'],
    establishdate: '2021-12-29T21:52:28.000Z',
  },
  {
    createdAt: '2023-08-14T14:48:46.000Z',
    updatedAt: '2023-08-08T22:23:16.000Z',
    createdById: 5,
    updatedById: 9,
    id: 84,
    orgcode: '530084',
    orgname: '璐有限责任公司',
    address: '32 Jiangnan West Road, Haizhu District',
    phone: '20-611-5899',
    email: 'kffan@gmail.com',
    url: 'http://auth.nakayama40.jp/Others',
    staffnum: 27,
    regcapital: 211.2634,
    paidcapital: 251.2448,
    insuranceratio: 8.95,
    isenable: true,
    status_singleselect: '3',
    range_multipleselect: ['F3134', 'I3006', 'I3008', 'I3027', 'I3032', 'P1029'],
    status_radio: '5',
    range_check: ['I3006', 'I3008', 'I3012', 'L2095', 'M2070'],
    establishdate: '2022-12-20T04:42:54.000Z',
  },
  {
    createdAt: '2023-06-24T08:12:11.000Z',
    updatedAt: '2023-07-10T02:25:11.743Z',
    createdById: 8,
    updatedById: null,
    id: 89,
    orgcode: '640089',
    orgname: 'Curtis Pharmaceutical Inc.',
    address: null,
    phone: '179-9231-4455',
    email: 'aoi110@icloud.com',
    url: 'https://www.yuziyi.co.jp/ToolsHomeDecoration',
    staffnum: 119,
    regcapital: 196.5298,
    paidcapital: 195.5359,
    insuranceratio: null,
    isenable: null,
    status_singleselect: '4',
    range_multipleselect: ['F3134', 'I3012', 'I3014', 'I3027', 'L2095', 'O3010', 'P1029'],
    status_radio: '4',
    range_check: ['I3006', 'I3008', 'I3010', 'I3011', 'I3014', 'I3027', 'L2032', 'M2070'],
    establishdate: '2023-10-08T21:08:37.000Z',
  },
  {
    createdAt: '2023-08-20T12:48:08.000Z',
    updatedAt: '2023-06-13T11:27:58.000Z',
    createdById: 7,
    updatedById: 5,
    id: 44,
    orgcode: '410044',
    orgname: 'Lee Brothers Inc.',
    address: '成华区双庆路300号',
    phone: null,
    email: 'tajiehong602@outlook.com',
    url: 'http://image.tonkay9.info/Baby',
    staffnum: 176,
    regcapital: 297.447,
    paidcapital: 16.0008,
    insuranceratio: 69.5,
    isenable: true,
    status_singleselect: '4',
    range_multipleselect: ['F3134', 'I3007', 'I3011', 'I3014', 'I3034', 'M2070'],
    status_radio: '3',
    range_check: ['F3134', 'I3006', 'I3010', 'I3027', 'I3034', 'L2032', 'O3010'],
    establishdate: '2023-01-04T12:48:43.000Z',
  },
  {
    createdAt: '2023-06-30T09:53:02.000Z',
    updatedAt: '2023-07-18T22:24:59.000Z',
    createdById: 3,
    updatedById: 4,
    id: 56,
    orgcode: '210056',
    orgname: 'Lopez Brothers Technology LLC',
    address: '延庆区028县道953号',
    phone: '10-641-1187',
    email: 'naks@hotmail.com',
    url: 'https://image.guzh.info/CenturionGardenOutdoor',
    staffnum: 185,
    regcapital: 63.5178,
    paidcapital: 153.6774,
    insuranceratio: 91.75,
    isenable: true,
    status_singleselect: '3',
    range_multipleselect: ['I3008', 'I3010', 'I3012', 'I3014', 'I3034', 'M2070', 'P1029'],
    status_radio: '4',
    range_check: ['I3008', 'I3011', 'L2032', 'M2070', 'P1029'],
    establishdate: '2021-05-21T11:02:59.000Z',
  },
  {
    createdAt: '2023-03-10T11:17:24.000Z',
    updatedAt: '2023-07-25T07:52:00.000Z',
    createdById: 3,
    updatedById: 4,
    id: 35,
    orgcode: '150035',
    orgname: '邵記系统有限责任公司',
    address: '209 1st Ave',
    phone: '718-246-6197',
    email: 'akat@hotmail.com',
    url: 'http://video.fuchungyin1009.co.jp/ArtsHandicraftsSewing',
    staffnum: 185,
    regcapital: 262.7247,
    paidcapital: 299.6833,
    insuranceratio: 45.48,
    isenable: null,
    status_singleselect: '1',
    range_multipleselect: ['F3134', 'I3007', 'I3014', 'I3027', 'I3032', 'I3034', 'L2032', 'M2070', 'O3010'],
    status_radio: '2',
    range_check: ['I3006', 'I3007', 'I3010', 'I3032', 'I3034', 'M2070', 'P1029'],
    establishdate: '2022-06-04T09:44:46.000Z',
  },
  {
    createdAt: '2023-05-22T02:10:55.000Z',
    updatedAt: '2023-07-19T22:44:41.000Z',
    createdById: 9,
    updatedById: 3,
    id: 4,
    orgcode: '430004',
    orgname: '宇宁制药有限责任公司',
    address: '328 Jingtian East 1st St, Futian District',
    phone: '755-3659-2323',
    email: 'cmsi92@icloud.com',
    url: 'http://www.czhennan4.biz/ToolsHomeDecoration',
    staffnum: 132,
    regcapital: 175.7828,
    paidcapital: 290.7203,
    insuranceratio: 45.74,
    isenable: true,
    status_singleselect: '8',
    range_multipleselect: ['I3006', 'I3007', 'I3008', 'I3010', 'I3011', 'I3012', 'I3027', 'M2070'],
    status_radio: '7',
    range_check: ['F3134', 'I3006', 'I3007', 'I3012', 'I3014', 'I3032', 'L2095', 'P1029'],
    establishdate: '2021-01-08T16:46:38.000Z',
  },
  {
    createdAt: '2023-06-15T13:47:48.000Z',
    updatedAt: '2023-05-20T12:37:39.000Z',
    createdById: 0,
    updatedById: 4,
    id: 34,
    orgcode: '210034',
    orgname: '董記电子有限责任公司',
    address: '265 Huaxia St, Jinghua Shangquan',
    phone: null,
    email: 'rivashle1114@gmail.com',
    url: 'http://auth.takeda1.cn/Handcrafts',
    staffnum: 176,
    regcapital: 281.1833,
    paidcapital: 67.1949,
    insuranceratio: 29.93,
    isenable: true,
    status_singleselect: '4',
    range_multipleselect: ['F3134', 'I3007', 'I3010', 'I3012', 'I3027', 'I3034', 'L2032', 'M2070', 'O3010', 'P1029'],
    status_radio: '2',
    range_check: ['F3134', 'I3006', 'I3007', 'I3011', 'I3012', 'I3014', 'L2095', 'O3010'],
    establishdate: '2023-02-08T16:44:29.000Z',
  },
  {
    createdAt: '2023-03-08T16:04:01.000Z',
    updatedAt: '2023-05-05T22:57:27.000Z',
    createdById: 4,
    updatedById: 3,
    id: 81,
    orgcode: '110081',
    orgname: '子异有限责任公司',
    address: '229 Rush Street',
    phone: '312-600-3390',
    email: 'lokwy@icloud.com',
    url: 'https://image.anakagawa.us/MusicalInstrument',
    staffnum: 26,
    regcapital: null,
    paidcapital: 186.0802,
    insuranceratio: 18.24,
    isenable: true,
    status_singleselect: '2',
    range_multipleselect: ['I3006', 'I3007', 'I3008', 'I3012', 'I3014', 'I3032', 'L2032', 'L2095', 'M2070', 'O3010'],
    status_radio: '5',
    range_check: ['F3134', 'I3006', 'I3007', 'I3008', 'I3012', 'I3027', 'L2032', 'O3010'],
    establishdate: '2021-04-08T05:24:21.000Z',
  },
  {
    createdAt: '2023-08-04T08:58:50.000Z',
    updatedAt: '2023-08-04T04:34:11.000Z',
    createdById: 9,
    updatedById: 8,
    id: 87,
    orgcode: '420087',
    orgname: '史記物业代理有限责任公司',
    address: '549 Ridgewood Road',
    phone: '330-982-5220',
    email: 'maruyamashi@hotmail.com',
    url: 'https://image.kondohik1.co.jp/ToysGames',
    staffnum: 126,
    regcapital: 227.7387,
    paidcapital: 139.9423,
    insuranceratio: 80.19,
    isenable: true,
    status_singleselect: '5',
    range_multipleselect: ['I3008', 'I3010', 'I3011', 'I3027', 'I3034', 'P1029'],
    status_radio: '3',
    range_check: ['I3006', 'I3010', 'I3014', 'I3032', 'I3034', 'M2070', 'O3010'],
    establishdate: '2023-04-08T00:21:42.000Z',
  },
  {
    createdAt: '2023-06-17T22:39:01.000Z',
    updatedAt: '2023-05-12T07:34:03.000Z',
    createdById: 0,
    updatedById: 7,
    id: 65,
    orgcode: '250065',
    orgname: '林有限责任公司',
    address: '595 3rd Section Hongxing Road, Jinjiang District',
    phone: '147-2716-7825',
    email: 'kathy09@gmail.com',
    url: 'http://auth.shenj.net/AppsGames',
    staffnum: 146,
    regcapital: 63.0539,
    paidcapital: 18.8649,
    insuranceratio: 0.22,
    isenable: true,
    status_singleselect: '2',
    range_multipleselect: ['I3008', 'I3011', 'I3012', 'I3027', 'L2032', 'L2095', 'M2070', 'P1029'],
    status_radio: '1',
    range_check: ['F3134', 'I3006', 'I3007', 'I3008', 'I3011', 'I3027', 'I3032', 'L2032', 'L2095'],
    establishdate: '2023-08-06T08:03:27.000Z',
  },
];
export default module.exports = {
  appendJsonCollectionName,
  builtin_General,
  builtin_File,
  builtin_Expression,
  e2e_GeneralFormsTable,
  generateRandomLetters,
  e2e_GeneralFormsTableData,
};
