export {
  AGENT_LAYER_PREFIX,
  agentLayer,
  annotatePlaceholders,
  onlineSkillsSection,
  onlineSystemLayer,
  onlineToolRules,
  CITATION_RULE,
  DEFAULT_GUIDANCE,
  environmentSection,
  firstTurn,
  joinBrief,
  renderBrief,
  renderInput,
  renderTurnPrompt,
  skillsSection,
  systemLayer,
  workspaceSection,
  type Brief,
  type BriefGuidance,
  type BriefInput,
  type BriefSkill,
} from './brief.js';
