import { PageConfig, generalWithBasic, generalWithChoices } from '@nocobase/test/client';

export const twoTableWithSameCollection: PageConfig = {
  pageSchema: {
    _isJSONSchemaObject: true,
    version: '2.0',
    type: 'void',
    'x-component': 'Page',
    properties: {
      aagn23cu1au: {
        _isJSONSchemaObject: true,
        version: '2.0',
        type: 'void',
        'x-component': 'Grid',
        'x-initializer': 'BlockInitializers',
        properties: {
          jkcte869qpa: {
            _isJSONSchemaObject: true,
            version: '2.0',
            type: 'void',
            'x-component': 'Grid.Row',
            properties: {
              a7mg35xwgnh: {
                'x-uid': 'j92fu6vu5wr',
                _isJSONSchemaObject: true,
                version: '2.0',
                type: 'void',
                'x-component': 'Grid.Col',
                'x-component-props': {
                  width: 50,
                },
                properties: {
                  ik3kd1mu356: {
                    _isJSONSchemaObject: true,
                    version: '2.0',
                    type: 'void',
                    'x-decorator': 'TableBlockProvider',
                    'x-acl-action': 'users:list',
                    'x-decorator-props': {
                      collection: 'users',
                      resource: 'users',
                      action: 'list',
                      params: {
                        pageSize: 20,
                      },
                      rowKey: 'id',
                      showIndex: true,
                      dragSort: false,
                      disableTemplate: false,
                    },
                    'x-designer': 'TableBlockDesigner',
                    'x-component': 'CardItem',
                    'x-filter-targets': [],
                    properties: {
                      actions: {
                        _isJSONSchemaObject: true,
                        version: '2.0',
                        type: 'void',
                        'x-initializer': 'TableActionInitializers',
                        'x-component': 'ActionBar',
                        'x-component-props': {
                          style: {
                            marginBottom: 'var(--nb-spacing)',
                          },
                        },
                        'x-uid': 'xbzkjfayl3y',
                        'x-async': false,
                        'x-index': 1,
                      },
                      '6rht663sjwy': {
                        _isJSONSchemaObject: true,
                        version: '2.0',
                        type: 'array',
                        'x-initializer': 'TableColumnInitializers',
                        'x-component': 'TableV2',
                        'x-component-props': {
                          rowKey: 'id',
                          rowSelection: {
                            type: 'checkbox',
                          },
                          useProps: '{{ useTableBlockProps }}',
                        },
                        properties: {
                          '1rdl2om3xvf': {
                            _isJSONSchemaObject: true,
                            version: '2.0',
                            type: 'void',
                            'x-decorator': 'TableV2.Column.Decorator',
                            'x-designer': 'TableV2.Column.Designer',
                            'x-component': 'TableV2.Column',
                            properties: {
                              nickname: {
                                _isJSONSchemaObject: true,
                                version: '2.0',
                                'x-collection-field': 'users.nickname',
                                'x-component': 'CollectionField',
                                'x-component-props': {
                                  ellipsis: true,
                                },
                                'x-read-pretty': true,
                                'x-decorator': null,
                                'x-decorator-props': {
                                  labelStyle: {
                                    display: 'none',
                                  },
                                },
                                'x-uid': 'awsapwb3vz8',
                                'x-async': false,
                                'x-index': 1,
                              },
                            },
                            'x-uid': '63je0mdriu0',
                            'x-async': false,
                            'x-index': 2,
                          },
                        },
                        'x-uid': 'xok38mlx47f',
                        'x-async': false,
                        'x-index': 2,
                      },
                    },
                    'x-uid': 'w67kx2dq7v0',
                    'x-async': false,
                    'x-index': 1,
                  },
                },
                'x-async': false,
                'x-index': 1,
              },
              col_8aw7x1sak31: {
                'x-uid': 'aih69lrjd2p',
                _isJSONSchemaObject: true,
                version: '2.0',
                type: 'void',
                'x-component': 'Grid.Col',
                'x-index': 2,
                'x-component-props': {
                  width: 50,
                },
                properties: {
                  md8bjznxwkj: {
                    _isJSONSchemaObject: true,
                    version: '2.0',
                    type: 'void',
                    'x-decorator': 'TableBlockProvider',
                    'x-acl-action': 'users:list',
                    'x-decorator-props': {
                      collection: 'users',
                      resource: 'users',
                      action: 'list',
                      params: {
                        pageSize: 20,
                      },
                      rowKey: 'id',
                      showIndex: true,
                      dragSort: false,
                      disableTemplate: false,
                    },
                    'x-designer': 'TableBlockDesigner',
                    'x-component': 'CardItem',
                    'x-filter-targets': [],
                    properties: {
                      actions: {
                        _isJSONSchemaObject: true,
                        version: '2.0',
                        type: 'void',
                        'x-initializer': 'TableActionInitializers',
                        'x-component': 'ActionBar',
                        'x-component-props': {
                          style: {
                            marginBottom: 'var(--nb-spacing)',
                          },
                        },
                        'x-uid': '5g15rd6dqli',
                        'x-async': false,
                        'x-index': 1,
                      },
                      '5jpkhgs6y9l': {
                        _isJSONSchemaObject: true,
                        version: '2.0',
                        type: 'array',
                        'x-initializer': 'TableColumnInitializers',
                        'x-component': 'TableV2',
                        'x-component-props': {
                          rowKey: 'id',
                          rowSelection: {
                            type: 'checkbox',
                          },
                          useProps: '{{ useTableBlockProps }}',
                        },
                        properties: {
                          wx9rc0ypdic: {
                            _isJSONSchemaObject: true,
                            version: '2.0',
                            type: 'void',
                            'x-decorator': 'TableV2.Column.Decorator',
                            'x-designer': 'TableV2.Column.Designer',
                            'x-component': 'TableV2.Column',
                            properties: {
                              nickname: {
                                _isJSONSchemaObject: true,
                                version: '2.0',
                                'x-collection-field': 'users.nickname',
                                'x-component': 'CollectionField',
                                'x-component-props': {
                                  ellipsis: true,
                                },
                                'x-read-pretty': true,
                                'x-decorator': null,
                                'x-decorator-props': {
                                  labelStyle: {
                                    display: 'none',
                                  },
                                },
                                'x-uid': 'iz76f2zk0p3',
                                'x-async': false,
                                'x-index': 1,
                              },
                            },
                            'x-uid': '6l713p7h6a6',
                            'x-async': false,
                            'x-index': 2,
                          },
                        },
                        'x-uid': 'qtnr055ay8q',
                        'x-async': false,
                        'x-index': 2,
                      },
                    },
                    'x-uid': 'bvl6hoot8p7',
                    'x-async': false,
                    'x-index': 1,
                  },
                },
                'x-async': false,
              },
            },
            'x-uid': '5y30ooo4yb9',
            'x-async': false,
            'x-index': 1,
          },
          zhjry50iany: {
            _isJSONSchemaObject: true,
            version: '2.0',
            type: 'void',
            'x-component': 'Grid.Row',
            'x-uid': 'bqakvev9voh',
            'x-async': false,
            'x-index': 2,
          },
        },
        'x-uid': 'y2lcuhlc22c',
        'x-async': false,
        'x-index': 1,
      },
    },
    'x-uid': 'vfw1o87k9dl',
    'x-async': true,
    'x-index': 1,
  },
};

export const twoTableWithRelationalFields: PageConfig = {
  pageSchema: {
    _isJSONSchemaObject: true,
    version: '2.0',
    type: 'void',
    'x-component': 'Page',
    properties: {
      mkihga8zgdc: {
        _isJSONSchemaObject: true,
        version: '2.0',
        type: 'void',
        'x-component': 'Grid',
        'x-initializer': 'BlockInitializers',
        properties: {
          qtp19qlje2y: {
            _isJSONSchemaObject: true,
            version: '2.0',
            type: 'void',
            'x-component': 'Grid.Row',
            properties: {
              bpjhe7vhk0q: {
                'x-uid': 'g3gmsg8dgvi',
                _isJSONSchemaObject: true,
                version: '2.0',
                type: 'void',
                'x-component': 'Grid.Col',
                'x-component-props': {
                  width: 50,
                },
                properties: {
                  q29lyxxnoqt: {
                    'x-uid': 'xq1rnptcf7a',
                    _isJSONSchemaObject: true,
                    version: '2.0',
                    type: 'void',
                    'x-decorator': 'TableBlockProvider',
                    'x-acl-action': 'roles:list',
                    'x-decorator-props': {
                      collection: 'roles',
                      resource: 'roles',
                      action: 'list',
                      params: {
                        pageSize: 20,
                      },
                      rowKey: 'name',
                      showIndex: true,
                      dragSort: false,
                      disableTemplate: false,
                    },
                    'x-designer': 'TableBlockDesigner',
                    'x-component': 'CardItem',
                    'x-filter-targets': [],
                    properties: {
                      actions: {
                        _isJSONSchemaObject: true,
                        version: '2.0',
                        type: 'void',
                        'x-initializer': 'TableActionInitializers',
                        'x-component': 'ActionBar',
                        'x-component-props': {
                          style: {
                            marginBottom: 'var(--nb-spacing)',
                          },
                        },
                        'x-uid': 'u8xfso0a35t',
                        'x-async': false,
                        'x-index': 1,
                      },
                      ev414dhhdkt: {
                        _isJSONSchemaObject: true,
                        version: '2.0',
                        type: 'array',
                        'x-initializer': 'TableColumnInitializers',
                        'x-component': 'TableV2',
                        'x-component-props': {
                          rowKey: 'id',
                          rowSelection: {
                            type: 'checkbox',
                          },
                          useProps: '{{ useTableBlockProps }}',
                        },
                        properties: {
                          t23whe7t7tm: {
                            _isJSONSchemaObject: true,
                            version: '2.0',
                            type: 'void',
                            'x-decorator': 'TableV2.Column.Decorator',
                            'x-designer': 'TableV2.Column.Designer',
                            'x-component': 'TableV2.Column',
                            properties: {
                              title: {
                                _isJSONSchemaObject: true,
                                version: '2.0',
                                'x-collection-field': 'roles.title',
                                'x-component': 'CollectionField',
                                'x-component-props': {
                                  ellipsis: true,
                                },
                                'x-read-pretty': true,
                                'x-decorator': null,
                                'x-decorator-props': {
                                  labelStyle: {
                                    display: 'none',
                                  },
                                },
                                'x-uid': '5jl8zmnh38i',
                                'x-async': false,
                                'x-index': 1,
                              },
                            },
                            'x-uid': '9y1uck15r14',
                            'x-async': false,
                            'x-index': 2,
                          },
                        },
                        'x-uid': 'l7wpauy51gd',
                        'x-async': false,
                        'x-index': 2,
                      },
                    },
                    'x-async': false,
                    'x-index': 1,
                  },
                },
                'x-async': false,
                'x-index': 1,
              },
              col_2fu9sdcu99u: {
                'x-uid': 'q1snbst31eh',
                _isJSONSchemaObject: true,
                version: '2.0',
                type: 'void',
                'x-component': 'Grid.Col',
                'x-index': 2,
                'x-component-props': {
                  width: 50,
                },
                properties: {
                  ifxs1ltyzyu: {
                    _isJSONSchemaObject: true,
                    version: '2.0',
                    type: 'void',
                    'x-decorator': 'TableBlockProvider',
                    'x-acl-action': 'users:list',
                    'x-decorator-props': {
                      collection: 'users',
                      resource: 'users',
                      action: 'list',
                      params: {
                        pageSize: 20,
                      },
                      rowKey: 'id',
                      showIndex: true,
                      dragSort: false,
                      disableTemplate: false,
                    },
                    'x-designer': 'TableBlockDesigner',
                    'x-component': 'CardItem',
                    'x-filter-targets': [],
                    properties: {
                      actions: {
                        _isJSONSchemaObject: true,
                        version: '2.0',
                        type: 'void',
                        'x-initializer': 'TableActionInitializers',
                        'x-component': 'ActionBar',
                        'x-component-props': {
                          style: {
                            marginBottom: 'var(--nb-spacing)',
                          },
                        },
                        'x-uid': 'oqdv3tu3laz',
                        'x-async': false,
                        'x-index': 1,
                      },
                      wyykccq1j91: {
                        _isJSONSchemaObject: true,
                        version: '2.0',
                        type: 'array',
                        'x-initializer': 'TableColumnInitializers',
                        'x-component': 'TableV2',
                        'x-component-props': {
                          rowKey: 'id',
                          rowSelection: {
                            type: 'checkbox',
                          },
                          useProps: '{{ useTableBlockProps }}',
                        },
                        properties: {
                          '4k1roap63h2': {
                            _isJSONSchemaObject: true,
                            version: '2.0',
                            type: 'void',
                            'x-decorator': 'TableV2.Column.Decorator',
                            'x-designer': 'TableV2.Column.Designer',
                            'x-component': 'TableV2.Column',
                            properties: {
                              roles: {
                                _isJSONSchemaObject: true,
                                version: '2.0',
                                'x-collection-field': 'users.roles',
                                'x-component': 'CollectionField',
                                'x-component-props': {
                                  ellipsis: true,
                                  size: 'small',
                                },
                                'x-read-pretty': true,
                                'x-decorator': null,
                                'x-decorator-props': {
                                  labelStyle: {
                                    display: 'none',
                                  },
                                },
                                'x-uid': '9jgtp03g8pi',
                                'x-async': false,
                                'x-index': 1,
                              },
                            },
                            'x-uid': 'qrdojan2b5g',
                            'x-async': false,
                            'x-index': 2,
                          },
                        },
                        'x-uid': 'abdcpql91wn',
                        'x-async': false,
                        'x-index': 2,
                      },
                    },
                    'x-uid': '5el8hue6945',
                    'x-async': false,
                    'x-index': 1,
                  },
                },
                'x-async': false,
              },
            },
            'x-uid': 'pmexhqiaq52',
            'x-async': false,
            'x-index': 1,
          },
          ef6epohn0yr: {
            _isJSONSchemaObject: true,
            version: '2.0',
            type: 'void',
            'x-component': 'Grid.Row',
            'x-uid': 'u7cdjkdpztt',
            'x-async': false,
            'x-index': 2,
          },
        },
        'x-uid': 'epjhxs40qys',
        'x-async': false,
        'x-index': 1,
      },
    },
    'x-uid': 'anxt1ecq7hd',
    'x-async': true,
    'x-index': 1,
  },
};

export const twoTableWithForeignKey: PageConfig = {};

export const oneFormAndOneTableWithSameCollection: PageConfig = {
  collections: generalWithBasic,
  pageSchema: {
    _isJSONSchemaObject: true,
    version: '2.0',
    type: 'void',
    'x-component': 'Page',
    properties: {
      k4rw21d8npm: {
        _isJSONSchemaObject: true,
        version: '2.0',
        type: 'void',
        'x-component': 'Grid',
        'x-initializer': 'BlockInitializers',
        properties: {
          '0qplm51g52v': {
            _isJSONSchemaObject: true,
            version: '2.0',
            type: 'void',
            'x-component': 'Grid.Row',
            properties: {
              '6k1kp63fe39': {
                _isJSONSchemaObject: true,
                version: '2.0',
                type: 'void',
                'x-component': 'Grid.Col',
                properties: {
                  '4bvs0awu4x3': {
                    _isJSONSchemaObject: true,
                    version: '2.0',
                    type: 'void',
                    'x-decorator': 'FilterFormBlockProvider',
                    'x-decorator-props': {
                      resource: 'general',
                      collection: 'general',
                    },
                    'x-designer': 'FormV2.FilterDesigner',
                    'x-component': 'CardItem',
                    'x-filter-targets': [],
                    'x-filter-operators': {},
                    properties: {
                      wsmj61aszlz: {
                        _isJSONSchemaObject: true,
                        version: '2.0',
                        type: 'void',
                        'x-component': 'FormV2',
                        'x-component-props': {
                          useProps: '{{ useFormBlockProps }}',
                        },
                        properties: {
                          grid: {
                            _isJSONSchemaObject: true,
                            version: '2.0',
                            type: 'void',
                            'x-component': 'Grid',
                            'x-initializer': 'FilterFormItemInitializers',
                            properties: {
                              '0k8y0nlffht': {
                                _isJSONSchemaObject: true,
                                version: '2.0',
                                type: 'void',
                                'x-component': 'Grid.Row',
                                properties: {
                                  qse6oj6e5qu: {
                                    _isJSONSchemaObject: true,
                                    version: '2.0',
                                    type: 'void',
                                    'x-component': 'Grid.Col',
                                    properties: {
                                      singleLineText: {
                                        _isJSONSchemaObject: true,
                                        version: '2.0',
                                        type: 'string',
                                        required: false,
                                        'x-designer': 'FormItem.FilterFormDesigner',
                                        'x-component': 'CollectionField',
                                        'x-decorator': 'FormItem',
                                        'x-collection-field': 'general.singleLineText',
                                        'x-component-props': {},
                                        'x-uid': 'axtueywbsku',
                                        'x-async': false,
                                        'x-index': 1,
                                      },
                                    },
                                    'x-uid': 'ghq5xu4u9q1',
                                    'x-async': false,
                                    'x-index': 1,
                                  },
                                },
                                'x-uid': 'yo9rhg3o491',
                                'x-async': false,
                                'x-index': 1,
                              },
                            },
                            'x-uid': 'u14kmr18s8n',
                            'x-async': false,
                            'x-index': 1,
                          },
                          actions: {
                            _isJSONSchemaObject: true,
                            version: '2.0',
                            type: 'void',
                            'x-initializer': 'FilterFormActionInitializers',
                            'x-component': 'ActionBar',
                            'x-component-props': {
                              layout: 'one-column',
                              style: {
                                float: 'right',
                              },
                            },
                            properties: {
                              '52ugkxvnymm': {
                                _isJSONSchemaObject: true,
                                version: '2.0',
                                title: '{{ t("Filter records") }}',
                                'x-action': 'submit',
                                'x-component': 'Action',
                                'x-designer': 'Action.Designer',
                                'x-component-props': {
                                  type: 'primary',
                                  useProps: '{{ useFilterBlockActionProps }}',
                                },
                                'x-action-settings': {},
                                type: 'void',
                                'x-uid': 'x9zwb21282b',
                                'x-async': false,
                                'x-index': 1,
                              },
                              ro85kbfk3ch: {
                                _isJSONSchemaObject: true,
                                version: '2.0',
                                title: '{{ t("Reset records") }}',
                                'x-component': 'Action',
                                'x-designer': 'Action.Designer',
                                'x-component-props': {
                                  useProps: '{{ useResetBlockActionProps }}',
                                },
                                'x-action-settings': {},
                                type: 'void',
                                'x-uid': 'yx5r6w259pn',
                                'x-async': false,
                                'x-index': 2,
                              },
                            },
                            'x-uid': 'fhd3bmfdv2l',
                            'x-async': false,
                            'x-index': 2,
                          },
                        },
                        'x-uid': 'hhu6h4smxk3',
                        'x-async': false,
                        'x-index': 1,
                      },
                    },
                    'x-uid': 'mwvcvngofcs',
                    'x-async': false,
                    'x-index': 1,
                  },
                },
                'x-uid': 'la5zbsnj43i',
                'x-async': false,
                'x-index': 1,
              },
            },
            'x-uid': 'cmb5v9n7hs5',
            'x-async': false,
            'x-index': 1,
          },
          ao49un8ae53: {
            _isJSONSchemaObject: true,
            version: '2.0',
            type: 'void',
            'x-component': 'Grid.Row',
            properties: {
              '6ozy0fovblc': {
                _isJSONSchemaObject: true,
                version: '2.0',
                type: 'void',
                'x-component': 'Grid.Col',
                properties: {
                  qqm3k28nlvw: {
                    _isJSONSchemaObject: true,
                    version: '2.0',
                    type: 'void',
                    'x-decorator': 'TableBlockProvider',
                    'x-acl-action': 'general:list',
                    'x-decorator-props': {
                      collection: 'general',
                      resource: 'general',
                      action: 'list',
                      params: {
                        pageSize: 20,
                      },
                      rowKey: 'id',
                      showIndex: true,
                      dragSort: false,
                      disableTemplate: false,
                    },
                    'x-designer': 'TableBlockDesigner',
                    'x-component': 'CardItem',
                    'x-filter-targets': [],
                    properties: {
                      actions: {
                        _isJSONSchemaObject: true,
                        version: '2.0',
                        type: 'void',
                        'x-initializer': 'TableActionInitializers',
                        'x-component': 'ActionBar',
                        'x-component-props': {
                          style: {
                            marginBottom: 'var(--nb-spacing)',
                          },
                        },
                        'x-uid': 'jd5cfyt9rvc',
                        'x-async': false,
                        'x-index': 1,
                      },
                      q50obbdn5ss: {
                        _isJSONSchemaObject: true,
                        version: '2.0',
                        type: 'array',
                        'x-initializer': 'TableColumnInitializers',
                        'x-component': 'TableV2',
                        'x-component-props': {
                          rowKey: 'id',
                          rowSelection: {
                            type: 'checkbox',
                          },
                          useProps: '{{ useTableBlockProps }}',
                        },
                        properties: {
                          xx80bo2vwzo: {
                            _isJSONSchemaObject: true,
                            version: '2.0',
                            type: 'void',
                            'x-decorator': 'TableV2.Column.Decorator',
                            'x-designer': 'TableV2.Column.Designer',
                            'x-component': 'TableV2.Column',
                            properties: {
                              singleLineText: {
                                _isJSONSchemaObject: true,
                                version: '2.0',
                                'x-collection-field': 'general.singleLineText',
                                'x-component': 'CollectionField',
                                'x-component-props': {
                                  ellipsis: true,
                                },
                                'x-read-pretty': true,
                                'x-decorator': null,
                                'x-decorator-props': {
                                  labelStyle: {
                                    display: 'none',
                                  },
                                },
                                'x-uid': '4abuynayx5p',
                                'x-async': false,
                                'x-index': 1,
                              },
                            },
                            'x-uid': 'svmhhffy26k',
                            'x-async': false,
                            'x-index': 1,
                          },
                        },
                        'x-uid': 'tnfoksv58jo',
                        'x-async': false,
                        'x-index': 2,
                      },
                    },
                    'x-uid': '89u71juhrim',
                    'x-async': false,
                    'x-index': 1,
                  },
                },
                'x-uid': '79f1735ed66',
                'x-async': false,
                'x-index': 1,
              },
            },
            'x-uid': '1jlx589r5yi',
            'x-async': false,
            'x-index': 2,
          },
        },
        'x-uid': 'wygph7l04pt',
        'x-async': false,
        'x-index': 1,
      },
    },
    'x-uid': 'hkp8w48hfxt',
    'x-async': true,
    'x-index': 1,
  },
};

export const oneCollapseAndOneTableWithSameCollection: PageConfig = {
  collections: generalWithChoices,
  pageSchema: {
    _isJSONSchemaObject: true,
    version: '2.0',
    type: 'void',
    'x-component': 'Page',
    properties: {
      jxgbx92czdd: {
        _isJSONSchemaObject: true,
        version: '2.0',
        type: 'void',
        'x-component': 'Grid',
        'x-initializer': 'BlockInitializers',
        properties: {
          xxnsq3r1w5u: {
            _isJSONSchemaObject: true,
            version: '2.0',
            type: 'void',
            'x-component': 'Grid.Row',
            properties: {
              o5ulrlifkhp: {
                _isJSONSchemaObject: true,
                version: '2.0',
                type: 'void',
                'x-component': 'Grid.Col',
                properties: {
                  x0iipsghykq: {
                    'x-uid': '325t1dnvyoa',
                    _isJSONSchemaObject: true,
                    version: '2.0',
                    type: 'void',
                    'x-decorator': 'AssociationFilter.Provider',
                    'x-decorator-props': {
                      collection: 'general',
                      blockType: 'filter',
                      associationFilterStyle: {
                        width: '100%',
                      },
                      name: 'filter-collapse',
                    },
                    'x-designer': 'AssociationFilter.BlockDesigner',
                    'x-component': 'CardItem',
                    'x-filter-targets': [],
                    properties: {
                      lsilk6r7192: {
                        _isJSONSchemaObject: true,
                        version: '2.0',
                        type: 'void',
                        'x-action': 'associateFilter',
                        'x-initializer': 'AssociationFilter.FilterBlockInitializer',
                        'x-component': 'AssociationFilter',
                        properties: {
                          singleSelect: {
                            _isJSONSchemaObject: true,
                            version: '2.0',
                            title: 'singleSelect',
                            interface: 'select',
                            type: 'void',
                            'x-designer': 'AssociationFilter.Item.Designer',
                            'x-component': 'AssociationFilter.Item',
                            'x-component-props': {
                              fieldNames: {
                                label: 'singleSelect',
                              },
                              useProps: '{{useAssociationFilterBlockProps}}',
                            },
                            'x-uid': 'o4wigvr1cxo',
                            'x-async': false,
                            'x-index': 1,
                          },
                        },
                        'x-uid': 'f8lk8ibhgrm',
                        'x-async': false,
                        'x-index': 1,
                      },
                    },
                    'x-async': false,
                    'x-index': 1,
                  },
                },
                'x-uid': 'xk98n4xjp10',
                'x-async': false,
                'x-index': 1,
              },
            },
            'x-uid': 'cijnohur32y',
            'x-async': false,
            'x-index': 1,
          },
          r1dqoqzo9xk: {
            _isJSONSchemaObject: true,
            version: '2.0',
            type: 'void',
            'x-component': 'Grid.Row',
            properties: {
              xd8oyouhi1g: {
                _isJSONSchemaObject: true,
                version: '2.0',
                type: 'void',
                'x-component': 'Grid.Col',
                properties: {
                  e0pa953qo00: {
                    _isJSONSchemaObject: true,
                    version: '2.0',
                    type: 'void',
                    'x-decorator': 'TableBlockProvider',
                    'x-acl-action': 'general:list',
                    'x-decorator-props': {
                      collection: 'general',
                      resource: 'general',
                      action: 'list',
                      params: {
                        pageSize: 20,
                      },
                      rowKey: 'id',
                      showIndex: true,
                      dragSort: false,
                      disableTemplate: false,
                    },
                    'x-designer': 'TableBlockDesigner',
                    'x-component': 'CardItem',
                    'x-filter-targets': [],
                    properties: {
                      actions: {
                        _isJSONSchemaObject: true,
                        version: '2.0',
                        type: 'void',
                        'x-initializer': 'TableActionInitializers',
                        'x-component': 'ActionBar',
                        'x-component-props': {
                          style: {
                            marginBottom: 'var(--nb-spacing)',
                          },
                        },
                        'x-uid': 'nq51lizkoo4',
                        'x-async': false,
                        'x-index': 1,
                      },
                      xodu4re5kqd: {
                        _isJSONSchemaObject: true,
                        version: '2.0',
                        type: 'array',
                        'x-initializer': 'TableColumnInitializers',
                        'x-component': 'TableV2',
                        'x-component-props': {
                          rowKey: 'id',
                          rowSelection: {
                            type: 'checkbox',
                          },
                          useProps: '{{ useTableBlockProps }}',
                        },
                        properties: {
                          rwf529x2vds: {
                            _isJSONSchemaObject: true,
                            version: '2.0',
                            type: 'void',
                            'x-decorator': 'TableV2.Column.Decorator',
                            'x-designer': 'TableV2.Column.Designer',
                            'x-component': 'TableV2.Column',
                            properties: {
                              singleSelect: {
                                _isJSONSchemaObject: true,
                                version: '2.0',
                                'x-collection-field': 'general.singleSelect',
                                'x-component': 'CollectionField',
                                'x-component-props': {
                                  style: {
                                    width: '100%',
                                  },
                                  ellipsis: true,
                                },
                                'x-read-pretty': true,
                                'x-decorator': null,
                                'x-decorator-props': {
                                  labelStyle: {
                                    display: 'none',
                                  },
                                },
                                'x-uid': 'e270d5dgyps',
                                'x-async': false,
                                'x-index': 1,
                              },
                            },
                            'x-uid': 'xdamueag38i',
                            'x-async': false,
                            'x-index': 1,
                          },
                        },
                        'x-uid': 'pcys8enhlel',
                        'x-async': false,
                        'x-index': 2,
                      },
                    },
                    'x-uid': 'esqois39pf6',
                    'x-async': false,
                    'x-index': 1,
                  },
                },
                'x-uid': 'okd9rwio86x',
                'x-async': false,
                'x-index': 1,
              },
            },
            'x-uid': 'wg35urizw83',
            'x-async': false,
            'x-index': 2,
          },
        },
        'x-uid': '7ta0nzl3kwd',
        'x-async': false,
        'x-index': 1,
      },
    },
    'x-uid': 'jxra1wgobos',
    'x-async': true,
    'x-index': 1,
  },
};
