/**
 * This file is part of the NocoBase (R) project.
 * Copyright (c) 2020-2024 NocoBase Co., Ltd.
 * Authors: NocoBase Team.
 *
 * This project is dual-licensed under AGPL-3.0 and NocoBase Commercial License.
 * For more information, please refer to: https://www.nocobase.com/agreement.
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import ts from 'typescript';

export const RUNJS_DOM_TYPE_ONLY_BRIDGE_SOURCE_FILE_NAMES = ['lib.dom.d.ts', 'lib.dom.iterable.d.ts'] as const;

export interface RunJSDOMTypeOnlyBridgeSource {
  fileName: string;
  content: string;
}

export interface GenerateRunJSDOMTypeOnlyBridgeOptions {
  outputPath: string;
  check?: boolean;
  libDirectory?: string;
}

const generatedMarker = '// Generated by @nocobase/runjs DOM type-only bridge generator. Do not edit.';

export class RunJSDOMTypeOnlyBridgeOutOfDateError extends Error {
  constructor(readonly outputPath: string) {
    super(`Generated RunJS DOM type-only bridge is out of date: ${outputPath}`);
    this.name = 'RunJSDOMTypeOnlyBridgeOutOfDateError';
  }
}

export function buildRunJSDOMTypeOnlyBridge(
  sources: readonly RunJSDOMTypeOnlyBridgeSource[],
  typeScript: typeof ts = ts,
): string {
  const factory = typeScript.factory;
  const printer = typeScript.createPrinter({ newLine: typeScript.NewLineKind.LineFeed, removeComments: true });
  const outputSourceFile = typeScript.createSourceFile(
    'runjs-dom-type-only-bridge.d.ts',
    '',
    typeScript.ScriptTarget.Latest,
    false,
    typeScript.ScriptKind.TS,
  );
  const declarations: ts.Statement[] = [];
  const declarationKinds = new Map<string, 'interface' | 'type'>();
  const interfaceTypeParameters = new Map<string, string>();
  const emittedTypeAliases = new Set<string>();

  for (const source of sources) {
    const sourceFile = typeScript.createSourceFile(
      source.fileName,
      source.content,
      typeScript.ScriptTarget.Latest,
      true,
      typeScript.ScriptKind.TS,
    );

    for (const statement of sourceFile.statements) {
      if (typeScript.isInterfaceDeclaration(statement)) {
        const name = statement.name.text;
        assertDeclarationKind(declarationKinds, name, 'interface');
        const typeParameterSignature = printTypeParameters(typeScript, printer, sourceFile, statement.typeParameters);
        const previousSignature = interfaceTypeParameters.get(name);
        if (previousSignature !== undefined) {
          if (previousSignature !== typeParameterSignature) {
            throw new Error(`Merged DOM interface "${name}" has incompatible type parameters.`);
          }
          continue;
        }
        interfaceTypeParameters.set(name, typeParameterSignature);
        const namespacedType = factory.createExpressionWithTypeArguments(
          factory.createPropertyAccessExpression(factory.createIdentifier('RunJSDOM'), name),
          createTypeArguments(typeScript, statement.typeParameters),
        );
        declarations.push(
          factory.createInterfaceDeclaration(
            undefined,
            name,
            statement.typeParameters,
            [factory.createHeritageClause(typeScript.SyntaxKind.ExtendsKeyword, [namespacedType])],
            [],
          ),
        );
        continue;
      }

      if (typeScript.isTypeAliasDeclaration(statement)) {
        const name = statement.name.text;
        assertDeclarationKind(declarationKinds, name, 'type');
        if (emittedTypeAliases.has(name)) {
          continue;
        }
        emittedTypeAliases.add(name);
        declarations.push(
          factory.createTypeAliasDeclaration(
            undefined,
            name,
            statement.typeParameters,
            factory.createTypeReferenceNode(
              factory.createQualifiedName(factory.createIdentifier('RunJSDOM'), name),
              createTypeArguments(typeScript, statement.typeParameters),
            ),
          ),
        );
      }
    }
  }

  return printer.printFile(factory.updateSourceFile(outputSourceFile, declarations)).trimEnd();
}

export async function generateRunJSDOMTypeOnlyBridge(options: GenerateRunJSDOMTypeOnlyBridgeOptions): Promise<string> {
  const libDirectory =
    options.libDirectory || path.dirname(ts.getDefaultLibFilePath({ target: ts.ScriptTarget.ES2020 }));
  const sources = await Promise.all(
    RUNJS_DOM_TYPE_ONLY_BRIDGE_SOURCE_FILE_NAMES.map(async (fileName) => ({
      fileName,
      content: await fs.readFile(path.join(libDirectory, fileName), 'utf8'),
    })),
  );
  const declaration = buildRunJSDOMTypeOnlyBridge(sources);
  const artifact = renderRunJSDOMTypeOnlyBridgeArtifact(declaration);
  const outputPath = path.resolve(options.outputPath);

  if (options.check) {
    const current = await fs.readFile(outputPath, 'utf8').catch(() => undefined);
    if (current !== artifact) {
      throw new RunJSDOMTypeOnlyBridgeOutOfDateError(outputPath);
    }
    return declaration;
  }

  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, artifact, 'utf8');
  return declaration;
}

function assertDeclarationKind(
  declarationKinds: Map<string, 'interface' | 'type'>,
  name: string,
  kind: 'interface' | 'type',
): void {
  const existingKind = declarationKinds.get(name);
  if (existingKind && existingKind !== kind) {
    throw new Error(`DOM declaration "${name}" is both an interface and a type alias.`);
  }
  declarationKinds.set(name, kind);
}

function createTypeArguments(
  typeScript: typeof ts,
  typeParameters: ts.NodeArray<ts.TypeParameterDeclaration> | undefined,
): ts.TypeNode[] | undefined {
  return typeParameters?.map((typeParameter) =>
    typeScript.factory.createTypeReferenceNode(typeParameter.name.text, undefined),
  );
}

function printTypeParameters(
  typeScript: typeof ts,
  printer: ts.Printer,
  sourceFile: ts.SourceFile,
  typeParameters: ts.NodeArray<ts.TypeParameterDeclaration> | undefined,
): string {
  return (typeParameters || [])
    .map((typeParameter) => printer.printNode(typeScript.EmitHint.Unspecified, typeParameter, sourceFile))
    .join(',');
}

function renderRunJSDOMTypeOnlyBridgeArtifact(declaration: string): string {
  return `${licenseHeader()}\n${generatedMarker}\n/* eslint-disable */\n\nexport const RUNJS_TYPESCRIPT_DOM_TYPE_ONLY_BRIDGE_DECLARATION = ${JSON.stringify(
    declaration,
  )};\n`;
}

function licenseHeader(): string {
  return `/**
 * This file is part of the NocoBase (R) project.
 * Copyright (c) 2020-2024 NocoBase Co., Ltd.
 * Authors: NocoBase Team.
 *
 * This project is dual-licensed under AGPL-3.0 and NocoBase Commercial License.
 * For more information, please refer to: https://www.nocobase.com/agreement.
 */`;
}
