import { general, PageConfig } from '@nocobase/test/client';

export const oneEmptyTableBlockWithActions: PageConfig = {
  // collections: general,
  pageSchema: {
    type: 'void',
    version: '2.0',
    'x-component': 'Page',
    _isJSONSchemaObject: true,
    properties: {
      '41di3r009jd': {
        type: 'void',
        version: '2.0',
        'x-component': 'Grid',
        'x-initializer': 'BlockInitializers',
        _isJSONSchemaObject: true,
        properties: {
          gbnc3li6a9w: {
            type: 'void',
            version: '2.0',
            'x-component': 'Grid.Row',
            _isJSONSchemaObject: true,
            properties: {
              j3eddpkupwt: {
                type: 'void',
                version: '2.0',
                'x-component': 'Grid.Col',
                _isJSONSchemaObject: true,
                properties: {
                  xdcz1yn5mhq: {
                    type: 'void',
                    version: '2.0',
                    'x-designer': 'TableBlockDesigner',
                    'x-component': 'CardItem',
                    'x-decorator': 'TableBlockProvider',
                    'x-acl-action': 'users:list',
                    'x-filter-targets': [],
                    'x-decorator-props': {
                      action: 'list',
                      params: {
                        pageSize: 20,
                      },
                      rowKey: 'id',
                      dragSort: false,
                      resource: 'users',
                      showIndex: true,
                      collection: 'users',
                      disableTemplate: false,
                    },
                    _isJSONSchemaObject: true,
                    properties: {
                      actions: {
                        type: 'void',
                        version: '2.0',
                        'x-component': 'ActionBar',
                        'x-initializer': 'TableActionInitializers',
                        'x-component-props': {
                          style: {
                            marginBottom: 'var(--nb-spacing)',
                          },
                        },
                        _isJSONSchemaObject: true,
                        properties: {
                          '1r5np6rvuu1': {
                            type: 'void',
                            title: "{{t('Add new')}}",
                            version: '2.0',
                            'x-align': 'right',
                            'x-action': 'create',
                            'x-designer': 'Action.Designer',
                            'x-component': 'Action',
                            'x-decorator': 'ACLActionProvider',
                            'x-acl-action': 'create',
                            'x-component-props': {
                              icon: 'PlusOutlined',
                              type: 'primary',
                              openMode: 'drawer',
                              component: 'CreateRecordAction',
                            },
                            'x-acl-action-props': {
                              skipScopeCheck: true,
                            },
                            _isJSONSchemaObject: true,
                            properties: {
                              drawer: {
                                type: 'void',
                                title: '{{ t("Add record") }}',
                                version: '2.0',
                                'x-component': 'Action.Container',
                                'x-component-props': {
                                  className: 'nb-action-popup',
                                },
                                _isJSONSchemaObject: true,
                                properties: {
                                  tabs: {
                                    type: 'void',
                                    version: '2.0',
                                    'x-component': 'Tabs',
                                    'x-initializer': 'TabPaneInitializersForCreateFormBlock',
                                    'x-component-props': {},
                                    _isJSONSchemaObject: true,
                                    properties: {
                                      tab1: {
                                        type: 'void',
                                        title: '{{t("Add new")}}',
                                        version: '2.0',
                                        'x-designer': 'Tabs.Designer',
                                        'x-component': 'Tabs.TabPane',
                                        'x-component-props': {},
                                        _isJSONSchemaObject: true,
                                        properties: {
                                          grid: {
                                            type: 'void',
                                            version: '2.0',
                                            'x-component': 'Grid',
                                            'x-initializer': 'CreateFormBlockInitializers',
                                            _isJSONSchemaObject: true,
                                            'x-uid': 'v7pxjwi9pj7',
                                            'x-async': false,
                                            'x-index': 1,
                                          },
                                        },
                                        'x-uid': 'tnctokz3b55',
                                        'x-async': false,
                                        'x-index': 1,
                                      },
                                    },
                                    'x-uid': 'kqkfs3l6eip',
                                    'x-async': false,
                                    'x-index': 1,
                                  },
                                },
                                'x-uid': 'p579n4wltcg',
                                'x-async': false,
                                'x-index': 1,
                              },
                            },
                            'x-uid': '3y8jltfizpf',
                            'x-async': false,
                            'x-index': 1,
                          },
                          t04fcms8ajo: {
                            type: 'void',
                            title: '{{ t("Delete") }}',
                            version: '2.0',
                            'x-align': 'right',
                            'x-action': 'destroy',
                            'x-designer': 'Action.Designer',
                            'x-component': 'Action',
                            'x-decorator': 'ACLActionProvider',
                            'x-acl-action': 'users:destroy',
                            'x-component-props': {
                              icon: 'DeleteOutlined',
                              confirm: {
                                title: "{{t('Delete record')}}",
                                content: "{{t('Are you sure you want to delete it?')}}",
                              },
                              useProps: '{{ useBulkDestroyActionProps }}',
                            },
                            'x-acl-action-props': {
                              skipScopeCheck: true,
                            },
                            _isJSONSchemaObject: true,
                            'x-uid': 'mdfewr4dlvm',
                            'x-async': false,
                            'x-index': 2,
                          },
                        },
                        'x-uid': 'lqz9dv59svz',
                        'x-async': false,
                        'x-index': 1,
                      },
                      '16hl9tu1ffk': {
                        type: 'array',
                        version: '2.0',
                        'x-component': 'TableV2',
                        'x-initializer': 'TableColumnInitializers',
                        'x-component-props': {
                          rowKey: 'id',
                          useProps: '{{ useTableBlockProps }}',
                          rowSelection: {
                            type: 'checkbox',
                          },
                        },
                        _isJSONSchemaObject: true,
                        properties: {
                          actions: {
                            type: 'void',
                            title: '{{ t("Actions") }}',
                            version: '2.0',
                            'x-designer': 'TableV2.ActionColumnDesigner',
                            'x-component': 'TableV2.Column',
                            'x-decorator': 'TableV2.Column.ActionBar',
                            'x-initializer': 'TableActionColumnInitializers',
                            'x-action-column': 'actions',
                            _isJSONSchemaObject: true,
                            properties: {
                              actions: {
                                type: 'void',
                                version: '2.0',
                                'x-component': 'Space',
                                'x-decorator': 'DndContext',
                                'x-component-props': {
                                  split: '|',
                                },
                                _isJSONSchemaObject: true,
                                properties: {
                                  sdrq42ok4ew: {
                                    type: 'void',
                                    title: '{{ t("Edit") }}',
                                    version: '2.0',
                                    'x-action': 'update',
                                    'x-designer': 'Action.Designer',
                                    'x-component': 'Action.Link',
                                    'x-decorator': 'ACLActionProvider',
                                    'x-designer-props': {
                                      linkageAction: true,
                                    },
                                    'x-component-props': {
                                      icon: 'EditOutlined',
                                      openMode: 'drawer',
                                    },
                                    _isJSONSchemaObject: true,
                                    properties: {
                                      drawer: {
                                        type: 'void',
                                        title: '{{ t("Edit record") }}',
                                        version: '2.0',
                                        'x-component': 'Action.Container',
                                        'x-component-props': {
                                          className: 'nb-action-popup',
                                        },
                                        _isJSONSchemaObject: true,
                                        properties: {
                                          tabs: {
                                            type: 'void',
                                            version: '2.0',
                                            'x-component': 'Tabs',
                                            'x-initializer': 'TabPaneInitializers',
                                            'x-component-props': {},
                                            _isJSONSchemaObject: true,
                                            properties: {
                                              tab1: {
                                                type: 'void',
                                                title: '{{t("Edit")}}',
                                                version: '2.0',
                                                'x-designer': 'Tabs.Designer',
                                                'x-component': 'Tabs.TabPane',
                                                'x-component-props': {},
                                                _isJSONSchemaObject: true,
                                                properties: {
                                                  grid: {
                                                    type: 'void',
                                                    version: '2.0',
                                                    'x-component': 'Grid',
                                                    'x-initializer': 'RecordBlockInitializers',
                                                    _isJSONSchemaObject: true,
                                                    'x-uid': '1krb3c4jti9',
                                                    'x-async': false,
                                                    'x-index': 1,
                                                  },
                                                },
                                                'x-uid': 'dk0us7k7lbk',
                                                'x-async': false,
                                                'x-index': 1,
                                              },
                                            },
                                            'x-uid': 'g0zgmu9anxv',
                                            'x-async': false,
                                            'x-index': 1,
                                          },
                                        },
                                        'x-uid': '3fo6d9hdrqu',
                                        'x-async': false,
                                        'x-index': 1,
                                      },
                                    },
                                    'x-uid': 'w4jg74lr1a0',
                                    'x-async': false,
                                    'x-index': 1,
                                  },
                                  '5kizp3fivpo': {
                                    type: 'void',
                                    title: '{{ t("Delete") }}',
                                    version: '2.0',
                                    'x-action': 'destroy',
                                    'x-designer': 'Action.Designer',
                                    'x-component': 'Action.Link',
                                    'x-decorator': 'ACLActionProvider',
                                    'x-designer-props': {
                                      linkageAction: true,
                                    },
                                    'x-component-props': {
                                      icon: 'DeleteOutlined',
                                      confirm: {
                                        title: "{{t('Delete record')}}",
                                        content: "{{t('Are you sure you want to delete it?')}}",
                                      },
                                      useProps: '{{ useDestroyActionProps }}',
                                    },
                                    _isJSONSchemaObject: true,
                                    'x-uid': 'nfeafij0216',
                                    'x-async': false,
                                    'x-index': 2,
                                  },
                                },
                                'x-uid': 'p3eirjb5x7i',
                                'x-async': false,
                                'x-index': 1,
                              },
                            },
                            'x-uid': 'g31xbx89vvd',
                            'x-async': false,
                            'x-index': 1,
                          },
                        },
                        'x-uid': 'fob1x156pmn',
                        'x-async': false,
                        'x-index': 2,
                      },
                    },
                    'x-uid': 'hs1uoqcf4cs',
                    'x-async': false,
                    'x-index': 1,
                  },
                },
                'x-uid': 'x05few1a4oi',
                'x-async': false,
                'x-index': 1,
              },
            },
            'x-uid': 'cvr91od4g44',
            'x-async': false,
            'x-index': 1,
          },
        },
        'x-uid': 'pnpna21v6n8',
        'x-async': false,
        'x-index': 1,
      },
    },
    'x-uid': '7xdw51730h0',
    'x-async': true,
    'x-index': 1,
  },
};

/**
 * 页面中有一个空的 Table 区块，并且配有字段：singleLineText,phone,percent
 */
export const oneEmptyTableBlockWithFields: PageConfig = {
  collections: general,
  pageSchema: {
    type: 'void',
    version: '2.0',
    'x-component': 'Page',
    _isJSONSchemaObject: true,
    properties: {
      hp8xrsakxmp: {
        type: 'void',
        version: '2.0',
        'x-component': 'Grid',
        'x-initializer': 'BlockInitializers',
        _isJSONSchemaObject: true,
        properties: {
          tjiyzokk0hk: {
            type: 'void',
            version: '2.0',
            'x-component': 'Grid.Row',
            _isJSONSchemaObject: true,
            properties: {
              zoim43wdfj7: {
                type: 'void',
                version: '2.0',
                'x-component': 'Grid.Col',
                _isJSONSchemaObject: true,
                properties: {
                  xqvr8sq84uq: {
                    type: 'void',
                    version: '2.0',
                    'x-designer': 'TableBlockDesigner',
                    'x-component': 'CardItem',
                    'x-decorator': 'TableBlockProvider',
                    'x-acl-action': 'general:list',
                    'x-filter-targets': [],
                    'x-decorator-props': {
                      action: 'list',
                      params: {
                        pageSize: 20,
                      },
                      rowKey: 'id',
                      dragSort: false,
                      resource: 'general',
                      showIndex: true,
                      collection: 'general',
                      disableTemplate: false,
                    },
                    _isJSONSchemaObject: true,
                    properties: {
                      actions: {
                        type: 'void',
                        version: '2.0',
                        'x-component': 'ActionBar',
                        'x-initializer': 'TableActionInitializers',
                        'x-component-props': {
                          style: {
                            marginBottom: 'var(--nb-spacing)',
                          },
                        },
                        _isJSONSchemaObject: true,
                        'x-uid': 'tiqpbf9287d',
                        'x-async': false,
                        'x-index': 1,
                      },
                      '1r3duvqvyo6': {
                        type: 'array',
                        version: '2.0',
                        'x-component': 'TableV2',
                        'x-initializer': 'TableColumnInitializers',
                        'x-component-props': {
                          rowKey: 'id',
                          useProps: '{{ useTableBlockProps }}',
                          rowSelection: {
                            type: 'checkbox',
                          },
                        },
                        _isJSONSchemaObject: true,
                        properties: {
                          actions: {
                            type: 'void',
                            title: '{{ t("Actions") }}',
                            version: '2.0',
                            'x-designer': 'TableV2.ActionColumnDesigner',
                            'x-component': 'TableV2.Column',
                            'x-decorator': 'TableV2.Column.ActionBar',
                            'x-initializer': 'TableActionColumnInitializers',
                            'x-action-column': 'actions',
                            _isJSONSchemaObject: true,
                            properties: {
                              actions: {
                                type: 'void',
                                version: '2.0',
                                'x-component': 'Space',
                                'x-decorator': 'DndContext',
                                'x-component-props': {
                                  split: '|',
                                },
                                _isJSONSchemaObject: true,
                                'x-uid': 'jc6heey1l39',
                                'x-async': false,
                                'x-index': 1,
                              },
                            },
                            'x-uid': 'gk863vfehar',
                            'x-async': false,
                            'x-index': 1,
                          },
                          u30tsz1woyi: {
                            type: 'void',
                            version: '2.0',
                            'x-designer': 'TableV2.Column.Designer',
                            'x-component': 'TableV2.Column',
                            'x-decorator': 'TableV2.Column.Decorator',
                            _isJSONSchemaObject: true,
                            properties: {
                              singleLineText: {
                                version: '2.0',
                                'x-component': 'CollectionField',
                                'x-decorator': null,
                                'x-read-pretty': true,
                                'x-component-props': {
                                  ellipsis: true,
                                },
                                'x-decorator-props': {
                                  labelStyle: {
                                    display: 'none',
                                  },
                                },
                                'x-collection-field': 'general.singleLineText',
                                _isJSONSchemaObject: true,
                                'x-uid': 'pz3ant6upuh',
                                'x-async': false,
                                'x-index': 1,
                              },
                            },
                            'x-uid': 'mqcskx1978e',
                            'x-async': false,
                            'x-index': 2,
                          },
                          zqjtaq22fr3: {
                            type: 'void',
                            version: '2.0',
                            'x-designer': 'TableV2.Column.Designer',
                            'x-component': 'TableV2.Column',
                            'x-decorator': 'TableV2.Column.Decorator',
                            _isJSONSchemaObject: true,
                            properties: {
                              phone: {
                                version: '2.0',
                                'x-component': 'CollectionField',
                                'x-decorator': null,
                                'x-read-pretty': true,
                                'x-component-props': {},
                                'x-decorator-props': {
                                  labelStyle: {
                                    display: 'none',
                                  },
                                },
                                'x-collection-field': 'general.phone',
                                _isJSONSchemaObject: true,
                                'x-uid': '4pbsi5uzc9a',
                                'x-async': false,
                                'x-index': 1,
                              },
                            },
                            'x-uid': '9oxsv4b5xk7',
                            'x-async': false,
                            'x-index': 3,
                          },
                          kzpyuff6bdk: {
                            type: 'void',
                            version: '2.0',
                            'x-designer': 'TableV2.Column.Designer',
                            'x-component': 'TableV2.Column',
                            'x-decorator': 'TableV2.Column.Decorator',
                            _isJSONSchemaObject: true,
                            properties: {
                              percent: {
                                version: '2.0',
                                'x-component': 'CollectionField',
                                'x-decorator': null,
                                'x-read-pretty': true,
                                'x-component-props': {
                                  style: {
                                    width: '100%',
                                  },
                                },
                                'x-decorator-props': {
                                  labelStyle: {
                                    display: 'none',
                                  },
                                },
                                'x-collection-field': 'general.percent',
                                _isJSONSchemaObject: true,
                                'x-uid': 'lwmdipbwb75',
                                'x-async': false,
                                'x-index': 1,
                              },
                            },
                            'x-uid': '33zsiui4pmz',
                            'x-async': false,
                            'x-index': 4,
                          },
                        },
                        'x-uid': 'cepnng5igm9',
                        'x-async': false,
                        'x-index': 2,
                      },
                    },
                    'x-uid': 'u0p9ju6vqgd',
                    'x-async': false,
                    'x-index': 1,
                  },
                },
                'x-uid': 'tj8u02bi26r',
                'x-async': false,
                'x-index': 1,
              },
            },
            'x-uid': 'hdi7wgdd8vf',
            'x-async': false,
            'x-index': 1,
          },
        },
        'x-uid': 'vu5h1stjse5',
        'x-async': false,
        'x-index': 1,
      },
    },
    'x-uid': 'q2frbwm5qpb',
    'x-async': true,
    'x-index': 1,
  },
};
