/**
 * This file is part of the NocoBase (R) project.
 * Copyright (c) 2020-2024 NocoBase Co., Ltd.
 * Authors: NocoBase Team.
 *
 * This project is dual-licensed under AGPL-3.0 and NocoBase Commercial License.
 * For more information, please refer to: https://www.nocobase.com/agreement.
 */

import { convertUiSchemaToJsonSchema } from '../utils';

it('should convert ui schema to json schema', async () => {
  const result = convertUiSchemaToJsonSchema({
    _isJSONSchemaObject: true,
    version: '2.0',
    type: 'void',
    'x-component': 'FormV2',
    'x-use-component-props': 'useCreateFormBlockProps',
    'x-app-version': '1.7.0-beta.9',
    properties: {
      grid: {
        _isJSONSchemaObject: true,
        version: '2.0',
        type: 'void',
        'x-component': 'Grid',
        'x-initializer': 'form:configureFields',
        'x-app-version': '1.7.0-beta.9',
        properties: {
          '9lv2wl150pl': {
            _isJSONSchemaObject: true,
            version: '2.0',
            type: 'void',
            'x-component': 'Grid.Row',
            'x-app-version': '1.7.0-beta.9',
            properties: {
              jjfipnudrfs: {
                _isJSONSchemaObject: true,
                version: '2.0',
                type: 'void',
                'x-component': 'Grid.Col',
                'x-app-version': '1.7.0-beta.9',
                properties: {
                  nickname: {
                    _isJSONSchemaObject: true,
                    version: '2.0',
                    type: 'string',
                    'x-toolbar': 'FormItemSchemaToolbar',
                    'x-settings': 'fieldSettings:FormItem',
                    'x-component': 'CollectionField',
                    'x-decorator': 'FormItem',
                    'x-collection-field': 'users.nickname',
                    'x-component-props': {},
                    'x-app-version': '1.7.0-beta.9',
                    'x-uid': 'mzsm3gfcix6',
                    'x-async': false,
                    'x-index': 1,
                    name: 'nickname',
                  },
                },
                'x-uid': 'wx3p0h2uj3a',
                'x-async': false,
                'x-index': 1,
                name: 'jjfipnudrfs',
              },
            },
            'x-uid': '1cndl1bxewd',
            'x-async': false,
            'x-index': 1,
            name: '9lv2wl150pl',
          },
          '25mljjny4u4': {
            _isJSONSchemaObject: true,
            version: '2.0',
            type: 'void',
            'x-component': 'Grid.Row',
            'x-app-version': '1.7.0-beta.9',
            properties: {
              l3vxr4qesnr: {
                _isJSONSchemaObject: true,
                version: '2.0',
                type: 'void',
                'x-component': 'Grid.Col',
                'x-app-version': '1.7.0-beta.9',
                properties: {
                  username: {
                    _isJSONSchemaObject: true,
                    version: '2.0',
                    type: 'string',
                    'x-toolbar': 'FormItemSchemaToolbar',
                    'x-settings': 'fieldSettings:FormItem',
                    'x-component': 'CollectionField',
                    'x-decorator': 'FormItem',
                    'x-collection-field': 'users.username',
                    'x-component-props': {},
                    'x-app-version': '1.7.0-beta.9',
                    'x-uid': 'hyqq9y93osu',
                    'x-async': false,
                    'x-index': 1,
                    name: 'username',
                  },
                },
                'x-uid': 'vzyckvjmhpq',
                'x-async': false,
                'x-index': 1,
                name: 'l3vxr4qesnr',
              },
            },
            'x-uid': 'q3uc0eoceyb',
            'x-async': false,
            'x-index': 2,
            name: '25mljjny4u4',
          },
          xhswvdtwuif: {
            _isJSONSchemaObject: true,
            version: '2.0',
            type: 'void',
            'x-component': 'Grid.Row',
            'x-app-version': '1.7.0-beta.9',
            properties: {
              ue5sdpbq6hr: {
                _isJSONSchemaObject: true,
                version: '2.0',
                type: 'void',
                'x-component': 'Grid.Col',
                'x-app-version': '1.7.0-beta.9',
                properties: {
                  email: {
                    _isJSONSchemaObject: true,
                    version: '2.0',
                    type: 'string',
                    'x-toolbar': 'FormItemSchemaToolbar',
                    'x-settings': 'fieldSettings:FormItem',
                    'x-component': 'CollectionField',
                    'x-decorator': 'FormItem',
                    'x-collection-field': 'users.email',
                    'x-component-props': {},
                    'x-app-version': '1.7.0-beta.9',
                    'x-uid': 'j8ayrm5ffvn',
                    'x-async': false,
                    'x-index': 1,
                    name: 'email',
                  },
                },
                'x-uid': 'z2y5tchettt',
                'x-async': false,
                'x-index': 1,
                name: 'ue5sdpbq6hr',
              },
            },
            'x-uid': '4e9k3kyh7a8',
            'x-async': false,
            'x-index': 3,
            name: 'xhswvdtwuif',
          },
          jpk5232nuty: {
            _isJSONSchemaObject: true,
            version: '2.0',
            type: 'void',
            'x-component': 'Grid.Row',
            'x-app-version': '1.7.0-beta.9',
            properties: {
              a5odai87axd: {
                _isJSONSchemaObject: true,
                version: '2.0',
                type: 'void',
                'x-component': 'Grid.Col',
                'x-app-version': '1.7.0-beta.9',
                properties: {
                  phone: {
                    _isJSONSchemaObject: true,
                    version: '2.0',
                    type: 'string',
                    'x-toolbar': 'FormItemSchemaToolbar',
                    'x-settings': 'fieldSettings:FormItem',
                    'x-component': 'CollectionField',
                    'x-decorator': 'FormItem',
                    'x-collection-field': 'users.phone',
                    'x-component-props': {},
                    'x-app-version': '1.7.0-beta.9',
                    'x-uid': 'vsg8y5ezr9d',
                    'x-async': false,
                    'x-index': 1,
                    name: 'phone',
                  },
                },
                'x-uid': 'cljjsqsovht',
                'x-async': false,
                'x-index': 1,
                name: 'a5odai87axd',
              },
            },
            'x-uid': 'ybzvngylbwq',
            'x-async': false,
            'x-index': 4,
            name: 'jpk5232nuty',
          },
        },
        'x-uid': 'ybw3ukyt20q',
        'x-async': false,
        'x-index': 1,
        name: 'grid',
      },
      m5fj43b5tv3: {
        _isJSONSchemaObject: true,
        version: '2.0',
        type: 'void',
        'x-component': 'ActionBar',
        'x-component-props': {
          layout: 'one-column',
          style: {
            marginBottom: 8,
          },
        },
        'x-app-version': '1.7.0-beta.9',
        properties: {
          '7mx0wfba3jq': {
            _isJSONSchemaObject: true,
            version: '2.0',
            type: 'void',
            'x-component': 'AIEmployeeButton',
            'x-toolbar': 'ActionSchemaToolbar',
            'x-settings': 'aiEmployees:button',
            'x-component-props': {
              aiEmployee: {
                createdAt: '2025-03-30T05:32:21.213Z',
                updatedAt: '2025-03-30T05:32:21.213Z',
                username: 'fromStruct',
                nickname: 'Structy',
                avatar: './wpuvnvazwl.svg',
                bio: 'An AI assistant specialized in structuring form content into organized and actionable data.',
                about:
                  'You are FormStructAI, an expert in structuring form data based on provided UI schemas. Your task is to analyze a given UI Schema, extract relevant form content, and return a structured JSON object that aligns with the schema. Ensure all required fields are properly populated, maintain data consistency, and infer missing values when possible. Your response must be formatted as JSON, ready to be pre-filled back into the form.',
                greeting:
                  'Hello! I’m Structy, here to help you turn messy form data into structured insights. How can I assist you today?',
                skills: null,
                modelSettings: null,
              },
            },
            'x-app-version': '1.7.0-beta.9',
            'x-uid': 'qjaxx03isdx',
            'x-async': false,
            'x-index': 1,
            name: '7mx0wfba3jq',
          },
        },
        'x-uid': 'ms75vnxwv2q',
        'x-async': false,
        'x-index': 2,
        name: 'm5fj43b5tv3',
      },
      '32rn0quhzze': {
        _isJSONSchemaObject: true,
        version: '2.0',
        type: 'void',
        'x-initializer': 'createForm:configureActions',
        'x-component': 'ActionBar',
        'x-component-props': {
          layout: 'one-column',
        },
        'x-app-version': '1.7.0-beta.9',
        properties: {
          '840bun8241p': {
            _isJSONSchemaObject: true,
            version: '2.0',
            title: '{{ t("Submit") }}',
            'x-action': 'submit',
            'x-component': 'Action',
            'x-use-component-props': 'useCreateActionProps',
            'x-toolbar': 'ActionSchemaToolbar',
            'x-settings': 'actionSettings:createSubmit',
            'x-component-props': {
              type: 'primary',
              htmlType: 'submit',
            },
            'x-action-settings': {},
            type: 'void',
            'x-app-version': '1.7.0-beta.9',
            'x-uid': 'r7ou2wp9kbo',
            'x-async': false,
            'x-index': 1,
            name: '840bun8241p',
          },
        },
        'x-uid': 'i97z5bbg537',
        'x-async': false,
        'x-index': 3,
        name: '32rn0quhzze',
      },
    },
    'x-uid': 'cnkrukqdrfn',
    'x-async': false,
    'x-index': 1,
    name: 'peiwud7mwvg',
  });
  console.log(result);
});
