/**
 * This file is part of the NocoBase (R) project.
 * Copyright (c) 2020-2024 NocoBase Co., Ltd.
 * Authors: NocoBase Team.
 *
 * This project is dual-licensed under AGPL-3.0 and NocoBase Commercial License.
 * For more information, please refer to: https://www.nocobase.com/agreement.
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import ts from 'typescript';

import { sha256Hex, stableSerialize } from '..';

export type RunJSCompletionCatalogCategory = 'component' | 'function' | 'icon' | 'object' | 'variable';

export interface RunJSCompletionCatalogEntry {
  name: string;
  category: RunJSCompletionCatalogCategory;
  packId: string;
  group?: string;
  source?: string;
}

export interface RunJSCompletionCatalog {
  id: string;
  moduleName: string;
  version: string;
  contentHash: string;
  entries: readonly RunJSCompletionCatalogEntry[];
}

export interface RunJSCompletionCatalogDefinition {
  id: 'antd' | 'antd-icons';
  moduleName: string;
  initialBudgetBytes: number;
}

export interface GenerateRunJSCompletionCatalogsOptions {
  projectRoot: string;
  outputDirectory: string;
  definitions: readonly RunJSCompletionCatalogDefinition[];
  check?: boolean;
}

export interface GeneratedRunJSCompletionCatalogManifestEntry {
  id: string;
  moduleName: string;
  version: string;
  contentHash: string;
  entryCount: number;
  rawBytes: number;
  initialBudgetBytes: number;
  async: boolean;
}

export interface GeneratedRunJSCompletionCatalogArtifacts {
  artifacts: ReadonlyMap<string, string>;
  catalogs: ReadonlyMap<string, RunJSCompletionCatalog>;
  manifest: readonly GeneratedRunJSCompletionCatalogManifestEntry[];
}

export function renderRunJSCompletionCatalogDataModule(catalogs: ReadonlyMap<string, RunJSCompletionCatalog>): string {
  const antdEntries = catalogs.get('antd')?.entries || [];
  const iconEntries = catalogs.get('antd-icons')?.entries || [];
  return `${licenseHeader()}\n${generatedMarker}\n${generatedEslintDisable}\n\nimport type { RunJSCompletionCatalogEntry } from './generator';\n\nexport const generatedRunJSAntdCompletionCatalog = ${JSON.stringify(
    antdEntries,
    null,
    2,
  )} satisfies readonly RunJSCompletionCatalogEntry[];\n\nexport const generatedRunJSAntdIconsCompletionCatalog = ${JSON.stringify(
    iconEntries,
    null,
    2,
  )} satisfies readonly RunJSCompletionCatalogEntry[];\n`;
}

interface CatalogRecord {
  definition: RunJSCompletionCatalogDefinition;
  exportName: string;
  fileName: string;
  catalog: RunJSCompletionCatalog;
  moduleSource: string;
  manifest: GeneratedRunJSCompletionCatalogManifestEntry;
}

interface PackageJsonRecord {
  version?: string;
}

const generatedMarker = '// Generated by @nocobase/runjs completion-catalog generator. Do not edit.';
const generatedEslintDisable = '/* eslint-disable */';
const iconNamePattern = /(?:Filled|Outlined|TwoTone)$/u;

export class RunJSCompletionCatalogArtifactsOutOfDateError extends Error {
  constructor(readonly staleArtifacts: readonly string[]) {
    super(`Generated RunJS completion catalogs are out of date: ${staleArtifacts.join(', ')}`);
    this.name = 'RunJSCompletionCatalogArtifactsOutOfDateError';
  }
}

export async function generateRunJSCompletionCatalogs(
  options: GenerateRunJSCompletionCatalogsOptions,
): Promise<GeneratedRunJSCompletionCatalogArtifacts> {
  const definitions = [...options.definitions].sort((left, right) => left.id.localeCompare(right.id));
  validateDefinitions(definitions);
  const records: CatalogRecord[] = [];
  for (const definition of definitions) {
    const catalog = await collectRunJSCompletionCatalog(options.projectRoot, definition);
    const exportName = toCatalogExportName(definition.id);
    const fileName = definition.id === 'antd-icons' ? 'icons.ts' : `${definition.id}.ts`;
    const moduleSource = renderCatalogModule(catalog, exportName);
    const rawBytes = Buffer.byteLength(moduleSource, 'utf8');
    records.push({
      definition,
      exportName,
      fileName,
      catalog,
      moduleSource,
      manifest: {
        id: catalog.id,
        moduleName: catalog.moduleName,
        version: catalog.version,
        contentHash: catalog.contentHash,
        entryCount: catalog.entries.length,
        rawBytes,
        initialBudgetBytes: definition.initialBudgetBytes,
        async: definition.id === 'antd-icons' && rawBytes > definition.initialBudgetBytes,
      },
    });
  }

  const artifacts = buildArtifacts(records);
  if (options.check) {
    const manifestArtifact = artifacts.get('manifest.ts');
    if (!manifestArtifact) {
      throw new Error('Missing generated RunJS completion catalog manifest artifact');
    }
    const staleArtifacts = await findStaleArtifacts(
      options.outputDirectory,
      new Map([['manifest.ts', manifestArtifact]]),
    );
    if (staleArtifacts.length) {
      throw new RunJSCompletionCatalogArtifactsOutOfDateError(staleArtifacts);
    }
  } else {
    await writeArtifacts(options.outputDirectory, artifacts);
  }

  return {
    artifacts,
    catalogs: new Map(records.map((record) => [record.catalog.id, record.catalog])),
    manifest: records.map((record) => record.manifest),
  };
}

export async function collectRunJSCompletionCatalog(
  projectRoot: string,
  definition: RunJSCompletionCatalogDefinition,
): Promise<RunJSCompletionCatalog> {
  const normalizedRoot = path.resolve(projectRoot);
  const compilerOptions: ts.CompilerOptions = {
    allowSyntheticDefaultImports: true,
    esModuleInterop: true,
    jsx: ts.JsxEmit.React,
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.NodeJs,
    noEmit: true,
    skipLibCheck: true,
    target: ts.ScriptTarget.ES2020,
    types: [],
  };
  const syntheticFileName = path.join(
    normalizedRoot,
    '.runjs-completion-catalog',
    `${sha256Hex(definition.moduleName).slice(0, 16)}.tsx`,
  );
  const syntheticSource = `import * as RunJSCatalogModule from ${JSON.stringify(
    definition.moduleName,
  )};\nexport { RunJSCatalogModule };\n`;
  const baseHost = ts.createCompilerHost(compilerOptions, true);
  const isSyntheticFile = (fileName: string): boolean => path.resolve(fileName) === path.resolve(syntheticFileName);
  const host: ts.CompilerHost = {
    ...baseHost,
    fileExists(fileName) {
      return isSyntheticFile(fileName) || baseHost.fileExists(fileName);
    },
    getSourceFile(fileName, languageVersion, onError, shouldCreateNewSourceFile) {
      if (isSyntheticFile(fileName)) {
        return ts.createSourceFile(fileName, syntheticSource, languageVersion, true, ts.ScriptKind.TSX);
      }
      return baseHost.getSourceFile(fileName, languageVersion, onError, shouldCreateNewSourceFile);
    },
    readFile(fileName) {
      return isSyntheticFile(fileName) ? syntheticSource : baseHost.readFile(fileName);
    },
  };
  const program = ts.createProgram({ rootNames: [syntheticFileName], options: compilerOptions, host });
  const sourceFile = program.getSourceFile(syntheticFileName);
  if (!sourceFile) {
    throw new Error(`Unable to create completion catalog program for ${definition.moduleName}`);
  }
  const importDeclaration = sourceFile.statements.find(ts.isImportDeclaration);
  const namespaceName = importDeclaration?.importClause?.namedBindings;
  if (!namespaceName || !ts.isNamespaceImport(namespaceName)) {
    throw new Error(`Unable to create namespace import for completion catalog ${definition.moduleName}`);
  }
  const checker = program.getTypeChecker();
  const alias = checker.getSymbolAtLocation(namespaceName.name);
  if (!alias) {
    throw new Error(`Unable to resolve completion catalog module ${definition.moduleName}`);
  }
  const moduleSymbol = alias.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(alias) : alias;
  const entries = checker
    .getExportsOfModule(moduleSymbol)
    .map((symbol) => toCatalogEntry(checker, symbol, definition))
    .filter((entry): entry is RunJSCompletionCatalogEntry => Boolean(entry))
    .sort((left, right) => left.name.localeCompare(right.name));
  const resolvedModule = ts.resolveModuleName(
    definition.moduleName,
    syntheticFileName,
    compilerOptions,
    ts.sys,
  ).resolvedModule;
  if (!resolvedModule) {
    throw new Error(`Unable to resolve completion catalog module ${definition.moduleName}`);
  }
  const packageJsonPath = getOwningPackageJsonPath(resolvedModule.resolvedFileName);
  const packageJson = packageJsonPath ? await readPackageJson(packageJsonPath) : {};
  const version = resolvedModule.packageId?.version || packageJson.version;
  if (!version) {
    throw new Error(`Unable to determine completion catalog version for ${definition.moduleName}`);
  }
  const contentHash = sha256Hex(
    stableSerialize({ id: definition.id, moduleName: definition.moduleName, version, entries }),
  );
  return {
    id: definition.id,
    moduleName: definition.moduleName,
    version,
    contentHash,
    entries,
  };
}

function toCatalogEntry(
  checker: ts.TypeChecker,
  exportedSymbol: ts.Symbol,
  definition: RunJSCompletionCatalogDefinition,
): RunJSCompletionCatalogEntry | undefined {
  if (exportedSymbol.name === 'default') {
    return undefined;
  }
  const symbol =
    exportedSymbol.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(exportedSymbol) : exportedSymbol;
  if (!(symbol.flags & ts.SymbolFlags.Value)) {
    return undefined;
  }
  const name = exportedSymbol.name;
  const group = definition.id === 'antd-icons' ? iconGroup(name) : undefined;
  return {
    name,
    category: classifyExport(checker, symbol, definition.id, name),
    packId: definition.id === 'antd-icons' ? `antd-icons/${group}` : `antd/${name}`,
    ...(group ? { group } : {}),
    source: definition.moduleName,
  };
}

function classifyExport(
  checker: ts.TypeChecker,
  symbol: ts.Symbol,
  catalogId: RunJSCompletionCatalogDefinition['id'],
  exportedName: string,
): RunJSCompletionCatalogCategory {
  if (catalogId === 'antd-icons' && iconNamePattern.test(exportedName)) {
    return 'icon';
  }
  if (catalogId === 'antd' && /^[A-Z]/u.test(exportedName)) {
    return 'component';
  }
  if (symbol.flags & (ts.SymbolFlags.Function | ts.SymbolFlags.Method)) {
    return 'function';
  }
  const declaration = symbol.valueDeclaration || symbol.declarations?.[0];
  if (declaration) {
    const type = checker.getTypeOfSymbolAtLocation(symbol, declaration);
    if (checker.getSignaturesOfType(type, ts.SignatureKind.Call).length) {
      return 'function';
    }
  }
  if (symbol.flags & (ts.SymbolFlags.Class | ts.SymbolFlags.Module | ts.SymbolFlags.NamespaceModule)) {
    return 'object';
  }
  return 'variable';
}

function buildArtifacts(records: readonly CatalogRecord[]): Map<string, string> {
  const artifacts = new Map<string, string>();
  records.forEach((record) => artifacts.set(record.fileName, record.moduleSource));
  artifacts.set('manifest.ts', renderManifestModule(records.map((record) => record.manifest)));
  artifacts.set('loaders.ts', renderLoadersModule(records));
  return artifacts;
}

function renderCatalogModule(catalog: RunJSCompletionCatalog, exportName: string): string {
  return `${licenseHeader()}\n${generatedMarker}\n${generatedEslintDisable}\n\nexport interface GeneratedRunJSCompletionCatalogEntry {\n  name: string;\n  category: 'component' | 'function' | 'icon' | 'object' | 'variable';\n  packId: string;\n  group?: string;\n  source?: string;\n}\n\nexport const ${exportName}: readonly GeneratedRunJSCompletionCatalogEntry[] = ${JSON.stringify(
    catalog.entries,
    null,
    2,
  )};\n`;
}

function renderManifestModule(entries: readonly GeneratedRunJSCompletionCatalogManifestEntry[]): string {
  return `${licenseHeader()}\n${generatedMarker}\n${generatedEslintDisable}\n\nexport interface GeneratedRunJSCompletionCatalogManifestEntry {\n  id: string;\n  moduleName: string;\n  version: string;\n  contentHash: string;\n  entryCount: number;\n  rawBytes: number;\n  initialBudgetBytes: number;\n  async: boolean;\n}\n\nexport const generatedRunJSCompletionCatalogManifest: readonly GeneratedRunJSCompletionCatalogManifestEntry[] = ${JSON.stringify(
    entries,
    null,
    2,
  )};\n`;
}

function renderLoadersModule(records: readonly CatalogRecord[]): string {
  const staticImports: string[] = [];
  const exports: string[] = [];
  for (const record of records) {
    const loaderName = `load${capitalize(record.exportName)}`;
    if (record.manifest.async) {
      exports.push(
        `export async function ${loaderName}() {\n  return (await import('./${record.fileName.replace(
          /\.ts$/u,
          '',
        )}')).${record.exportName};\n}`,
      );
    } else {
      staticImports.push(`import { ${record.exportName} } from './${record.fileName.replace(/\.ts$/u, '')}';`);
      exports.push(`export async function ${loaderName}() {\n  return ${record.exportName};\n}`);
    }
  }
  return `${licenseHeader()}\n${generatedMarker}\n${generatedEslintDisable}\n\n${staticImports.join(
    '\n',
  )}\n\n${exports.join('\n\n')}\n`;
}

async function findStaleArtifacts(outputDirectory: string, expected: ReadonlyMap<string, string>): Promise<string[]> {
  const stale: string[] = [];
  for (const relativePath of [...expected.keys()].sort()) {
    let actual: string | undefined;
    try {
      actual = await fs.readFile(path.join(outputDirectory, relativePath), 'utf8');
    } catch (error) {
      if (!isMissingFileError(error)) throw error;
    }
    if (actual !== expected.get(relativePath)) {
      stale.push(relativePath);
    }
  }
  return stale;
}

async function writeArtifacts(outputDirectory: string, artifacts: ReadonlyMap<string, string>): Promise<void> {
  await fs.rm(outputDirectory, { recursive: true, force: true });
  for (const [relativePath, content] of artifacts) {
    const fileName = path.join(outputDirectory, relativePath);
    await fs.mkdir(path.dirname(fileName), { recursive: true });
    await fs.writeFile(fileName, content, 'utf8');
  }
}

function getOwningPackageJsonPath(fileName: string): string | undefined {
  const normalized = String(fileName).replace(/\\/gu, '/');
  const marker = '/node_modules/';
  const markerIndex = normalized.indexOf(marker);
  if (markerIndex < 0) return undefined;
  const packageStart = markerIndex + marker.length;
  const segments = normalized.slice(packageStart).split('/');
  const count = segments[0]?.startsWith('@') ? 2 : 1;
  if (segments.length < count) return undefined;
  return path.normalize(`${normalized.slice(0, packageStart)}${segments.slice(0, count).join('/')}/package.json`);
}

async function readPackageJson(fileName: string): Promise<PackageJsonRecord> {
  const value: unknown = JSON.parse(await fs.readFile(fileName, 'utf8'));
  if (!value || typeof value !== 'object' || Array.isArray(value)) return {};
  const version = (value as Record<string, unknown>).version;
  return { version: typeof version === 'string' ? version : undefined };
}

function validateDefinitions(definitions: readonly RunJSCompletionCatalogDefinition[]): void {
  const seen = new Set<string>();
  for (const definition of definitions) {
    if (seen.has(definition.id)) throw new Error(`Duplicate RunJS completion catalog: ${definition.id}`);
    if (!definition.moduleName || definition.initialBudgetBytes <= 0) {
      throw new Error(`Invalid RunJS completion catalog definition: ${definition.id}`);
    }
    seen.add(definition.id);
  }
}

function iconGroup(symbol: string): string {
  const first = Array.from(symbol)[0] || '';
  return /^[A-Za-z]$/u.test(first) ? first.toUpperCase() : 'other';
}

function toCatalogExportName(id: RunJSCompletionCatalogDefinition['id']): string {
  return id === 'antd-icons' ? 'generatedRunJSAntdIconsCompletionCatalog' : 'generatedRunJSAntdCompletionCatalog';
}

function capitalize(value: string): string {
  return value ? `${value[0].toUpperCase()}${value.slice(1)}` : value;
}

function isMissingFileError(error: unknown): boolean {
  return Boolean(error && typeof error === 'object' && 'code' in error && error.code === 'ENOENT');
}

function licenseHeader(): string {
  return `/**\n * This file is part of the NocoBase (R) project.\n * Copyright (c) 2020-2024 NocoBase Co., Ltd.\n * Authors: NocoBase Team.\n *\n * This project is dual-licensed under AGPL-3.0 and NocoBase Commercial License.\n * For more information, please refer to: https://www.nocobase.com/agreement.\n */`;
}
