/**
 * This file is part of the NocoBase (R) project.
 * Copyright (c) 2020-2024 NocoBase Co., Ltd.
 * Authors: NocoBase Team.
 *
 * This project is dual-licensed under AGPL-3.0 and NocoBase Commercial License.
 * For more information, please refer to: https://www.nocobase.com/agreement.
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import ts from 'typescript';

import { normalizeText, sha256Hex, stableSerialize } from '..';
import type { RunJSTypeLibraryFile, RunJSTypeLibraryPack, RunJSTypeLibraryPackDependency } from '../typescript-library';

export interface RunJSTypeLibraryPackRootFileInput {
  path: string;
  content: string;
}

export interface RunJSTypeLibraryPackDefinition {
  id: string;
  libraryName: string;
  entry: string;
  dependencies?: readonly string[];
  rootFiles?: readonly RunJSTypeLibraryPackRootFileInput[];
  triggers?: readonly string[];
  metadata?: Readonly<Record<string, string | number | boolean>>;
  version?: string;
}

export interface GenerateRunJSTypeLibraryPacksOptions {
  projectRoot: string;
  outputDirectory: string;
  definitions: readonly RunJSTypeLibraryPackDefinition[];
  check?: boolean;
}

export interface GeneratedRunJSTypeLibraryPackManifestEntry {
  id: string;
  libraryName: string;
  version: string;
  entry: string;
  sourcePackage: string;
  dependencies: readonly RunJSTypeLibraryPackDependency[];
  triggers: readonly string[];
  contentHash: string;
  graphHash: string;
  fileCount: number;
  rootFileCount: number;
  dependencyFileCount: number;
  graphRawBytes: number;
  rawBytes: number;
}

export interface GeneratedRunJSTypeLibraryPackArtifacts {
  artifacts: ReadonlyMap<string, string>;
  manifest: readonly GeneratedRunJSTypeLibraryPackManifestEntry[];
  packs: ReadonlyMap<string, RunJSTypeLibraryPack>;
}

interface CollectedDeclarationGraph {
  dependencyFiles: RunJSTypeLibraryFile[];
  sourcePackage: string;
  version: string;
}

interface GeneratedPackRecord {
  graphHash: string;
  pack: RunJSTypeLibraryPack;
  manifest: GeneratedRunJSTypeLibraryPackManifestEntry;
}

interface PackageJsonRecord {
  name?: string;
  version?: string;
}

const generatedMarker = '// Generated by @nocobase/runjs type-pack generator. Do not edit.';
const generatedEslintDisable = '/* eslint-disable */';
const declarationExtension = /\.d\.(?:cts|mts|ts)$/u;
const testDeclarationPath = /(?:^|\/)(?:__tests__|tests?|fixtures)(?:\/|$)|\.(?:spec|test)\.d\.(?:cts|mts|ts)$/iu;

export class RunJSTypePackArtifactsOutOfDateError extends Error {
  constructor(readonly staleArtifacts: readonly string[]) {
    super(`Generated RunJS type-pack artifacts are out of date: ${staleArtifacts.join(', ')}`);
    this.name = 'RunJSTypePackArtifactsOutOfDateError';
  }
}

export class RunJSTypePackPathConflictError extends Error {
  constructor(
    readonly virtualPath: string,
    readonly leftHash: string,
    readonly rightHash: string,
  ) {
    super(`RunJS type-pack path conflict for "${virtualPath}": ${leftHash} !== ${rightHash}`);
    this.name = 'RunJSTypePackPathConflictError';
  }
}

export async function generateRunJSTypeLibraryPacks(
  options: GenerateRunJSTypeLibraryPacksOptions,
): Promise<GeneratedRunJSTypeLibraryPackArtifacts> {
  const projectRoot = path.resolve(options.projectRoot);
  const definitionById = createDefinitionMap(options.definitions);
  const generatedById = new Map<string, GeneratedPackRecord>();
  const visiting = new Set<string>();
  const globallySeenFiles = new Map<string, string>();

  const generateDefinition = async (id: string): Promise<GeneratedPackRecord> => {
    const existing = generatedById.get(id);
    if (existing) {
      return existing;
    }
    const definition = definitionById.get(id);
    if (!definition) {
      throw new Error(`Unknown RunJS type-pack dependency: ${id}`);
    }
    if (visiting.has(id)) {
      throw new Error(`Circular RunJS type-pack dependency involving "${id}"`);
    }

    visiting.add(id);
    const dependencyRecords: GeneratedPackRecord[] = [];
    for (const dependencyId of stableUnique(definition.dependencies || [])) {
      dependencyRecords.push(await generateDefinition(dependencyId));
    }

    const graph = await collectRunJSTypeDeclarationGraph(projectRoot, definition.entry);
    const inheritedFiles = collectInheritedFiles(dependencyRecords, generatedById);
    const dependencyFiles = excludeInheritedFiles(graph.dependencyFiles, inheritedFiles);
    const rootFiles = createRootFiles(definition.rootFiles || []);
    const graphHash = buildDeclarationGraphHash(dependencyFiles);
    const graphRawBytes = dependencyFiles.reduce((total, file) => total + Buffer.byteLength(file.content, 'utf8'), 0);
    const dependencies = dependencyRecords.map(({ pack }) => ({
      id: pack.id,
      version: pack.version,
      contentHash: pack.contentHash,
    }));
    const version = definition.version || graph.version;
    const rawBytes =
      graphRawBytes + rootFiles.reduce((total, file) => total + Buffer.byteLength(file.content, 'utf8'), 0);
    const contentHash = buildPackContentHash({
      definition,
      version,
      sourcePackage: graph.sourcePackage,
      dependencies,
      rootFiles,
      dependencyFiles,
    });
    const pack: RunJSTypeLibraryPack = {
      id: definition.id,
      libraryName: definition.libraryName,
      version,
      contentHash,
      dependencies,
      rootFiles,
      dependencyFiles,
      metadata: {
        ...definition.metadata,
        entry: definition.entry,
        sourcePackage: graph.sourcePackage,
        fileCount: rootFiles.length + dependencyFiles.length,
        rawBytes,
      },
    };

    validateGlobalFileHashes(pack, globallySeenFiles);
    const manifest: GeneratedRunJSTypeLibraryPackManifestEntry = {
      id: definition.id,
      libraryName: definition.libraryName,
      version,
      entry: definition.entry,
      sourcePackage: graph.sourcePackage,
      dependencies,
      triggers: stableUnique(definition.triggers || [definition.id]),
      contentHash,
      graphHash,
      fileCount: rootFiles.length + dependencyFiles.length,
      rootFileCount: rootFiles.length,
      dependencyFileCount: dependencyFiles.length,
      graphRawBytes,
      rawBytes,
    };
    const record: GeneratedPackRecord = {
      graphHash,
      pack,
      manifest,
    };
    generatedById.set(id, record);
    visiting.delete(id);
    return record;
  };

  for (const id of [...definitionById.keys()].sort()) {
    await generateDefinition(id);
  }

  const records = [...generatedById.values()].sort((left, right) => left.pack.id.localeCompare(right.pack.id));
  const artifacts = buildGeneratedArtifacts(records);

  if (options.check) {
    const manifestArtifact = artifacts.get('manifest.ts');
    if (!manifestArtifact) {
      throw new Error('Missing generated RunJS type-pack manifest artifact');
    }
    const staleArtifacts = await findStaleArtifacts(
      options.outputDirectory,
      new Map([['manifest.ts', manifestArtifact]]),
    );
    if (staleArtifacts.length) {
      throw new RunJSTypePackArtifactsOutOfDateError(staleArtifacts);
    }
  } else {
    await writeGeneratedArtifacts(options.outputDirectory, artifacts);
  }

  return {
    artifacts,
    manifest: records.map((record) => record.manifest),
    packs: new Map(records.map((record) => [record.pack.id, record.pack])),
  };
}

export async function collectRunJSTypeDeclarationGraph(
  projectRoot: string,
  entry: string,
): Promise<CollectedDeclarationGraph> {
  const compilerOptions: ts.CompilerOptions = {
    allowSyntheticDefaultImports: true,
    esModuleInterop: true,
    jsx: ts.JsxEmit.React,
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.NodeJs,
    noEmit: true,
    noLib: true,
    skipLibCheck: true,
    target: ts.ScriptTarget.ES2020,
    types: [],
  };
  const normalizedRoot = path.resolve(projectRoot);
  const syntheticFileName = path.join(normalizedRoot, '.runjs-type-pack', `${sha256Hex(entry).slice(0, 16)}.tsx`);
  const syntheticSource = `import type * as RunJSTypePackEntry from ${JSON.stringify(
    entry,
  )};\nexport type __RunJSTypePackEntry = typeof RunJSTypePackEntry;\n`;
  const packageJsonPaths = new Set<string>();
  const baseHost = ts.createCompilerHost(compilerOptions, true);
  const isSyntheticFile = (fileName: string): boolean => path.resolve(fileName) === path.resolve(syntheticFileName);
  const readFile = (fileName: string): string | undefined => {
    if (isSyntheticFile(fileName)) {
      return syntheticSource;
    }
    const content = baseHost.readFile(fileName);
    if (typeof content === 'string' && path.basename(fileName) === 'package.json') {
      packageJsonPaths.add(path.resolve(fileName));
    }
    return content;
  };
  const host: ts.CompilerHost = {
    ...baseHost,
    fileExists(fileName) {
      return isSyntheticFile(fileName) || baseHost.fileExists(fileName);
    },
    getSourceFile(fileName, languageVersion, onError, shouldCreateNewSourceFile) {
      if (isSyntheticFile(fileName)) {
        return ts.createSourceFile(fileName, syntheticSource, languageVersion, true, ts.ScriptKind.TSX);
      }
      return baseHost.getSourceFile(fileName, languageVersion, onError, shouldCreateNewSourceFile);
    },
    readFile,
  };
  const moduleResolutionHost: ts.ModuleResolutionHost = {
    directoryExists: host.directoryExists,
    fileExists: host.fileExists,
    getCurrentDirectory: () => normalizedRoot,
    getDirectories: host.getDirectories,
    readFile,
    realpath: host.realpath,
    useCaseSensitiveFileNames: host.useCaseSensitiveFileNames,
  };
  const resolved = ts.resolveModuleName(entry, syntheticFileName, compilerOptions, moduleResolutionHost).resolvedModule;
  if (!resolved) {
    throw new Error(`Unable to resolve RunJS type-pack entry "${entry}" from ${normalizedRoot}`);
  }

  const program = ts.createProgram({ rootNames: [syntheticFileName], options: compilerOptions, host });
  program.getTypeChecker();
  const declarationPaths = program
    .getSourceFiles()
    .map((sourceFile) => path.resolve(sourceFile.fileName))
    .filter((fileName) => !isSyntheticFile(fileName))
    .filter((fileName) => declarationExtension.test(toPosixPath(fileName)))
    .filter((fileName) => !testDeclarationPath.test(toVirtualTypePackPath(fileName)));

  for (const declarationPath of declarationPaths) {
    const ownerPackageJson = getOwningPackageJsonPath(declarationPath);
    if (ownerPackageJson) {
      packageJsonPaths.add(ownerPackageJson);
    }
  }

  const files: RunJSTypeLibraryFile[] = [];
  for (const fileName of stableUnique([...declarationPaths, ...packageJsonPaths])) {
    if (!isInsideNodeModules(fileName)) {
      continue;
    }
    const content = normalizeText(await fs.readFile(fileName, 'utf8'));
    files.push({
      path: toVirtualTypePackPath(fileName),
      content,
      contentHash: sha256Hex(content),
    });
  }
  files.sort((left, right) => left.path.localeCompare(right.path));

  const resolvedPackageJsonPath = getOwningPackageJsonPath(path.resolve(resolved.resolvedFileName));
  const resolvedPackage = resolvedPackageJsonPath ? await readPackageJson(resolvedPackageJsonPath) : {};
  const sourcePackage = resolved.packageId?.name || resolvedPackage.name || entry.split('/')[0];
  const version = resolved.packageId?.version || resolvedPackage.version;
  if (!version) {
    throw new Error(`Unable to determine package version for RunJS type-pack entry "${entry}"`);
  }

  return {
    dependencyFiles: files,
    sourcePackage,
    version,
  };
}

export function collectRunJSTypeDeclarationGraphSync(projectRoot: string, entry: string): CollectedDeclarationGraph {
  const compilerOptions: ts.CompilerOptions = {
    allowSyntheticDefaultImports: true,
    esModuleInterop: true,
    jsx: ts.JsxEmit.React,
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.NodeJs,
    noEmit: true,
    noLib: true,
    skipLibCheck: true,
    target: ts.ScriptTarget.ES2020,
    types: [],
  };
  const normalizedRoot = path.resolve(projectRoot);
  const syntheticFileName = path.join(normalizedRoot, '.runjs-type-pack', `${sha256Hex(entry).slice(0, 16)}.tsx`);
  const syntheticSource = `import type * as RunJSTypePackEntry from ${JSON.stringify(
    entry,
  )};\nexport type __RunJSTypePackEntry = typeof RunJSTypePackEntry;\n`;
  const packageJsonPaths = new Set<string>();
  const baseHost = ts.createCompilerHost(compilerOptions, true);
  const isSyntheticFile = (fileName: string): boolean => path.resolve(fileName) === path.resolve(syntheticFileName);
  const readFile = (fileName: string): string | undefined => {
    if (isSyntheticFile(fileName)) {
      return syntheticSource;
    }
    const content = baseHost.readFile(fileName);
    if (typeof content === 'string' && path.basename(fileName) === 'package.json') {
      packageJsonPaths.add(path.resolve(fileName));
    }
    return content;
  };
  const host: ts.CompilerHost = {
    ...baseHost,
    fileExists(fileName) {
      return isSyntheticFile(fileName) || baseHost.fileExists(fileName);
    },
    getSourceFile(fileName, languageVersion, onError, shouldCreateNewSourceFile) {
      if (isSyntheticFile(fileName)) {
        return ts.createSourceFile(fileName, syntheticSource, languageVersion, true, ts.ScriptKind.TSX);
      }
      return baseHost.getSourceFile(fileName, languageVersion, onError, shouldCreateNewSourceFile);
    },
    readFile,
  };
  const moduleResolutionHost: ts.ModuleResolutionHost = {
    directoryExists: host.directoryExists,
    fileExists: host.fileExists,
    getCurrentDirectory: () => normalizedRoot,
    getDirectories: host.getDirectories,
    readFile,
    realpath: host.realpath,
    useCaseSensitiveFileNames: host.useCaseSensitiveFileNames,
  };
  const resolved = ts.resolveModuleName(entry, syntheticFileName, compilerOptions, moduleResolutionHost).resolvedModule;
  if (!resolved) {
    throw new Error(`Unable to resolve RunJS type-pack entry "${entry}" from ${normalizedRoot}`);
  }

  const program = ts.createProgram({ rootNames: [syntheticFileName], options: compilerOptions, host });
  program.getTypeChecker();
  const declarationPaths = program
    .getSourceFiles()
    .map((sourceFile) => path.resolve(sourceFile.fileName))
    .filter((fileName) => !isSyntheticFile(fileName))
    .filter((fileName) => declarationExtension.test(toPosixPath(fileName)))
    .filter((fileName) => !testDeclarationPath.test(toVirtualTypePackPath(fileName)));

  for (const declarationPath of declarationPaths) {
    const ownerPackageJson = getOwningPackageJsonPath(declarationPath);
    if (ownerPackageJson) {
      packageJsonPaths.add(ownerPackageJson);
    }
  }

  const files: RunJSTypeLibraryFile[] = [];
  for (const fileName of stableUnique([...declarationPaths, ...packageJsonPaths])) {
    if (!isInsideNodeModules(fileName)) {
      continue;
    }
    const source = ts.sys.readFile(fileName);
    if (typeof source !== 'string') {
      throw new Error(`Unable to read RunJS type-pack file: ${fileName}`);
    }
    const content = normalizeText(source);
    files.push({
      path: toVirtualTypePackPath(fileName),
      content,
      contentHash: sha256Hex(content),
    });
  }
  files.sort((left, right) => left.path.localeCompare(right.path));

  const resolvedPackageJsonPath = getOwningPackageJsonPath(path.resolve(resolved.resolvedFileName));
  const resolvedPackage = resolvedPackageJsonPath ? readPackageJsonSync(resolvedPackageJsonPath) : {};
  const sourcePackage = resolved.packageId?.name || resolvedPackage.name || entry.split('/')[0];
  const version = resolved.packageId?.version || resolvedPackage.version;
  if (!version) {
    throw new Error(`Unable to determine package version for RunJS type-pack entry "${entry}"`);
  }

  return {
    dependencyFiles: files,
    sourcePackage,
    version,
  };
}

export function toVirtualTypePackPath(fileName: string): string {
  const normalized = toPosixPath(fileName);
  const marker = '/node_modules/';
  const markerIndex = normalized.indexOf(marker);
  if (markerIndex >= 0) {
    return normalized.slice(markerIndex);
  }
  if (normalized.startsWith('node_modules/')) {
    return `/${normalized}`;
  }
  throw new Error(`RunJS type-pack file is outside node_modules: ${fileName}`);
}

function createDefinitionMap(
  definitions: readonly RunJSTypeLibraryPackDefinition[],
): Map<string, RunJSTypeLibraryPackDefinition> {
  const definitionById = new Map<string, RunJSTypeLibraryPackDefinition>();
  for (const definition of definitions) {
    if (!definition.id || !definition.libraryName || !definition.entry) {
      throw new Error('RunJS type-pack definitions require id, libraryName, and entry');
    }
    if (definitionById.has(definition.id)) {
      throw new Error(`Duplicate RunJS type-pack definition: ${definition.id}`);
    }
    definitionById.set(definition.id, definition);
  }
  return definitionById;
}

function createRootFiles(inputs: readonly RunJSTypeLibraryPackRootFileInput[]): RunJSTypeLibraryFile[] {
  return inputs
    .map((input) => {
      const content = normalizeText(input.content);
      return {
        path: normalizeVirtualPackPath(input.path),
        content,
        contentHash: sha256Hex(content),
      };
    })
    .sort((left, right) => left.path.localeCompare(right.path));
}

function collectInheritedFiles(
  dependencies: readonly GeneratedPackRecord[],
  generatedById: ReadonlyMap<string, GeneratedPackRecord>,
): Map<string, string> {
  const inheritedFiles = new Map<string, string>();
  const visited = new Set<string>();
  const visit = (record: GeneratedPackRecord): void => {
    if (visited.has(record.pack.id)) {
      return;
    }
    visited.add(record.pack.id);
    for (const dependency of record.pack.dependencies) {
      const dependencyRecord = generatedById.get(dependency.id);
      if (dependencyRecord) {
        visit(dependencyRecord);
      }
    }
    for (const file of [...record.pack.rootFiles, ...record.pack.dependencyFiles]) {
      const existing = inheritedFiles.get(file.path);
      if (existing && existing !== file.contentHash) {
        throw new RunJSTypePackPathConflictError(file.path, existing, file.contentHash);
      }
      inheritedFiles.set(file.path, file.contentHash);
    }
  };
  dependencies.forEach(visit);
  return inheritedFiles;
}

function excludeInheritedFiles(
  files: readonly RunJSTypeLibraryFile[],
  inheritedFiles: ReadonlyMap<string, string>,
): RunJSTypeLibraryFile[] {
  return files.filter((file) => {
    const inheritedHash = inheritedFiles.get(file.path);
    if (!inheritedHash) {
      return true;
    }
    if (inheritedHash !== file.contentHash) {
      throw new RunJSTypePackPathConflictError(file.path, inheritedHash, file.contentHash);
    }
    return false;
  });
}

function buildPackContentHash(input: {
  definition: RunJSTypeLibraryPackDefinition;
  version: string;
  sourcePackage: string;
  dependencies: readonly RunJSTypeLibraryPackDependency[];
  rootFiles: readonly RunJSTypeLibraryFile[];
  dependencyFiles: readonly RunJSTypeLibraryFile[];
}): string {
  return sha256Hex(
    stableSerialize({
      id: input.definition.id,
      libraryName: input.definition.libraryName,
      entry: input.definition.entry,
      version: input.version,
      sourcePackage: input.sourcePackage,
      dependencies: input.dependencies,
      triggers: stableUnique(input.definition.triggers || [input.definition.id]),
      metadata: input.definition.metadata || {},
      rootFiles: input.rootFiles.map(fileHashRecord),
      dependencyFiles: input.dependencyFiles.map(fileHashRecord),
    }),
  );
}

function buildDeclarationGraphHash(dependencyFiles: readonly RunJSTypeLibraryFile[]): string {
  return sha256Hex(stableSerialize(dependencyFiles.map(fileHashRecord)));
}

function fileHashRecord(file: RunJSTypeLibraryFile): Pick<RunJSTypeLibraryFile, 'path' | 'contentHash'> {
  return { path: file.path, contentHash: file.contentHash };
}

function validateGlobalFileHashes(pack: RunJSTypeLibraryPack, seenFiles: Map<string, string>): void {
  for (const file of [...pack.rootFiles, ...pack.dependencyFiles]) {
    const existing = seenFiles.get(file.path);
    if (existing && existing !== file.contentHash) {
      throw new RunJSTypePackPathConflictError(file.path, existing, file.contentHash);
    }
    seenFiles.set(file.path, file.contentHash);
  }
}

function buildGeneratedArtifacts(records: readonly GeneratedPackRecord[]): Map<string, string> {
  const artifacts = new Map<string, string>();
  const recordsByGraphHash = groupPackRecordsByGraphHash(records);
  for (const [graphHash, graphRecords] of [...recordsByGraphHash].sort(([left], [right]) =>
    left.localeCompare(right),
  )) {
    artifacts.set(`graphs/${graphHash}.ts`, renderGraphModule(graphRecords));
  }
  artifacts.set('manifest.ts', renderManifestModule(records.map((record) => record.manifest)));
  artifacts.set('loaders.ts', renderLoadersModule(records));
  return artifacts;
}

function renderGraphModule(records: readonly GeneratedPackRecord[]): string {
  const dependencyFiles = records[0]?.pack.dependencyFiles;
  if (!dependencyFiles) {
    throw new Error('Cannot render an empty generated RunJS type-library graph');
  }
  const descriptors = Object.fromEntries(records.map((record) => [record.pack.id, createPackDescriptor(record.pack)]));
  return `${licenseHeader()}\n${generatedMarker}\n${generatedEslintDisable}\n\nimport type { RunJSTypeLibraryFile, RunJSTypeLibraryPack } from '@nocobase/runjs/client-v2';\n\ntype GeneratedRunJSTypeLibraryPackDescriptor = Omit<RunJSTypeLibraryPack, 'dependencyFiles'>;\n\ninterface GeneratedRunJSTypeLibraryGraph {\n  dependencyFiles: readonly RunJSTypeLibraryFile[];\n  packDescriptors: Readonly<Record<string, GeneratedRunJSTypeLibraryPackDescriptor>>;\n}\n\nconst graph: GeneratedRunJSTypeLibraryGraph = {\n  dependencyFiles: ${JSON.stringify(
    dependencyFiles,
    null,
    2,
  )},\n  packDescriptors: ${JSON.stringify(descriptors, null, 2)},\n};\n\nexport default graph;\n`;
}

function renderManifestModule(entries: readonly GeneratedRunJSTypeLibraryPackManifestEntry[]): string {
  const renderedEntries = entries.map((entry) => `  ${JSON.stringify(entry)}`).join(',\n');
  return `${licenseHeader()}\n${generatedMarker}\n${generatedEslintDisable}\n\nexport interface GeneratedRunJSTypeLibraryPackManifestEntry {\n  id: string;\n  libraryName: string;\n  version: string;\n  entry: string;\n  sourcePackage: string;\n  dependencies: readonly { id: string; version: string; contentHash: string }[];\n  triggers: readonly string[];\n  contentHash: string;\n  graphHash: string;\n  fileCount: number;\n  rootFileCount: number;\n  dependencyFileCount: number;\n  graphRawBytes: number;\n  rawBytes: number;\n}\n\nexport const generatedRunJSTypeLibraryPackManifest: readonly GeneratedRunJSTypeLibraryPackManifestEntry[] = [\n${renderedEntries}\n];\n`;
}

function renderLoadersModule(records: readonly GeneratedPackRecord[]): string {
  const recordsByGraphHash = groupPackRecordsByGraphHash(records);
  const graphLoaders = [...recordsByGraphHash.keys()]
    .sort()
    .map((graphHash) => `  ${JSON.stringify(graphHash)}: async () => (await import('./graphs/${graphHash}')).default,`)
    .join('\n');
  const loaders = records
    .map(
      (record) =>
        `  ${JSON.stringify(record.pack.id)}: () => loadGeneratedRunJSTypeLibraryPack(${JSON.stringify(
          record.pack.id,
        )}, ${JSON.stringify(record.graphHash)}),`,
    )
    .join('\n');
  return `${licenseHeader()}\n${generatedMarker}\n${generatedEslintDisable}\n\nimport type { RunJSTypeLibraryFile, RunJSTypeLibraryPack } from '@nocobase/runjs/client-v2';\n\ntype GeneratedRunJSTypeLibraryPackDescriptor = Omit<RunJSTypeLibraryPack, 'dependencyFiles'>;\ninterface GeneratedRunJSTypeLibraryGraph {\n  dependencyFiles: readonly RunJSTypeLibraryFile[];\n  packDescriptors: Readonly<Record<string, GeneratedRunJSTypeLibraryPackDescriptor>>;\n}\ntype GeneratedRunJSTypeLibraryGraphLoader = () => Promise<GeneratedRunJSTypeLibraryGraph>;\n\nexport type GeneratedRunJSTypeLibraryPackLoader = () => Promise<RunJSTypeLibraryPack>;\n\nconst generatedRunJSTypeLibraryGraphLoaders: Readonly<Record<string, GeneratedRunJSTypeLibraryGraphLoader>> = {\n${graphLoaders}\n};\n\nconst generatedRunJSTypeLibraryGraphPromises = new Map<string, Promise<GeneratedRunJSTypeLibraryGraph>>();\n\nfunction loadGeneratedRunJSTypeLibraryGraph(graphHash: string): Promise<GeneratedRunJSTypeLibraryGraph> {\n  const cached = generatedRunJSTypeLibraryGraphPromises.get(graphHash);\n  if (cached) {\n    return cached;\n  }\n  const loader = generatedRunJSTypeLibraryGraphLoaders[graphHash];\n  if (!loader) {\n    return Promise.reject(new Error(\`Unknown generated RunJS type-library graph: \${graphHash}\`));\n  }\n  const promise = loader().catch((error: unknown) => {\n    generatedRunJSTypeLibraryGraphPromises.delete(graphHash);\n    throw error;\n  });\n  generatedRunJSTypeLibraryGraphPromises.set(graphHash, promise);\n  return promise;\n}\n\nasync function loadGeneratedRunJSTypeLibraryPack(\n  packId: string,\n  graphHash: string,\n): Promise<RunJSTypeLibraryPack> {\n  const graph = await loadGeneratedRunJSTypeLibraryGraph(graphHash);\n  const descriptor = graph.packDescriptors[packId];\n  if (!descriptor) {\n    throw new Error(\`Unknown generated RunJS type-library pack \${packId} in graph \${graphHash}\`);\n  }\n  return { ...descriptor, dependencyFiles: graph.dependencyFiles };\n}\n\nexport const generatedRunJSTypeLibraryPackLoaders: Readonly<Record<string, GeneratedRunJSTypeLibraryPackLoader>> = {\n${loaders}\n};\n`;
}

function groupPackRecordsByGraphHash(records: readonly GeneratedPackRecord[]): Map<string, GeneratedPackRecord[]> {
  const recordsByGraphHash = new Map<string, GeneratedPackRecord[]>();
  for (const record of records) {
    const graphRecords = recordsByGraphHash.get(record.graphHash) || [];
    graphRecords.push(record);
    recordsByGraphHash.set(record.graphHash, graphRecords);
  }
  return recordsByGraphHash;
}

function createPackDescriptor(pack: RunJSTypeLibraryPack): Omit<RunJSTypeLibraryPack, 'dependencyFiles'> {
  return {
    id: pack.id,
    libraryName: pack.libraryName,
    version: pack.version,
    contentHash: pack.contentHash,
    dependencies: pack.dependencies,
    rootFiles: pack.rootFiles,
    metadata: pack.metadata,
  };
}

async function findStaleArtifacts(outputDirectory: string, expected: ReadonlyMap<string, string>): Promise<string[]> {
  const stale: string[] = [];
  for (const relativePath of [...expected.keys()].sort()) {
    const expectedContent = expected.get(relativePath);
    let actualContent: string | undefined;
    try {
      actualContent = await fs.readFile(path.join(outputDirectory, relativePath), 'utf8');
    } catch (error) {
      if (!isMissingFileError(error)) {
        throw error;
      }
    }
    if (expectedContent !== actualContent) {
      stale.push(relativePath);
    }
  }
  return stale;
}

async function writeGeneratedArtifacts(outputDirectory: string, artifacts: ReadonlyMap<string, string>): Promise<void> {
  await fs.rm(outputDirectory, { recursive: true, force: true });
  for (const [relativePath, content] of artifacts) {
    const fileName = path.join(outputDirectory, relativePath);
    await fs.mkdir(path.dirname(fileName), { recursive: true });
    await fs.writeFile(fileName, content, 'utf8');
  }
}

function getOwningPackageJsonPath(fileName: string): string | undefined {
  const normalized = toPosixPath(fileName);
  const marker = '/node_modules/';
  const markerIndex = normalized.indexOf(marker);
  if (markerIndex < 0) {
    return undefined;
  }
  const packageStart = markerIndex + marker.length;
  const segments = normalized.slice(packageStart).split('/');
  const packageSegmentCount = segments[0]?.startsWith('@') ? 2 : 1;
  if (segments.length < packageSegmentCount) {
    return undefined;
  }
  const packageRoot = normalized.slice(0, packageStart) + segments.slice(0, packageSegmentCount).join('/');
  return path.normalize(`${packageRoot}/package.json`);
}

async function readPackageJson(fileName: string): Promise<PackageJsonRecord> {
  try {
    const value: unknown = JSON.parse(await fs.readFile(fileName, 'utf8'));
    if (!value || typeof value !== 'object' || Array.isArray(value)) {
      return {};
    }
    const record = value as Record<string, unknown>;
    return {
      name: typeof record.name === 'string' ? record.name : undefined,
      version: typeof record.version === 'string' ? record.version : undefined,
    };
  } catch (error) {
    if (isMissingFileError(error)) {
      return {};
    }
    throw error;
  }
}

function readPackageJsonSync(fileName: string): PackageJsonRecord {
  const content = ts.sys.readFile(fileName);
  if (typeof content !== 'string') {
    return {};
  }
  const value: unknown = JSON.parse(content);
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    return {};
  }
  const record = value as Record<string, unknown>;
  return {
    name: typeof record.name === 'string' ? record.name : undefined,
    version: typeof record.version === 'string' ? record.version : undefined,
  };
}

function normalizeVirtualPackPath(value: string): string {
  const normalized = toPosixPath(value).replace(/\/+/gu, '/');
  if (!normalized.startsWith('/') || normalized.includes('/../') || normalized.endsWith('/..')) {
    throw new Error(`Invalid RunJS type-pack virtual path: ${value}`);
  }
  return path.posix.normalize(normalized);
}

function stableUnique(values: readonly string[]): string[] {
  return [...new Set(values)].sort();
}

function isInsideNodeModules(fileName: string): boolean {
  const normalized = toPosixPath(fileName);
  return normalized.includes('/node_modules/') || normalized.startsWith('node_modules/');
}

function toPosixPath(value: string): string {
  return String(value).replace(/\\/gu, '/').replace(/\/+/gu, '/');
}

function isMissingFileError(error: unknown): boolean {
  return Boolean(error && typeof error === 'object' && 'code' in error && error.code === 'ENOENT');
}

function licenseHeader(): string {
  return `/**\n * This file is part of the NocoBase (R) project.\n * Copyright (c) 2020-2024 NocoBase Co., Ltd.\n * Authors: NocoBase Team.\n *\n * This project is dual-licensed under AGPL-3.0 and NocoBase Commercial License.\n * For more information, please refer to: https://www.nocobase.com/agreement.\n */`;
}
