/**
 * This file is part of the NocoBase (R) project.
 * Copyright (c) 2020-2024 NocoBase Co., Ltd.
 * Authors: NocoBase Team.
 *
 * This project is dual-licensed under AGPL-3.0 and NocoBase Commercial License.
 * For more information, please refer to: https://www.nocobase.com/agreement.
 */

import { Schema } from '@formily/json-schema';
import type { Database } from '@nocobase/database';
import _ from 'lodash';
import FlowModelRepository from '../repository';
import { getCollectionName, getCollectionTitle, getFieldName, getFieldTitle } from './service-helpers';
import { getNodeSubModelList, getSingleNodeSubModel } from './service-utils';
import type { FlowSurfaceTemplateRow } from './template-service-utils';

export type TemplateTranslate = (key: string, options?: Record<string, any>) => string;

const AUTO_GENERATED_SUFFIX = ' (Auto generated)';
const LEGACY_AUTO_POPUP_PREFIX = 'Auto popup ';
const LEGACY_AUTO_POPUP_DESCRIPTION_PREFIX = 'Auto-generated popup template ';

function getFallbackTranslate() {
  return (key: string, options?: Record<string, any>) =>
    key.replace(/\{\{\s*([^}\s]+)\s*\}\}/g, (_match, name) => {
      const value = options?.[name];
      return _.isUndefined(value) || _.isNull(value) ? '' : String(value);
    });
}

function extractTranslationKey(tokenContent: string) {
  const matched = tokenContent.match(/["'`]([^"'`]+)["'`]/);
  return matched?.[1]?.trim() || '';
}

function sanitizePendingTranslationTokens(value: string) {
  if (!value.includes('{{')) {
    return value;
  }
  return value.replace(/\{\{\s*t\(([\s\S]*?)\)\s*\}\}/g, (_match, tokenContent) => extractTranslationKey(tokenContent));
}

export function compileTemplateString(value: any, t?: TemplateTranslate) {
  if (typeof value !== 'string' || !value) {
    return value;
  }
  try {
    const compiled = Schema.compile(value, { t: t || getFallbackTranslate() });
    if (typeof compiled === 'string') {
      return sanitizePendingTranslationTokens(compiled).trim();
    }
    return compiled;
  } catch (error) {
    return sanitizePendingTranslationTokens(value).trim();
  }
}

function inferPopupDefaultTypeFromTargetTree(node: any): 'view' | 'edit' | 'addNew' | 'generic' {
  const popupPage = getSingleNodeSubModel(node?.subModels?.page);
  const popupTab = _.castArray(popupPage?.subModels?.tabs || [])[0];
  const popupGrid = getSingleNodeSubModel(popupTab?.subModels?.grid);
  const popupBlock = getNodeSubModelList(popupGrid?.subModels?.items)[0];
  if (popupBlock?.use === 'DetailsBlockModel') {
    return 'view';
  }
  if (popupBlock?.use === 'EditFormModel') {
    return 'edit';
  }
  if (popupBlock?.use === 'CreateFormModel') {
    return 'addNew';
  }
  return 'generic';
}

function getPopupLabelKey(defaultType: 'view' | 'edit' | 'addNew' | 'generic') {
  switch (defaultType) {
    case 'addNew':
      return 'Popup for Add New';
    case 'edit':
      return 'Popup for Edit';
    case 'view':
      return 'Popup for Details';
    default:
      return 'popup';
  }
}

function getAutoGeneratedDisplaySuffix(t?: TemplateTranslate) {
  const translate = t || getFallbackTranslate();
  return ` (${translate('Auto generated')})`;
}

function isAutoGeneratedPopupTemplateName(name: string) {
  return name.endsWith(AUTO_GENERATED_SUFFIX) || name.startsWith(LEGACY_AUTO_POPUP_PREFIX);
}

function isAutoGeneratedPopupTemplateDescription(description: string) {
  return (
    description.startsWith(LEGACY_AUTO_POPUP_DESCRIPTION_PREFIX) ||
    description.startsWith('Automatically generated popup template for ')
  );
}

function buildAutoGeneratedActionPopupMetadata(input: {
  popupType: 'view' | 'edit' | 'addNew' | 'generic';
  collectionLabel: string;
  t?: TemplateTranslate;
}) {
  const translate = input.t || getFallbackTranslate();
  const popupLabel = translate(getPopupLabelKey(input.popupType));
  return {
    name: `${input.collectionLabel} ${popupLabel}${getAutoGeneratedDisplaySuffix(input.t)}`,
    description: translate(
      'Automatically generated popup template for collection "{{collectionLabel}}" ({{popupLabel}}).',
      {
        collectionLabel: input.collectionLabel,
        popupLabel,
      },
    ),
  };
}

function buildAutoGeneratedAssociationPopupMetadata(input: {
  popupType: 'view' | 'edit' | 'addNew' | 'generic';
  sourceCollectionLabel: string;
  associationFieldLabel: string;
  targetCollectionLabel: string;
  t?: TemplateTranslate;
}) {
  const translate = input.t || getFallbackTranslate();
  const popupLabel = translate(getPopupLabelKey(input.popupType));
  return {
    name: `${input.sourceCollectionLabel} -> ${
      input.associationFieldLabel
    } ${popupLabel}${getAutoGeneratedDisplaySuffix(input.t)}`,
    description: translate(
      'Automatically generated popup template for relation field "{{associationFieldLabel}}" in collection "{{sourceCollectionLabel}}", targeting "{{targetCollectionLabel}}" ({{popupLabel}}).',
      {
        associationFieldLabel: input.associationFieldLabel,
        sourceCollectionLabel: input.sourceCollectionLabel,
        targetCollectionLabel: input.targetCollectionLabel,
        popupLabel,
      },
    ),
  };
}

async function getTargetTree(db: Database, targetUid?: string, transaction?: any) {
  const normalizedTargetUid = String(targetUid || '').trim();
  if (!normalizedTargetUid) {
    return null;
  }
  const repo = db.getCollection('flowModels')?.repository as FlowModelRepository;
  if (!repo) {
    return null;
  }
  return repo.findModelById(normalizedTargetUid, {
    transaction,
    includeAsyncNode: true,
  });
}

function getCollection(db: Database, dataSourceKey: string | undefined, collectionName: string | undefined) {
  const normalizedDataSourceKey = dataSourceKey || 'main';
  const mainCollection = normalizedDataSourceKey === 'main' ? (db as any).getCollection?.(collectionName) : null;
  if (mainCollection) {
    return mainCollection;
  }
  const dataSourceManager = (db as any).app?.dataSourceManager || (db as any).dataSourceManager;
  const ds =
    dataSourceManager?.get?.(normalizedDataSourceKey) || dataSourceManager?.dataSources?.get?.(normalizedDataSourceKey);
  return ds?.collectionManager?.getCollection?.(collectionName) || (db as any).getCollection?.(collectionName);
}

function getAssociationField(collection: any, associationName?: string) {
  const normalized = String(associationName || '').trim();
  if (!normalized) {
    return null;
  }
  const fieldName = normalized.split('.').slice(-1)[0];
  return collection?.getField?.(fieldName) || null;
}

function parseAssociationSource(associationName?: string) {
  const normalized = String(associationName || '').trim();
  if (!normalized || !normalized.includes('.')) {
    return null;
  }
  const parts = normalized.split('.').filter(Boolean);
  if (parts.length < 2) {
    return null;
  }
  return {
    sourceCollectionName: parts[0],
    associationFieldName: parts[parts.length - 1],
  };
}

async function buildAutoGeneratedPopupMetadata(
  db: Database,
  row: FlowSurfaceTemplateRow,
  t?: TemplateTranslate,
  transaction?: any,
) {
  const targetTree = await getTargetTree(db, row.targetUid, transaction);
  const popupType = inferPopupDefaultTypeFromTargetTree(targetTree);
  const dataSourceKey = String(row.dataSourceKey || 'main').trim() || 'main';
  const collectionName = String(row.collectionName || '').trim();
  const associationName = String(row.associationName || '').trim();
  const collection = getCollection(db, dataSourceKey, collectionName);
  const collectionLabel = String(
    compileTemplateString(getCollectionTitle(collection) || collectionName, t) || '',
  ).trim();

  if (associationName) {
    const associationSource = parseAssociationSource(associationName);
    const sourceCollectionName = associationSource?.sourceCollectionName || collectionName;
    const sourceCollection = getCollection(db, dataSourceKey, sourceCollectionName) || collection;
    const associationField =
      getAssociationField(sourceCollection, associationName) ||
      sourceCollection?.getField?.(associationSource?.associationFieldName || '');
    const targetCollectionName =
      String(associationField?.target || associationField?.options?.target || collectionName || '').trim() ||
      collectionName;
    const targetCollection = getCollection(db, dataSourceKey, targetCollectionName) || collection;
    const sourceCollectionLabel = String(
      compileTemplateString(
        getCollectionTitle(sourceCollection) || getCollectionName(sourceCollection) || sourceCollectionName,
        t,
      ) || '',
    ).trim();
    const associationFieldLabel = String(
      compileTemplateString(
        getFieldTitle(associationField) ||
          getFieldName(associationField) ||
          associationSource?.associationFieldName ||
          '',
        t,
      ) || '',
    ).trim();
    const targetCollectionLabel = String(
      compileTemplateString(
        getCollectionTitle(targetCollection) || getCollectionName(targetCollection) || targetCollectionName,
        t,
      ) || '',
    ).trim();
    if (sourceCollectionLabel && associationFieldLabel && targetCollectionLabel) {
      return buildAutoGeneratedAssociationPopupMetadata({
        popupType,
        sourceCollectionLabel,
        associationFieldLabel,
        targetCollectionLabel,
        t,
      });
    }
  }

  if (collectionLabel) {
    return buildAutoGeneratedActionPopupMetadata({
      popupType,
      collectionLabel,
      t,
    });
  }

  return null;
}

export async function resolveFlowTemplateDisplayRow(
  db: Database,
  row: FlowSurfaceTemplateRow,
  options: { t?: TemplateTranslate; transaction?: any } = {},
): Promise<FlowSurfaceTemplateRow> {
  const plainRow = typeof (row as any)?.toJSON === 'function' ? (row as any).toJSON() : row;
  if (!plainRow) {
    return plainRow;
  }
  const t = options.t || getFallbackTranslate();
  const nextRow: FlowSurfaceTemplateRow = {
    ...plainRow,
    name: compileTemplateString(plainRow.name, t),
    description: compileTemplateString(plainRow.description, t),
  };
  const hasAutoGeneratedName = isAutoGeneratedPopupTemplateName(String(nextRow.name || '').trim());
  const hasAutoGeneratedDescription = isAutoGeneratedPopupTemplateDescription(String(nextRow.description || '').trim());
  if (String(nextRow.type || '').trim() !== 'popup' || (!hasAutoGeneratedName && !hasAutoGeneratedDescription)) {
    return nextRow;
  }
  const rewritten = await buildAutoGeneratedPopupMetadata(db, nextRow, t, options.transaction);
  if (!rewritten) {
    return nextRow;
  }
  return {
    ...nextRow,
    name: hasAutoGeneratedName ? rewritten.name : nextRow.name,
    description: hasAutoGeneratedDescription ? rewritten.description : nextRow.description,
  };
}

export async function resolveFlowTemplateDisplayRows(
  db: Database,
  rows: FlowSurfaceTemplateRow[],
  options: { t?: TemplateTranslate; transaction?: any } = {},
) {
  return Promise.all(rows.map((row) => resolveFlowTemplateDisplayRow(db, row, options)));
}
