/**
 * This file is part of the NocoBase (R) project.
 * Copyright (c) 2020-2024 NocoBase Co., Ltd.
 * Authors: NocoBase Team.
 *
 * This project is dual-licensed under AGPL-3.0 and NocoBase Commercial License.
 * For more information, please refer to: https://www.nocobase.com/agreement.
 */

export const FLOW_SURFACE_REACTION_UNSUPPORTED_TARGET_KIND = 'FLOW_SURFACE_REACTION_UNSUPPORTED_TARGET_KIND';
export const FLOW_SURFACE_REACTION_AMBIGUOUS_SCENE = 'FLOW_SURFACE_REACTION_AMBIGUOUS_SCENE';
export const FLOW_SURFACE_REACTION_UNSUPPORTED_ACTION_FOR_SCENE = 'FLOW_SURFACE_REACTION_UNSUPPORTED_ACTION_FOR_SCENE';
export const FLOW_SURFACE_REACTION_UNKNOWN_TARGET_KEY = 'FLOW_SURFACE_REACTION_UNKNOWN_TARGET_KEY';
export const FLOW_SURFACE_REACTION_DUPLICATE_SLOT = 'FLOW_SURFACE_REACTION_DUPLICATE_SLOT';
export const FLOW_SURFACE_REACTION_INVALID_CONDITION_PATH = 'FLOW_SURFACE_REACTION_INVALID_CONDITION_PATH';
export const FLOW_SURFACE_REACTION_INVALID_CONDITION_OPERATOR = 'FLOW_SURFACE_REACTION_INVALID_CONDITION_OPERATOR';
export const FLOW_SURFACE_REACTION_INVALID_VALUE_SOURCE = 'FLOW_SURFACE_REACTION_INVALID_VALUE_SOURCE';
export const FLOW_SURFACE_REACTION_INVALID_VALUE_PATH = 'FLOW_SURFACE_REACTION_INVALID_VALUE_PATH';
export const FLOW_SURFACE_REACTION_INVALID_TARGET_FIELD = 'FLOW_SURFACE_REACTION_INVALID_TARGET_FIELD';
export const FLOW_SURFACE_REACTION_FINGERPRINT_CONFLICT = 'FLOW_SURFACE_REACTION_FINGERPRINT_CONFLICT';
export const FLOW_SURFACE_REACTION_FORM_ONLY = 'FLOW_SURFACE_REACTION_FORM_ONLY';
