/**
 * This file is part of the NocoBase (R) project.
 * Copyright (c) 2020-2024 NocoBase Co., Ltd.
 * Authors: NocoBase Team.
 *
 * This project is dual-licensed under AGPL-3.0 and NocoBase Commercial License.
 * For more information, please refer to: https://www.nocobase.com/agreement.
 */

import type { LightExtensionSettingsTypegenFile } from './settings-typegen';

export const LIGHT_EXTENSION_BINDING_CONTEXT_PATH = '.light-extension/types/context.d.ts';
export const LIGHT_EXTENSION_COLLECTION_TYPES_PATH = '.light-extension/types/collections.d.ts';

export type LightExtensionBindingContextMode = 'generic' | 'multiple' | 'precise';

export interface LightExtensionContextPackField {
  name: string;
  interface?: string;
  type?: string;
  nullable: boolean;
  enum?: Array<string | number | boolean>;
  associationTarget?: string;
  readable: boolean;
  writable: boolean;
}

export interface LightExtensionContextPackLike {
  contextPackVersion: 'light-extension.context-pack.v1';
  contextMode: LightExtensionBindingContextMode;
  reason: string;
  repoId: string;
  entry: {
    id: string;
    kind: string;
    entryName: string;
    entryPath: string;
    settingsSchema: Record<string, unknown> | null;
  };
  references: Array<{
    id: string;
    ownerKind: string;
    ownerLocator: unknown;
    ownerLocatorHash: string;
    resolvedStatus: string;
  }>;
  binding?: {
    referenceId: string;
    ownerLocatorHash: string;
    owner: {
      ownerKind: string;
      modelUid: string;
      modelUse: string;
      surface: string;
      dataSourceKey?: string;
      collectionName?: string;
    };
  };
  collection?: {
    dataSourceKey: string;
    name: string;
    title?: string;
    fields: LightExtensionContextPackField[];
  };
  supportedImports: string[];
  versions: {
    sdk: string;
    validator: string;
  };
  contextHash: string;
}

export interface LightExtensionBindingContextTypegenResult {
  contextHash: string;
  contextMode: LightExtensionBindingContextMode;
  entry: Pick<LightExtensionContextPackLike['entry'], 'id' | 'kind' | 'entryName' | 'entryPath'>;
  files: LightExtensionSettingsTypegenFile[];
  precise: boolean;
  reason: string;
}

type NormalizedField = LightExtensionContextPackField & {
  interface: string;
  type: string;
};

const generatedHeader = '// Generated by @nocobase/light-extension-sdk. Do not edit.';
const identifierPattern = /^[A-Za-z_$][A-Za-z0-9_$]*$/u;
const scalarStringTypes = new Set([
  'char',
  'citext',
  'date',
  'datetime',
  'email',
  'password',
  'phone',
  'richtext',
  'string',
  'text',
  'time',
  'uid',
  'url',
  'uuid',
]);
const scalarNumberTypes = new Set(['decimal', 'double', 'float', 'integer', 'number', 'percent', 'real', 'smallint']);
const scalarBooleanTypes = new Set(['bool', 'boolean']);
const toManyAssociationTypes = new Set(['belongstomany', 'hasmany']);
const associationTypes = new Set(['belongsto', 'belongstomany', 'hasmany', 'hasone']);

export function generateBindingContextTypes(
  contextPack: LightExtensionContextPackLike,
): LightExtensionBindingContextTypegenResult {
  const header = `${generatedHeader}\n// Context Hash: ${JSON.stringify(contextPack.contextHash)}`;
  const collection = contextPack.contextMode === 'precise' ? contextPack.collection : undefined;
  const fields = normalizeFields(collection?.fields || []);
  const precise = contextPack.contextMode === 'precise' && Boolean(contextPack.binding);
  const contextType = contextPack.entry.kind === 'js-page' ? 'JSPageContext' : 'JSBlockContext';

  return {
    contextHash: contextPack.contextHash,
    contextMode: contextPack.contextMode,
    entry: {
      id: contextPack.entry.id,
      kind: contextPack.entry.kind,
      entryName: contextPack.entry.entryName,
      entryPath: contextPack.entry.entryPath,
    },
    files: [
      {
        path: LIGHT_EXTENSION_COLLECTION_TYPES_PATH,
        content: buildCollectionTypes(header, collection, fields),
      },
      {
        path: LIGHT_EXTENSION_BINDING_CONTEXT_PATH,
        content: buildBindingContextType(header, contextType, precise && Boolean(collection)),
      },
    ],
    precise,
    reason: contextPack.reason,
  };
}

function buildCollectionTypes(
  header: string,
  collection: LightExtensionContextPackLike['collection'] | undefined,
  fields: NormalizedField[],
): string {
  if (!collection) {
    return [
      header,
      '',
      'export type CurrentRecord = unknown;',
      'export type CurrentCreateValues = unknown;',
      'export type CurrentUpdateValues = unknown;',
      'export type CurrentValues = unknown;',
      'export type CurrentCollection = unknown;',
      'export type CurrentCollectionField = unknown;',
      'export type CurrentDataSource = unknown;',
      'export interface LightExtensionCollections {}',
      '',
    ].join('\n');
  }

  const readableFields = fields.filter((field) => field.readable);
  const writableFields = readableFields.filter((field) => field.writable);
  const recordLines = buildProperties(readableFields, collection.name);
  const valueLines = buildProperties(writableFields, collection.name);
  const collectionName = JSON.stringify(collection.name);
  const dataSourceKey = JSON.stringify(collection.dataSourceKey);

  return [
    header,
    'import type { LightExtensionCollectionContext, LightExtensionDataSourceContext } from "@nocobase/light-extension-sdk/shared";',
    '',
    'export interface CurrentRecord {',
    ...recordLines,
    '}',
    '',
    'export interface CurrentCreateValues {',
    ...valueLines,
    '}',
    '',
    'export interface CurrentUpdateValues {',
    ...valueLines,
    '}',
    '',
    'export type CurrentValues = CurrentCreateValues | CurrentUpdateValues;',
    `export type CurrentCollection = LightExtensionCollectionContext<${dataSourceKey}, ${collectionName}, CurrentRecord, CurrentCreateValues, CurrentUpdateValues>;`,
    'export type CurrentCollectionField = unknown;',
    `export type CurrentDataSource = LightExtensionDataSourceContext<${dataSourceKey}>;`,
    '',
    'export interface LightExtensionCollections {',
    `  ${quoteProperty(collection.name)}: {`,
    '    record: CurrentRecord;',
    '    create: CurrentCreateValues;',
    '    update: CurrentUpdateValues;',
    '  };',
    '}',
    '',
  ].join('\n');
}

function buildBindingContextType(
  header: string,
  contextType: 'JSBlockContext' | 'JSPageContext',
  preciseCollection: boolean,
): string {
  const dataTypes = preciseCollection
    ? 'CurrentRecord, CurrentValues, CurrentCollection, CurrentCollectionField, CurrentDataSource'
    : 'unknown, unknown, unknown, unknown, unknown';
  return [
    header,
    `import type { ${contextType} } from "@nocobase/light-extension-sdk/client";`,
    ...(preciseCollection
      ? [
          'import type { CurrentCollection, CurrentCollectionField, CurrentDataSource, CurrentRecord, CurrentValues } from "./collections";',
        ]
      : []),
    '',
    `export type LightExtensionBindingContext<TSettings = unknown> = ${contextType}<TSettings, ${dataTypes}>;`,
    '',
  ].join('\n');
}

function buildProperties(fields: NormalizedField[], currentCollectionName: string): string[] {
  return fields.map((field) => `  ${quoteProperty(field.name)}?: ${fieldType(field, currentCollectionName)};`);
}

function fieldType(field: NormalizedField, currentCollectionName: string): string {
  const enumType = normalizeEnum(field.enum);
  let type = enumType || scalarType(field);
  if (field.associationTarget) {
    const targetShape = field.associationTarget === currentCollectionName ? 'CurrentRecord' : 'Record<string, unknown>';
    type = toManyAssociationTypes.has(field.type) ? `Array<${targetShape}>` : targetShape;
  }
  return field.nullable ? `${type} | null` : type;
}

function scalarType(field: NormalizedField): string {
  const candidates = [field.type, field.interface];
  if (candidates.some((value) => scalarStringTypes.has(value))) return 'string';
  if (candidates.some((value) => scalarNumberTypes.has(value))) return 'number';
  if (candidates.some((value) => scalarBooleanTypes.has(value))) return 'boolean';
  if (candidates.some((value) => associationTypes.has(value))) return 'Record<string, unknown>';
  return 'unknown';
}

function normalizeEnum(values: LightExtensionContextPackField['enum']): string | null {
  if (!Array.isArray(values)) return null;
  const literals = [...new Set(values.map((value) => JSON.stringify(value)))].sort();
  return literals.length ? literals.join(' | ') : null;
}

function normalizeFields(fields: LightExtensionContextPackField[]): NormalizedField[] {
  const byName = new Map<string, NormalizedField>();
  for (const field of fields) {
    if (!field || typeof field.name !== 'string' || !field.name || !field.readable || byName.has(field.name)) {
      continue;
    }
    byName.set(field.name, {
      ...field,
      interface: normalizeTypeName(field.interface),
      type: normalizeTypeName(field.type),
    });
  }
  return [...byName.values()].sort((left, right) => left.name.localeCompare(right.name));
}

function normalizeTypeName(value: string | undefined): string {
  return typeof value === 'string' ? value.replace(/[^a-zA-Z0-9]/gu, '').toLowerCase() : '';
}

function quoteProperty(value: string): string {
  return identifierPattern.test(value) ? value : JSON.stringify(value);
}
