import { gridRowColWrap } from '../utils';

// 页面里添加区块
export const BlockInitializers = {
  title: '{{t("Add block")}}',
  icon: 'PlusOutlined',
  wrap: gridRowColWrap,
  items: [
    {
      key: 'dataBlocks',
      type: 'itemGroup',
      title: '{{t("Data blocks")}}',
      children: [
        {
          role: 'button',
          'aria-label': 'data-block-table',
          key: 'table',
          type: 'item',
          title: '{{t("Table")}}',
          component: 'TableBlockInitializer',
        },
        {
          role: 'button',
          'aria-label': 'data-block-form',
          key: 'form',
          type: 'item',
          title: '{{t("Form")}}',
          component: 'FormBlockInitializer',
        },
        {
          role: 'button',
          'aria-label': 'data-block-details',
          key: 'details',
          type: 'item',
          title: '{{t("Details")}}',
          component: 'DetailsBlockInitializer',
        },
        {
          role: 'button',
          'aria-label': 'data-block-list',
          key: 'List',
          type: 'item',
          title: '{{t("List")}}',
          component: 'ListBlockInitializer',
        },
        {
          role: 'button',
          'aria-label': 'data-block-grid-card',
          key: 'GridCard',
          type: 'item',
          title: '{{t("Grid Card")}}',
          component: 'GridCardBlockInitializer',
        },
        {
          role: 'button',
          'aria-label': 'data-block-calendar',
          key: 'calendar',
          type: 'item',
          title: '{{t("Calendar")}}',
          component: 'CalendarBlockInitializer',
        },
        {
          role: 'button',
          'aria-label': 'data-block-kanban',
          key: 'kanban',
          type: 'item',
          title: '{{t("Kanban")}}',
          component: 'KanbanBlockInitializer',
        },
        {
          role: 'button',
          'aria-label': 'data-block-gantt',
          key: 'Gantt',
          type: 'item',
          title: '{{t("Gantt")}}',
          component: 'GanttBlockInitializer',
        },
      ],
    },
    {
      key: 'filterBlocks',
      type: 'itemGroup',
      title: '{{t("Filter blocks")}}',
      children: [
        {
          role: 'button',
          'aria-label': 'filter-block-form',
          key: 'filterForm',
          type: 'item',
          title: '{{t("Form")}}',
          component: 'FilterFormBlockInitializer',
        },
        {
          role: 'button',
          'aria-label': 'filter-block-collapse',
          key: 'filterCollapse',
          type: 'item',
          title: '{{t("Collapse")}}',
          component: 'FilterCollapseBlockInitializer',
        },
      ],
    },
    {
      key: 'media',
      type: 'itemGroup',
      title: '{{t("Other blocks")}}',
      children: [
        {
          role: 'button',
          'aria-label': 'block-markdown',
          key: 'markdown',
          type: 'item',
          title: '{{t("Markdown")}}',
          component: 'MarkdownBlockInitializer',
        },
        {
          role: 'button',
          'aria-label': 'block-audit-logs',
          key: 'auditLogs',
          type: 'item',
          title: '{{t("Audit logs")}}',
          component: 'AuditLogsBlockInitializer',
        },
      ],
    },
  ],
};
