/**
 * This file is part of the NocoBase (R) project.
 * Copyright (c) 2020-2024 NocoBase Co., Ltd.
 * Authors: NocoBase Team.
 *
 * This project is dual-licensed under AGPL-3.0 and NocoBase Commercial License.
 * For more information, please refer to: https://www.nocobase.com/agreement.
 */

const execa = require('execa');
const chokidar = require('chokidar');
const fs = require('fs-extra');
const path = require('path');
const { runWithPrefix } = require('../util');
const { discoverPortalRegistries } = require('./config');

const PORTAL_TEMPLATE_GIT_URL = 'git@github.com:nocobase/portal-template-default.git';
const PORTAL_TEMPLATE_REF = 'main';
const LOCAL_TEMPLATE_EXCLUDED_PATHS = new Set(['.git', 'node_modules', 'dist', 'dist-ssr']);

async function run(command, args, options = {}) {
  return execa(command, args, {
    stdio: 'inherit',
    ...options,
  });
}

function getPortalPnpmEnvironment(environment = {}) {
  const inheritedPath = environment.PATH || process.env.PATH || '';
  const nodeOptions = String(environment.NODE_OPTIONS || process.env.NODE_OPTIONS || '')
    .split(/\s+/)
    .filter((option) => option && option !== '--preserve-symlinks' && option !== '--preserve-symlinks-main')
    .join(' ');
  return {
    ...process.env,
    COREPACK_ENABLE_STRICT: '0',
    ...environment,
    NODE_OPTIONS: nodeOptions,
    NODE_PATH: '',
    PATH: [path.dirname(process.execPath), inheritedPath].filter(Boolean).join(path.delimiter),
  };
}

async function runPortalPnpm(args, options = {}) {
  return run('pnpm', args, {
    ...options,
    env: getPortalPnpmEnvironment(options.env),
  });
}

async function installPortalTemplateDependencies(workspacePath) {
  await runPortalPnpm(['install', '--frozen-lockfile'], { cwd: workspacePath });
}

function createPortalEnvironment(environment = process.env) {
  const appPort = Number(environment.APP_PORT) || 13000;
  const apiUrl = environment.NOCOBASE_API_URL || `http://127.0.0.1:${appPort}/api`;
  return [
    '# Generated by yarn portal-registry dev. Do not edit this managed file.',
    `NOCOBASE_API_URL=${JSON.stringify(apiUrl)}`,
    'NOCOBASE_PORTAL_BASE="/"',
    '',
  ].join('\n');
}

function getNocoBaseDevelopmentEnvironment(environment = process.env) {
  return {
    ...environment,
    APP_CLIENT_ENTRY_MODE: 'modern-only',
  };
}

function isNestedPath(parentPath, childPath) {
  const relativePath = path.relative(parentPath, childPath);
  return relativePath === '' || (!relativePath.startsWith('..') && !path.isAbsolute(relativePath));
}

async function validateLocalPortalTemplate(templatePath) {
  if (!(await fs.pathExists(templatePath)) || !(await fs.stat(templatePath)).isDirectory()) {
    throw new Error(`Local Portal Template directory does not exist: ${templatePath}`);
  }

  const missingFiles = [];
  for (const fileName of ['package.json', 'components.json']) {
    if (!(await fs.pathExists(path.resolve(templatePath, fileName)))) missingFiles.push(fileName);
  }
  if (missingFiles.length > 0) {
    throw new Error(`Invalid local Portal Template at ${templatePath}: missing ${missingFiles.join(', ')}`);
  }
}

async function ensurePortalTemplate({ cwd, workspacePath, templatePath }) {
  let localTemplatePath;
  if (templatePath) {
    localTemplatePath = path.resolve(cwd, templatePath);
    await validateLocalPortalTemplate(localTemplatePath);
    if (isNestedPath(localTemplatePath, workspacePath) || isNestedPath(workspacePath, localTemplatePath)) {
      throw new Error('Local Portal Template and Portal Registry workspace must not contain each other');
    }
  }

  await fs.remove(workspacePath);
  await fs.ensureDir(path.dirname(workspacePath));

  if (!localTemplatePath) {
    await run('git', ['clone', '--branch', PORTAL_TEMPLATE_REF, PORTAL_TEMPLATE_GIT_URL, workspacePath], { cwd });
    return;
  }

  await fs.copy(localTemplatePath, workspacePath, {
    filter: (sourcePath) => {
      const relativePath = path.relative(localTemplatePath, sourcePath);
      if (!relativePath) return true;
      return !LOCAL_TEMPLATE_EXCLUDED_PATHS.has(relativePath.split(path.sep)[0]);
    },
  });
}

async function copyPortalRegistrySource(sourcePath, targetPath, options = {}) {
  if (await fs.pathExists(targetPath)) {
    if (!options.overwrite) {
      throw new Error(`Portal Registry development target already exists: ${targetPath}`);
    }
    await fs.remove(targetPath);
  }
  await fs.copy(sourcePath, targetPath);
}

function getPortalRegistryDevelopmentMappings(registries, workspacePath) {
  const mappings = new Map();
  for (const registry of registries) {
    for (const item of registry.config.items) {
      const sourceRoot = path.resolve(registry.sourceRoot, item.source);
      const targetRoot = path.resolve(workspacePath, item.target);
      mappings.set(`${sourceRoot}\0${targetRoot}`, { sourceRoot, targetRoot });
    }
  }
  return [...mappings.values()];
}

function watchPortalRegistrySources(registries, workspacePath) {
  const sourceTargets = getPortalRegistryDevelopmentMappings(registries, workspacePath);
  const watcher = chokidar.watch([...new Set(sourceTargets.map(({ sourceRoot }) => sourceRoot))], {
    ignoreInitial: true,
    awaitWriteFinish: {
      stabilityThreshold: 50,
      pollInterval: 10,
    },
  });

  const resolveTargets = (sourcePath) =>
    sourceTargets.flatMap(({ sourceRoot, targetRoot }) => {
      const relativePath = path.relative(sourceRoot, sourcePath);
      if (relativePath.startsWith('..') || path.isAbsolute(relativePath)) return [];
      return [path.resolve(targetRoot, relativePath)];
    });
  const reportError = (error) => console.error(`Portal Registry source sync failed: ${error.message}`);
  const syncTargets = (sourcePath, operation) => {
    for (const targetPath of resolveTargets(sourcePath)) operation(targetPath).catch(reportError);
  };

  watcher
    .on('add', (sourcePath) => {
      syncTargets(sourcePath, (targetPath) => fs.copy(sourcePath, targetPath));
    })
    .on('change', (sourcePath) => {
      syncTargets(sourcePath, (targetPath) => fs.copy(sourcePath, targetPath));
    })
    .on('addDir', (sourcePath) => {
      syncTargets(sourcePath, (targetPath) => fs.ensureDir(targetPath));
    })
    .on('unlink', (sourcePath) => {
      syncTargets(sourcePath, (targetPath) => fs.remove(targetPath));
    })
    .on('unlinkDir', (sourcePath) => {
      syncTargets(sourcePath, (targetPath) => fs.remove(targetPath));
    })
    .on('error', reportError);

  return watcher;
}

async function preparePortalRegistryWorkspace(options = {}) {
  const cwd = path.resolve(options.cwd || process.cwd());
  const workspacePath = path.resolve(cwd, 'storage/portal-registry');
  await ensurePortalTemplate({ cwd, workspacePath, templatePath: options.templatePath });
  const registries = await discoverPortalRegistries({ cwd });

  try {
    const portalEnvironmentPath = path.resolve(workspacePath, '.env.local');
    await fs.writeFile(portalEnvironmentPath, createPortalEnvironment());

    const mappings = getPortalRegistryDevelopmentMappings(registries, workspacePath);
    for (const targetRoot of new Set(mappings.map((mapping) => mapping.targetRoot))) {
      await fs.remove(targetRoot);
    }
    for (const mapping of mappings) {
      await fs.copy(mapping.sourceRoot, mapping.targetRoot);
    }
  } catch (error) {
    await fs.remove(workspacePath);
    throw error;
  }

  return {
    workspacePath,
    registries,
  };
}

async function startPortalRegistryDevelopment(options = {}) {
  const cwd = path.resolve(options.cwd || process.cwd());
  const workspace = await preparePortalRegistryWorkspace({ cwd, templatePath: options.templatePath });
  const sourceWatcher = watchPortalRegistrySources(workspace.registries, workspace.workspacePath);

  try {
    await installPortalTemplateDependencies(workspace.workspacePath);
  } catch (error) {
    await sourceWatcher.close();
    throw error;
  }

  console.log('Portal Registry APIs serve dist/portal-registry. Run yarn portal-registry build after source changes.');
  const nocobase = execa('yarn', ['dev'], {
    cwd,
    stdio: 'inherit',
    env: getNocoBaseDevelopmentEnvironment(),
  });
  const portal = runWithPrefix('pnpm', ['run', 'dev', '--host', '0.0.0.0'], {
    cwd: workspace.workspacePath,
    prefix: 'portal-registry',
    color: 'green',
    env: getPortalPnpmEnvironment(),
    shell: false,
  });
  const children = [nocobase, portal];
  let stopping = false;
  const stop = (signal = 'SIGTERM') => {
    if (stopping) return;
    stopping = true;
    for (const child of children) {
      if (child.exitCode === null && child.signalCode === null) {
        child.kill(signal, { forceKillAfterTimeout: 3000 });
      }
    }
  };
  const handleSigint = () => stop('SIGINT');
  const handleSigterm = () => stop('SIGTERM');
  process.once('SIGINT', handleSigint);
  process.once('SIGTERM', handleSigterm);

  try {
    await Promise.race(children);
  } catch (error) {
    if (!stopping && error.signal !== 'SIGINT') throw error;
  } finally {
    stop();
    await Promise.allSettled([...children, sourceWatcher.close()]);
    process.removeListener('SIGINT', handleSigint);
    process.removeListener('SIGTERM', handleSigterm);
  }
}

module.exports = {
  LOCAL_TEMPLATE_EXCLUDED_PATHS,
  PORTAL_TEMPLATE_GIT_URL,
  PORTAL_TEMPLATE_REF,
  copyPortalRegistrySource,
  createPortalEnvironment,
  ensurePortalTemplate,
  getNocoBaseDevelopmentEnvironment,
  getPortalPnpmEnvironment,
  getPortalRegistryDevelopmentMappings,
  installPortalTemplateDependencies,
  isNestedPath,
  preparePortalRegistryWorkspace,
  runPortalPnpm,
  startPortalRegistryDevelopment,
  validateLocalPortalTemplate,
  watchPortalRegistrySources,
};
